Repository stolostron/console, pull requests merged in 2021-04, with the labels that each got.

#435 Bulk add/remove clusters to cluster set
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/src/NavigationPath.ts
  frontend/src/components/BulkActionModel.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageClusters/ClusterSetManageClusters.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageClusters/ClusterSetManageClusters.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSet.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterStatuses.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterDestroy.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/useAllClusters.tsx
Labels: approved, lgtm

#434 10462 no matching discovery
  backend/src/routes/watch.ts
  frontend/src/atoms.tsx
  frontend/src/lib/test-metadata.ts
  frontend/src/routes/Credentials/AddCredentials/AddAwsCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddAzureCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddBareMetalCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.tsx
  frontend/src/routes/Credentials/AddCredentials/AddGcpCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddRedHatCloudCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddVmwareCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/EditCredentials.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, lgtm

#436 Add cluster set label to ClusterDeployment
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
Labels: approved, lgtm

#437 Install config bug
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm

#438 use latest temptifly
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm

#440 Cluster pools page
  backend/src/routes/watch.ts
  frontend/public/locales/en/cluster.json
  frontend/src/NavigationPath.ts
  frontend/src/atoms.tsx
  frontend/src/resources/cluster-pool.ts
  frontend/src/routes/ClusterManagement/ClusterManagement.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
Labels: approved, lgtm

#441 Add conditional chain to conditions array in checkForCondition
  frontend/src/lib/get-cluster.ts
Labels: approved, lgtm

#442 Diagnostics
  frontend/package-lock.json
  frontend/package.json
  frontend/src/jest.d.ts
  frontend/src/lib/test-util.ts
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/setupTests.ts
Labels: approved, lgtm

#444 update packages
  backend/package-lock.json
  backend/package.json
  backend/src/routes/watch.ts
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm

#443 Cluster set updates to match APIs more closely
  frontend/public/locales/en/cluster.json
  frontend/src/lib/get-cluster.ts
  frontend/src/lib/patch-cluster.ts
  frontend/src/lib/rbac-util.ts
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageClusters/ClusterSetManageClusters.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageClusters/ClusterSetManageClusters.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSet.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/useCanJoinClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/useClusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ManagedClusterSetModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/useAllClusters.tsx
Labels: approved, lgtm

#439 Discovery empty states
  backend/src/routes/watch.ts
  frontend/package-lock.json
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/discovery.json
  frontend/src/atoms.tsx
  frontend/src/lib/test-metadata.ts
  frontend/src/routes/ClusterManagement/ClusterManagement.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, lgtm

#445 Handle login redirect on token expiration
  backend/src/app.ts
  backend/src/lib/cookies.ts
  backend/src/lib/json-request.ts
  backend/src/lib/server-side-events.ts
  backend/src/resources/status.ts
  backend/src/routes/oauth.ts
  backend/src/routes/watch.ts
  frontend/src/atoms.tsx
Labels: approved, lgtm

#448 Handle PolicyReport upgrade to v1alpha2
  frontend/src/resources/policy-report.ts
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
Labels: approved, lgtm

#447 Update packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm

#446 Add openstack
  CONTRIBUTING.md
  OWNERS
  frontend/public/locales/en/connection.json
  frontend/public/locales/en/create.json
  frontend/src/lib/providers.ts
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/endpoints.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/install-config.hbs
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.tsx
  frontend/src/routes/Credentials/AddCredentials/AddOpenStackCredentials.test.tsx
  frontend/src/routes/Credentials/Credentials.tsx
Labels: approved, lgtm

#451 Cluster pool expand rows with cluster list, claim cluster modal
  backend/src/routes/watch.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/atoms.tsx
  frontend/src/lib/get-cluster.ts
  frontend/src/resources/cluster-claim.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ScaleClusterPoolModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterStatuses.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/useClusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/useAllClusters.tsx
Labels: approved, lgtm

#449 Update the discoveredclusters api
  frontend/src/resources/discovered-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, lgtm

#454 Add import cluster action for detached clusters, add action filtering for Detaching status
  frontend/public/locales/en/cluster.json
  frontend/src/lib/import-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/Clusters.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
Labels: approved, lgtm

#455 update ui-components
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: approved, lgtm

#453 update image
  Dockerfile
  Dockerfile.prow
Labels: approved, lgtm

#452 Provider namespace tooltip text change
  frontend/public/locales/en/connection.json
  frontend/public/locales/en/create.json
Labels: approved, lgtm

#456 Add edit ManagedClusterSet labels
  frontend/public/locales/en/common.json
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSet.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/EditLabels.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/EditLabels.tsx
Labels: approved, lgtm

#457 Add detached clusters to ClusterStatuses component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterStatuses.tsx
Labels: approved, lgtm

#461 add ingress floating IP for openstack
  frontend/public/locales/en/create.json
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/install-config.hbs
Labels: approved, dco-signoff: yes, lgtm

#460 Machine pool UI
  backend/src/routes/watch.ts
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/NavigationPath.ts
  frontend/src/atoms.tsx
  frontend/src/lib/get-cluster.ts
  frontend/src/resources/machine-pool.ts
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
Labels: approved, dco-signoff: yes, lgtm

#464 Check for cluster image set failure condition
  frontend/public/locales/en/cluster.json
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/HiveNotification.tsx
Labels: approved, dco-signoff: yes, lgtm

#459 update ui-components
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/test-util.ts
  frontend/src/routes/BareMetalAssets/BareMetalAsset.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.test.tsx
  frontend/src/routes/Credentials/Credentials.test.tsx
Labels: approved, dco-signoff: no

#465 Update packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#428 add quotes around name when used for name or namespace
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/endpoints.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/install-config.hbs
  setup.sh
Labels: approved, lgtm

#463 spacing fix
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/AddCluster.tsx
Labels: approved, dco-signoff: no, lgtm

#469 Machine pool scaling
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/components/ScaleMachinePoolModal.tsx
Labels: approved, dco-signoff: yes, lgtm

#471 Fix machine pool status null pointer bug, remove launch console from cluster actions, change node links to anchor elements, update ui-components
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
Labels: approved, dco-signoff: yes, lgtm

#470 Secret to provider connection conversion
  backend/src/routes/watch.ts
  frontend/src/atoms.tsx
  frontend/src/lib/test-metadata.ts
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Credentials/Credentials.test.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: no, lgtm

#468 credentials table move column
  frontend/src/routes/Credentials/Credentials.tsx
Labels: approved, dco-signoff: yes, lgtm

#474 Create ClusterPool
  frontend/public/locales/en/create.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.ts
  frontend/src/lib/create-cluster.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataAWS.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataAZR.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataGCP.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/style.css
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/templates/install-config.hbs
Labels: approved, dco-signoff: yes, lgtm

#475 [release-2.2] add image set failure status
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/components/HiveNotification.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusField.tsx
Labels: approved, dco-signoff: yes, lgtm

#467 add credentials fix
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.tsx
Labels: approved, dco-signoff: yes, lgtm

#473 Credential table secret changes
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.tsx
  frontend/src/routes/Credentials/AddCredentials/Components/CloudConnectionForm.tsx
  frontend/src/routes/Credentials/AddCredentials/EditCredentials.test.tsx
  frontend/src/routes/Credentials/Credentials.tsx
Labels: approved, dco-signoff: yes, lgtm

#472 Import claimed cluster, disable console launch link while hibernating, add claim cluster button to pool table
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/lib/import-cluster.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
Labels: approved, dco-signoff: yes, lgtm

#478 Add update release image modal, add release notes to upgrade modal
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/lib/doc-util.ts
  frontend/src/lib/nock-util.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/UpdateReleaseImageModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/BatchUpgradeModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ReleaseNotesLink.tsx
Labels: approved, dco-signoff: yes, lgtm

#477 ansibleTowerSecret typed resource
  frontend/src/lib/providers.ts
  frontend/src/resources/ansible-tower-secret.ts
Labels: approved, dco-signoff: yes, lgtm

#479 Fix empty state link for cluster pools
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
Labels: approved, dco-signoff: yes, lgtm

#481 fix navigation redirect
  frontend/src/atoms.tsx
Labels: approved, dco-signoff: yes, lgtm

#482 Added actionList to cluster empty and bma empty
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/AddCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#483 update ui-components
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#458 Wizard & Ansible credentials addition
  frontend/public/locales/en/connection.json
  frontend/src/lib/providers.ts
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/Credentials/AddCredentials/AddAwsCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddAzureCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddBareMetalCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.tsx
  frontend/src/routes/Credentials/AddCredentials/AddGcpCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddOpenStackCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddRedHatCloudCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddVmwareCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/Components/AnsibleTowerSecretForm.tsx
  frontend/src/routes/Credentials/AddCredentials/Components/CloudConnectionForm.tsx
  frontend/src/routes/Credentials/AddCredentials/Components/CreateProviderWizard.test.tsx
  frontend/src/routes/Credentials/AddCredentials/Components/CreateProviderWizard.tsx
  frontend/src/routes/Credentials/AddCredentials/EditCredentials.test.tsx
  frontend/src/routes/Credentials/Credentials.tsx
Labels: approved, dco-signoff: no, do-not-merge/hold, lgtm

#480 Enable RBAC for multi DiscoveryConfigs
  frontend/public/locales/en/connection.json
  frontend/public/locales/en/discovery.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.ts
  frontend/src/components/discoveryVersions.json
  frontend/src/lib/providers.ts
  frontend/src/lib/test-metadata.ts
  frontend/src/resources/discovery-config.ts
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/AddCredentials.tsx
  frontend/src/routes/Credentials/AddCredentials/AddRedHatCloudCredentials.test.tsx
  frontend/src/routes/Credentials/AddCredentials/Components/CloudConnectionForm.tsx
  frontend/src/routes/Credentials/AddCredentials/Components/CreateProviderWizard.tsx
  frontend/src/routes/Credentials/Credentials.test.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#484 Cluster set access management UI
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/NavigationPath.ts
  frontend/src/resources/rbac.ts
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/useClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#488 UX updates
  frontend/public/locales/en/cluster.json
  frontend/src/components/BulkActionModel.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/UpdateReleaseImageModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Credentials/AddCredentials/EditCredentials.test.tsx
Labels: approved, dco-signoff: yes, lgtm

#489 change prow build badge in README
  README.md
Labels: approved, dco-signoff: yes, lgtm

#490 make default flavor m1.xlarge so openshift has enough memory on opens…
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
Labels: approved, dco-signoff: yes, lgtm

#486 change order of credential type in creation
  frontend/src/routes/Credentials/AddCredentials/Components/CreateProviderWizard.tsx
Labels: approved, dco-signoff: yes, lgtm

#487 Fix authentication check
  backend/src/app.ts
  backend/src/lib/respond.ts
  backend/src/routes/authenticated.ts
  backend/src/routes/oauth.ts
  backend/src/routes/watch.ts
  frontend/src/atoms.tsx
Labels: approved, dco-signoff: yes, lgtm

#491 Update packages 16
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#492 fix login redirect
  frontend/src/atoms.tsx
  frontend/src/lib/resource-request.ts
Labels: approved, dco-signoff: yes

#493 adjust server side events ping time
  backend/src/lib/server-side-events.ts
Labels: approved, dco-signoff: yes

#494 eventsource reconnect on close
  backend/src/routes/watch.ts
  frontend/src/atoms.tsx
Labels: dco-signoff: yes

#495 fix installconfig can be undefined in clusterdeployment
  frontend/src/lib/get-cluster.ts
Labels: approved, dco-signoff: yes, lgtm

#498 fix memory leak
  backend/src/routes/authenticated.ts
Labels: approved, dco-signoff: yes, lgtm

#497 Cluster pool updates
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/lib/delete-cluster.ts
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ScaleClusterPoolModal.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/UpdateReleaseImageModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageClusters/ClusterSetManageClusters.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSet.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/useClusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/BatchUpgradeModal.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/BatchUpgradeModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterDestroy.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterDestroy.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/DistributionField.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/DownloadConfigurationDropdown.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/EditLabels.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/HiveNotification.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ImportCommand.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/LoginCredentials.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ManagedClusterSetModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.test.tsx
Labels: approved, dco-signoff: yes, lgtm

#500 Machine pool scaling updates
  frontend/public/locales/en/cluster.json
  frontend/src/components/Rbac.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#501 force build to prime sonarcloud
  .triggerbuild
Labels: approved, dco-signoff: yes, lgtm

#502 Cluster set updates
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetClusterPools/ClusterSetClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetClusters/ClusterSetClusters.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageClusters/ClusterSetManageClusters.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSet.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSet.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSetModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ManagedClusterSetModal.tsx
Labels: approved, dco-signoff: yes, lgtm

#503 Add scripts
  package.json
  scripts/patch-deployment.sh
  scripts/setup-users.sh
Labels: approved, dco-signoff: yes, lgtm

#505 Page cards
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/BareMetalAssets/CreateBareMetalAsset.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterSettings/ClusterSettings.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Credentials/Credentials.tsx
Labels: approved, dco-signoff: yes, lgtm

#506 Credential wizard layout tweaks
  frontend/src/components/AcmDataForm.tsx
  frontend/src/routes/Credentials/Credentials.tsx
Labels: approved, dco-signoff: yes, lgtm

#504 Fix nested cluster table header string
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
Labels: approved, dco-signoff: yes, lgtm

#508 update-ui-components
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/BareMetalAssets/CreateBareMetalAsset.tsx
  frontend/src/routes/ClusterManagement/ClusterManagement.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes

#509 cleanup credentials wizard strings
  frontend/public/locales/en/credentials.json
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#507 Enables first set of RBAC additions to discoveredclusters tbl
  frontend/public/locales/en/discovery.json
  frontend/src/resources/discovered-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#516 misc bugs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#511 update patch deployment to force pod reload
  scripts/patch-deployment.sh
  scripts/setup-users.sh
Labels: approved, dco-signoff: yes, lgtm

#517 edit to Ansible provider host and token name
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#518 harden server side events
  backend/src/lib/server-side-events.ts
Labels: approved, dco-signoff: yes, lgtm

#520 Fix scaling alert appearing when node list is not updated in ManagedClusterInfo
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#513 integration page
  backend/src/routes/watch.ts
  frontend/public/locales/en/cluster.json
  frontend/src/NavigationPath.ts
  frontend/src/atoms.tsx
  frontend/src/components/DropdownActionModal.tsx
  frontend/src/resources/cluster-curator.ts
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.test.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.tsx
  frontend/src/routes/ClusterManagement/ClusterManagement.tsx
Labels: approved, dco-signoff: no, lgtm

#521 aligning ansible variable reference
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.tsx
Labels: approved, dco-signoff: yes, lgtm

#522 latest temptifly
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#523 Fix issues from enabling strong type checking
  backend/src/lib/server-side-events.ts
  frontend/src/atoms.tsx
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/BulkActionModel.tsx
  frontend/src/components/ConfirmModal.tsx
  frontend/src/components/ErrorPage.tsx
  frontend/src/index.tsx
  frontend/src/lib/bare-metal-assets.ts
  frontend/src/lib/create-cluster.ts
  frontend/src/lib/get-addons.ts
  frontend/src/lib/nock-util.ts
  frontend/src/lib/rbac-util.ts
  frontend/src/lib/useQuery.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
  frontend/tsconfig.json
Labels: approved, dco-signoff: yes, lgtm

#525 Use watch and update sidebar to use new policyreport
  backend/src/routes/watch.ts
  frontend/src/atoms.tsx
  frontend/src/resources/policy-report.ts
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
Labels: approved, dco-signoff: yes, lgtm

#512 add credentials show error page if no namespaces
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#519 update-packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#527 wizard-validation-styling
  frontend/src/components/AcmDataForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#530 update-packages
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#526 wizard detail view styling
  frontend/public/locales/en/common.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#531 Add creator/claimer to cluster details page
  frontend/public/locales/en/cluster.json
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
Labels: approved, dco-signoff: yes, lgtm

#533 Allow user to create a namespace from create cluster pool page
  frontend/public/locales/en/create.json
  frontend/src/lib/create-cluster.ts
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlData.js
Labels: approved, dco-signoff: yes, lgtm

#534 change ClusterDeployment installAttemptsLimit to 1
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#535 Fix expand icon showing when pool is scaled to 0 with existing claime…
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
Labels: approved, dco-signoff: yes, lgtm

#536 Fix display name not working in cluster sets
  frontend/src/routes/ClusterManagement/ClusterSets/components/useClusters.tsx
Labels: approved, dco-signoff: yes, lgtm
