Repository stolostron/console, pull requests merged in 2021-05, with the labels that each got.

#537 add livenessprobe
  backend/src/app.ts
  backend/src/lib/server.ts
  backend/src/routes/liveness.ts
  backend/src/routes/oauth.ts
  backend/src/routes/readiness.ts
Labels: approved, dco-signoff: yes, lgtm

#538 fix setup-users script
  scripts/setup-users.sh
Labels: approved, dco-signoff: yes, lgtm

#543 Status summary - Fix issue getting PolicyReport results
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
Labels: approved, dco-signoff: yes, lgtm

#514 [DNM] Cluster curator status roll up
  backend/src/routes/watch.ts
  frontend/public/locales/en/cluster.json
  frontend/src/atoms.tsx
  frontend/src/lib/get-cluster.ts
  frontend/src/resources/cluster-curator.ts
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/useAllClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#545 Handle older PolicyReport version
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
Labels: approved, dco-signoff: yes, lgtm

#544 fix ansible credentials
  frontend/src/resources/provider-connection.ts
Labels: approved, dco-signoff: yes, lgtm

#548 Cluster curator status roll up tweaks and add structure for upgrade + upgrade hooks
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/components/DistributionField.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusField.tsx
Labels: approved, dco-signoff: yes, lgtm

#549 Clean up auto-scale validation
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/components/ScaleMachinePoolModal.tsx
Labels: approved, dco-signoff: yes, lgtm

#550 Terminology cards for cluster sets and cluster pools
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/lib/doc-util.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
Labels: approved, dco-signoff: yes, lgtm

#551 Add curator statuses to ClusterStatuses component, update cluster overview with helper texts
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterStatuses.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#552 Add extra hive check to ScaleClusterAlert
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#554 Nls a
  frontend/public/locales/en/create.json
  frontend/public/locales/en/credentials.json
  setup.sh
Labels: approved, dco-signoff: yes, lgtm

#556 More NLS changes for default text field prompts
  frontend/public/locales/en/create.json
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataVMW.js
Labels: approved, dco-signoff: yes, lgtm

#541 reviewing ui content with brandi
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/public/locales/en/credentials.json
  frontend/public/locales/en/discovery.json
  frontend/src/lib/doc-util.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#562 Fix cluster set join rbac check bug
  frontend/src/lib/rbac-util.ts
Labels: approved, dco-signoff: yes, lgtm

#553 Use DiscoveredCluster DisplayName attribute
  frontend/src/resources/discovered-cluster.ts
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#563 update to latest ui-components with table tweaks
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterSettings/ClusterSettings.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#564 Move context provider to top of cluster details
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
Labels: approved, dco-signoff: yes, lgtm

#560 use wizard variant of temptifly
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/create.json
  frontend/src/resources/resource.ts
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/components/WrappedCreateBareMetalAssetModal.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataVMW.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/style.css
Labels: approved, dco-signoff: no, lgtm

#558 change edit credential to patch operation
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#555 7384 feature gate removal
  frontend/src/routes/ClusterManagement/ClusterManagement.test.tsx
  frontend/src/routes/ClusterManagement/ClusterManagement.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
Labels: approved, dco-signoff: no, do-not-merge/hold, lgtm

#557 docs
  docs/ARCHITECTURE.md
  docs/RESOURCES.md
Labels: approved, dco-signoff: yes, lgtm

#539 Create edit ansible templates
  frontend/public/locales/en/cluster.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.ts
  frontend/src/components/AcmDataForm.tsx
  frontend/src/resources/cluster-curator.ts
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#566 Change forms to use full screen instead of card
  frontend/src/components/AcmDataForm.tsx
  frontend/src/routes/BareMetalAssets/CreateBareMetalAsset.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#546 graceful kubernetes shutdown
  backend/src/lib/server.ts
Labels: approved, dco-signoff: yes, lgtm

#561 Discovery Table/ Discovery Config pages updates
  frontend/public/locales/en/credentials.json
  frontend/public/locales/en/discovery.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.ts
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#569 Convert Create cluster pool to wizard, pull code from create cluster, get connections from recoil
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataAWS.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataAZR.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataGCP.js
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataVMW.js
Labels: approved, dco-signoff: yes, lgtm

#571 Fix label name in hive templates for cluster sets
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#568 Update Discovery to v1alpha1
  backend/src/routes/watch.ts
  frontend/src/resources/discovered-cluster.ts
  frontend/src/resources/discovery-config.ts
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#572 Simple name
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataVMW.js
Labels: approved, dco-signoff: yes, lgtm

#576 fix table breakpoints
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterSettings/ClusterSettings.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#578 collapse cluster labels
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#574 Discovery Prompt, Notifications, and minor UI tweaks
  frontend/public/locales/en/discovery.json
  frontend/src/components/ACM-Discovery-illus.png
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryBanner/DiscoveryBanner.test.tsx
  frontend/src/routes/Discovery/DiscoveryBanner/DiscoveryBanner.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, do-not-merge/hold, lgtm

#584 console backend hardening
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/lib/fetch-retry.ts
  backend/src/lib/json-request.ts
  backend/src/lib/main.ts
  backend/src/lib/server-side-events.ts
  backend/src/lib/server.ts
  backend/src/routes/authenticated.ts
  backend/src/routes/events.ts
  backend/src/routes/liveness.ts
  backend/src/routes/oauth.ts
  backend/src/routes/readiness.ts
  backend/src/routes/search.ts
  frontend/src/atoms.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
Labels: approved, dco-signoff: yes, lgtm

#583 console-string-changes
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/discovery.json
Labels: approved, dco-signoff: yes, lgtm

#582 addition of token and server to automatically import
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#586 Update Notifications
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryComponents/Banner.test.tsx
  frontend/src/routes/Discovery/DiscoveryComponents/Banner.tsx
  frontend/src/routes/Discovery/DiscoveryComponents/Notification.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#587 casing fix
  frontend/public/locales/en/cluster.json
Labels: approved, dco-signoff: yes, lgtm

#585 handle login
  backend/src/routes/serve.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atoms.tsx
  frontend/src/lib/resource-request.ts
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#588 Remove prettier configs and remove create clusterpool rbac check
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
Labels: approved, dco-signoff: yes, lgtm

#589 streamline import cluster
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#590 Lots of fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.svg
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/create.json
  frontend/src/App.tsx
  frontend/src/components/BulkActionModel.tsx
  frontend/src/lib/units.ts
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/UpdateReleaseImageModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSetModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/EditLabels.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ImportCommand.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ImportCommand.tsx
Labels: approved, dco-signoff: yes, lgtm

#591 Fix setup script due to configmap addition
  setup.sh
Labels: approved, dco-signoff: yes, lgtm

#593 2.2.x - fix baremetal status
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
Labels: approved, dco-signoff: yes, lgtm

#596 update-packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#592 2.2.x - update packages that have issues
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#598 console backend watch timeout handling
  backend/src/lib/fetch-retry.ts
  backend/src/lib/request-retry.ts
  backend/src/routes/events.ts
Labels: approved, dco-signoff: yes, lgtm

#581 change label from providerconnection
  backend/src/routes/events.ts
  frontend/src/lib/test-metadata.ts
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.test.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Credentials/Credentials.test.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#601 fix displaying yaml secrets
  frontend/src/components/AcmDataForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#602 fix credential icons
  frontend/src/components/AcmSvgIcon.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#604 Check recoil cache for existing cluster, remove list ManagedClusterInfo check
  frontend/src/lib/create-cluster.ts
  frontend/src/resources/managed-cluster-info.ts
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#603 Cluster set - submariner features
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/NavigationPath.ts
  frontend/src/components/BulkActionModel.tsx
  frontend/src/lib/doc-util.ts
  frontend/src/lib/get-addons.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetClusterPools/ClusterSetClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetClusters/ClusterSetClusters.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/MultiClusterNetworkStatus.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/useClusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/LoginCredentials.tsx
Labels: approved, dco-signoff: yes, lgtm

#599 DiscoveryConfig - Make versions optional
  frontend/public/locales/en/discovery.json
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#605 Random fixes
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ImportCommand.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#597 Filter out Non-RHOCM Creds from dropdown
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#607 use sessionStorage, not localStorage
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryComponents/Notification.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#608 Update PolicyReport severity options
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebarIcons.js
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
Labels: approved, dco-signoff: yes, lgtm

#600 make import a secondary button in the toolbar
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#606 walking through more disco UI with brandi
  frontend/public/locales/en/discovery.json
Labels: approved, dco-signoff: yes, lgtm

#595 Auto fill server
  frontend/src/resources/discovered-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#613 Find token by name rather than array position
  setup.sh
Labels: approved, dco-signoff: yes, lgtm

#612 Populate PolicyReport reason& resolution data from configmap
  backend/src/routes/events.ts
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
Labels: approved, dco-signoff: yes, lgtm

#614 12655 disco tweaks
  frontend/public/locales/en/discovery.json
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#610 Prov regions
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAZR.js
Labels: approved, dco-signoff: yes, lgtm

#615 Fix typo in cluster set label
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#616 Update create cluster breadcrumb
  frontend/public/locales/en/create.json
Labels: approved, dco-signoff: yes, lgtm

#617 Increase import secret timeout, remove clean up logic
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ImportCommand.tsx
Labels: approved, dco-signoff: yes, lgtm

#622 ensure clouds.yaml is hidden by default
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#618 Handle new policyreport name
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
Labels: approved, dco-signoff: yes, lgtm

#611 credential wizard - changes from feedback
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/credentials.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#625 Update Curator status checks
  frontend/src/lib/get-cluster.ts
Labels: approved, dco-signoff: yes, lgtm

#624 Minor doc updates
  docs/ARCHITECTURE.md
  docs/RESOURCES.md
Labels: approved, dco-signoff: yes, lgtm

#626 fix temptifly wizard patternfly layout
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/style.css
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/style.css
Labels: approved, dco-signoff: yes, lgtm

#623 Fix Disco Notifications
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Discovery/DiscoveryComponents/Notification.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Discovery/DiscoveryConfig/DiscoveryConfig.tsx
Labels: approved, dco-signoff: yes, lgtm

#629 update-packages
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#630 Handle templates in Insight description texts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
  frontend/src/typings.d.ts
Labels: approved, dco-signoff: yes, lgtm

#633 adding type to discovered clusters table
  frontend/public/locales/en/discovery.json
  frontend/src/resources/discovered-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#631 configmap settings and feature gates support
  backend/config/settings
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/lib/config.ts
  backend/src/lib/main.ts
  backend/src/routes/events.ts
  backend/src/routes/serve.ts
  docs/featuregate.yaml
  features/cluster-sets.yaml
  frontend/src/atoms.tsx
Labels: approved, dco-signoff: yes, lgtm

#627 SubmarinerConfig additions
  backend/src/routes/events.ts
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/src/atoms.tsx
  frontend/src/lib/delete-submariner.ts
  frontend/src/lib/get-cluster.ts
  frontend/src/resources/secret.tsx
  frontend/src/resources/submariner-config.ts
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/MultiClusterNetworkStatus.tsx
Labels: approved, dco-signoff: yes, lgtm

#638 Tech/Dec preview alerts for Cluster pool, Cluster sets, Machine pools
  frontend/public/locales/en/cluster.json
  frontend/src/components/TechPreviewAlert.tsx
  frontend/src/lib/doc-util.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/Discovery/DiscoveredClusters/DiscoveredClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#637 add validation for clouds.yaml and cloud name
  CONTRIBUTING.md
  frontend/public/locales/en/credentials.json
  frontend/src/lib/validation.ts
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  package.json
Labels: approved, dco-signoff: yes, lgtm

#639 Rbac for submariner add-ons menu
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
Labels: approved, dco-signoff: yes, lgtm

#641 Alerts for api status messages
  frontend/public/locales/en/cluster.json
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterStatusMessageAlert.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusField.tsx
Labels: approved, dco-signoff: yes, lgtm

#643 add bare metal OS image URL validation AND Copyright not in file - husky failed
  frontend/public/locales/en/credentials.json
  frontend/src/components/TechPreviewAlert.tsx
  frontend/src/lib/validation.test.ts
  frontend/src/lib/validation.ts
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#642 Tweaks to ClusterStatusMessageAlert
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterStatusMessageAlert.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusField.tsx
Labels: approved, dco-signoff: yes, lgtm

#648 Wizard support for multiselect
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
Labels: approved, dco-signoff: yes, lgtm

#651 translate scale up/down title
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#644 Reversions of display name behavior, display claim name under cluster…
  frontend/public/locales/en/cluster.json
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/BatchChannelSelectModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/BatchUpgradeModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterActionDropdown.tsx
Labels: approved, dco-signoff: yes, lgtm

#652 Data form updates
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm
