Repository stolostron/console, pull requests merged in 2021-06, with the labels that each got.

#646 rename credentials fields
  frontend/public/locales/en/create.json
  frontend/public/locales/en/credentials.json
  frontend/src/lib/validation.ts
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/templates/install-config.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/install-config.hbs
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#634 Create wizard ansible additions
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/create.json
  frontend/src/resources/cluster-curator.ts
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: approved, dco-signoff: no, do-not-merge/hold, lgtm

#653 ordered string input support
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/components/DataForm/ExampleForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#650 Implementation of ProgressTracker for curator install jobs
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.tsx
Labels: approved, dco-signoff: yes, lgtm

#632 add alert toast on credential success
  frontend/public/locales/en/credentials.json
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes

#636 update to be consistent with Patternfly guidelines
  frontend/public/locales/en/bma.json
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/public/locales/en/create.json
  frontend/public/locales/en/credentials.json
  frontend/src/components/BulkActionModel.tsx
  frontend/src/lib/validation.test.ts
  frontend/src/routes/BareMetalAssets/BareMetalAsset.test.tsx
Labels: approved, dco-signoff: no, lgtm

#647 rename credential groups
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#654 Submariner install wizard, update SubmarinerConfig modal
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/common.json
  frontend/public/locales/en/credentials.json
  frontend/src/NavigationPath.ts
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/resources/submariner-config.ts
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/EditSubmarinerConfigModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAWS.js
Labels: approved, dco-signoff: yes, lgtm

#656 Bug fix for failed curator condition
  frontend/src/lib/get-cluster.ts
Labels: approved, dco-signoff: yes, lgtm

#655 translation-string reference fix + other bug fix (BMA status)
  frontend/public/locales/en/cluster.json
  frontend/src/routes/BareMetalAssets/BareMetalAsset.test.tsx
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.tsx
Labels: approved, dco-signoff: no, lgtm

#659 Fix scale math for auto-scale
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#660 data form subsections
  frontend/public/locales/en/cluster.json
  frontend/src/App.tsx
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/components/DataForm/ExampleForm.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#661 Use SectionGroups for Submariner installer
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#665 fix for BMA regression
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
Labels: approved, dco-signoff: yes, lgtm

#664 only update modal when it's closed/reopen
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/Clusters/components/BatchChannelSelectModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/BatchUpgradeModal.tsx
Labels: approved, dco-signoff: yes, lgtm

#668 Template Edit/Table fix
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomations.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#669 string fixes for template page
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/create.json
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#666 ManagedClusterSetBinding UI
  backend/src/routes/events.ts
  frontend/public/locales/en/cluster.json
  frontend/src/atoms.tsx
  frontend/src/lib/rbac-util.ts
  frontend/src/resources/managed-cluster-set-binding.ts
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ManagedClusterSetBindingModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#672 ansible job template extra variables
  frontend/public/locales/en/cluster.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/components/DataForm/ExampleForm.tsx
  frontend/src/lib/test-util.ts
  frontend/src/resources/cluster-curator.ts
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/ClusterManagement/AnsibleAutomations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#667 ipv6
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/install-config.hbs
Labels: approved, dco-signoff: yes, lgtm

#671 try a different handlebar fix for clouds.yaml
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#673 fix azure and GCP deployment after creds format change
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#674 Several fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/BulkActionModel.tsx
  frontend/src/lib/patch-cluster.ts
  frontend/src/routes/ClusterManagement/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSets.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSetModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterSetActionDropdown.test.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/components/useCanJoinClusterSets.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#677 Add success icons to create cluster set and claim cluster secondary modals
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/ClusterPools/components/ClusterClaimModal.tsx
  frontend/src/routes/ClusterManagement/ClusterSets/CreateClusterSet/CreateClusterSetModal.tsx
Labels: approved, dco-signoff: yes, lgtm

#678 package-updates
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: approved, dco-signoff: yes, lgtm

#675 Fix double table in manage resources confirm modal
  frontend/src/routes/ClusterManagement/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
Labels: approved, dco-signoff: yes, lgtm

#679 secret label change for temptifly create function
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#680 Automatically show cluster issue sidebar if redirected from search re…
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
Labels: approved, dco-signoff: yes, lgtm

#683 BMA modal change icon
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
Labels: approved, dco-signoff: yes, lgtm

#686 Import command support for OCP 3.11
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ImportCommand.tsx
Labels: approved, dco-signoff: yes, lgtm

#662 add SNO for AWS
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/create.json
  frontend/public/locales/en/credentials.json
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataVMW.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/templates/install-config.hbs
Labels: approved, dco-signoff: no, lgtm

#682 Status string updates
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/create.json
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.tsx
Labels: approved, dco-signoff: yes

#687 handle tile keyboard selection
  frontend/src/components/AcmDataForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#691 debug SNO
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: approved, dco-signoff: yes, lgtm

#692 Fix scaling alert bug caused by Submariner scaling on AWS
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#690 latest temptifly
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/test-util.ts
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/style.css
Labels: approved, dco-signoff: yes, lgtm

#689 Fix release image select width and enable batch update
  frontend/public/locales/en/cluster.json
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/ClusterPools.tsx
  frontend/src/routes/ClusterManagement/ClusterPools/components/UpdateReleaseImageModal.tsx
Labels: approved, dco-signoff: yes, lgtm

#694 Log link in status rollup
  backend/src/routes/events.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/cluster.json
  frontend/src/atoms.tsx
  frontend/src/resources/ansible-job.ts
  frontend/src/routes/ClusterManagement/ClusterSets/components/ClusterStatuses.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/HiveNotification.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/HiveNotification.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ProgressStepBar.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusField.tsx
Labels: approved, dco-signoff: yes, lgtm

#684 fix detail list yaml spacing
  frontend/src/components/AcmDataForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#676 ssh key validate newline
  frontend/public/locales/en/credentials.json
  frontend/src/lib/validation.test.ts
  frontend/src/lib/validation.ts
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
Labels: approved, dco-signoff: yes, lgtm

#698 Prepend rule ID to description column text in cluster details sidebar
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.test.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterPolicySidebar.tsx
Labels: approved, dco-signoff: yes, lgtm

#701 Fix scaling alert for SNO
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ScaleClusterAlert.tsx
Labels: approved, dco-signoff: yes, lgtm

#703 Update cluster sets to Tech Preview
  frontend/public/locales/en/cluster.json
Labels: approved, dco-signoff: yes, lgtm

#697 Add discovery telemetry annotations
  frontend/src/resources/managed-cluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: approved, dco-signoff: yes, lgtm

#696 fit and finish
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/create.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
Labels: approved, dco-signoff: yes, lgtm

#704 Small type checking fixes
  frontend/src/jest.d.ts
  frontend/src/lib/get-cluster.ts
  frontend/src/lib/validation.test.ts
  frontend/src/resources/cluster-provision.ts
  frontend/src/resources/managed-cluster-add-on.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/components/ScaleMachinePoolModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterStatusMessageAlert.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/EditLabels.tsx
  frontend/src/setupTests.ts
Labels: approved, dco-signoff: yes, lgtm

#699 Add Single node openshift for bare metal
  frontend/package-lock.json
  frontend/public/locales/en/create.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ProgressStepBar.tsx
Labels: approved, dco-signoff: no, lgtm

#702 Update Discovery Doc Links
  frontend/public/locales/en/credentials.json
  frontend/src/lib/doc-util.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#707 Add IBM Power/Z to provider list, fix broken credential mapping in create cluster pools
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#708 Fix addon launch out links
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/get-addons.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#709 Remove card from Machine pool page
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
Labels: approved, dco-signoff: yes, lgtm

#706 Validation enhancement
  frontend/public/locales/en/credentials.json
  frontend/src/lib/validation.test.ts
  frontend/src/lib/validation.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#710 Point create cluster pool to create cluster's install config template
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/install-config.hbs
Labels: approved, dco-signoff: yes, lgtm

#712 Fix string reference for Cluster set view role
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
Labels: approved, dco-signoff: yes, lgtm

#713 Fix incorrect progressing status for submariner summary status
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/MultiClusterNetworkStatus.tsx
Labels: approved, dco-signoff: yes, lgtm

#714 string changes
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/create.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: approved, dco-signoff: yes, lgtm

#715 use latest temptifly
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#716 Add image/jpeg content type
  backend/src/routes/serve.ts
Labels: approved, dco-signoff: yes, lgtm

#717 yaml to form
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
Labels: approved, dco-signoff: yes, lgtm

#719 Align secondary BMA button with clusters page
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPage.tsx
Labels: approved, dco-signoff: yes, lgtm

#721 fix combo
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#722 add unit test case for AWS create cluster
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
Labels: approved, dco-signoff: yes, lgtm

#720 Feature gated template
  featuregate.yaml
  features/automation.yaml
  frontend/src/FeatureGates.ts
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#726 String changes to align with product
  frontend/public/locales/en/cluster.json
  frontend/public/locales/en/create.json
Labels: approved, dco-signoff: yes, lgtm

#723 use specific values for bulkactionmodel icon
  frontend/public/locales/en/cluster.json
  frontend/src/components/BulkActionModel.tsx
  frontend/src/routes/Credentials/Credentials.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/ClusterSetActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
Labels: approved, dco-signoff: yes, lgtm

#725 Job template help text
  frontend/public/locales/en/cluster.json
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#727 tab and filter bug
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
Labels: approved, dco-signoff: yes, lgtm

#728 Doc integration updates
  frontend/public/locales/en/cluster.json
  frontend/src/lib/doc-util.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#730 wizard bug
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#724 Disable sno baremetal
  README.md
  features/single-node-openshift.yaml
  frontend/package-lock.json
  frontend/public/locales/en/create.json
  frontend/src/FeatureGates.ts
  frontend/src/components/TechPreviewAlert.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
Labels: approved, dco-signoff: yes, lgtm

#729 fix for status popover ansible link
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusField.tsx
Labels: approved, dco-signoff: yes, lgtm

#731 add plural for channel select & cluster upgrade
  frontend/public/locales/en/cluster.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/BatchChannelSelectModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/BatchUpgradeModal.tsx
Labels: approved, dco-signoff: yes, lgtm

#732 update dependencies
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
  scripts/update-dependencies.sh
Labels: approved, dco-signoff: yes, lgtm

#735 Bma bugs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/bare-metal-asset.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: approved, dco-signoff: yes, lgtm

#738 delete cluster if creation fails
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/create-cluster.ts
Labels: approved, dco-signoff: yes, lgtm

#743 change help URL links for 2.3
  frontend/src/lib/doc-util.ts
Labels: approved, dco-signoff: yes, lgtm

#744 lastest temptifly
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#745 separate help links for each credential type
  frontend/src/lib/doc-util.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#746 Fix SNO with cluster pools
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
Labels: approved, dco-signoff: yes, lgtm

#741 fix access check
  backend/src/routes/events.ts
Labels: approved, dco-signoff: yes, lgtm

#747 Update to ui-components@0.178.0
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
Labels: approved, dco-signoff: yes, lgtm

#734 Enforce unique job names in template creation
  frontend/public/locales/en/cluster.json
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
Labels: approved, dco-signoff: yes, lgtm

#739 Remove 4.5 from discovery OCP version list
  frontend/src/components/discoveryVersions.json
Labels: approved, dco-signoff: yes, lgtm

#740 bma-status-fix-2.2
  frontend/public/locales/en/bma.json
  frontend/src/resources/bare-metal-asset.ts
  frontend/src/routes/BareMetalAssets/BareMetalAsset.test.tsx
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
Labels: approved, dco-signoff: yes, lgtm

#733 Adoption of bma status from backend (foundation)
  frontend/public/locales/en/bma.json
  frontend/src/resources/bare-metal-asset.ts
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAsset.test.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPage.tsx
Labels: approved, dco-signoff: yes, lgtm

#752 ui-components 0.179.0
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes, lgtm

#751 Combo bug4
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: approved, dco-signoff: yes, lgtm

#750 Ansible status fix
  frontend/public/locales/en/cluster.json
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ProgressStepBar.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/useAllClusters.tsx
Labels: approved, dco-signoff: yes, lgtm

#754 fix (ansible job link needs absolute url path)
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusField.tsx
Labels: approved, dco-signoff: yes, lgtm

#755 adding absolute path to distribution path
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.tsx
Labels: approved, dco-signoff: yes, lgtm

#756 Ansible status bug fix
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.tsx
Labels: approved, dco-signoff: yes, lgtm
