Repository stolostron/console, pull requests merged in 2022-02, with the labels that each got.

#1145 Cluster Set fix
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
Labels: lgtm, approved, dco-signoff: yes

#1142 2.4.x fix for console cache not getting updates
  backend/package-lock.json
  backend/package.json
  backend/src/lib/respond.ts
  backend/src/lib/token.ts
  backend/src/resources/resource.ts
  backend/src/routes/events.ts
  backend/src/routes/oauth.ts
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#1148 Pre commit configuration
  .husky/pre-commit
  frontend/i18next-parser.config.js
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/WrappedImportBareMetalAssetsButton.js
  scripts/copyright-check.ts
  scripts/copyright-fix.ts
Labels: lgtm, approved, dco-signoff: yes

#1147 Optimize policyset summary calculation & include preset url filter ca…
  frontend/src/components/StatusIcons.tsx
  frontend/src/resources/policy-set.ts
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarFilter.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarSearch.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Governance/policy-sets/usePolicySetSummary.tsx
Labels: lgtm, approved, dco-signoff: yes

#1152 2.3 console fix for watched resources
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1149 governance overview and wizards
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/NavigationPath.ts
  frontend/src/components/StatusIcons.tsx
  frontend/src/components/StatusLabeledIcons.tsx
  frontend/src/resources/utils/resource-request.ts
  frontend/src/routes/Governance/Governance.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/PolicyWizardPage.tsx
  frontend/src/routes/Governance/policy-sets/PolicySetWizardPage.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/usePolicySetSummary.tsx
  frontend/webpack.config.ts
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes

#1155 Add BundleAnalyzerPlugin to frontend
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.ts
Labels: lgtm, approved, dco-signoff: yes

#1150 Fix null result error in policy set sidebar component
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1157 governance overview summary cards
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Governance/overview/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1156 Initial Policy table column rework
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Governance/GovernancePage.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/util.tsx
  frontend/src/routes/Governance/useGovernanceData.tsx
Labels: lgtm, approved, dco-signoff: yes

#1159 minor policyset card tweaks
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1160 Include correct translations for ClusterPolicySidebar
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterPolicySidebar.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterPolicySidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1158 cleanup console backend logging
  backend/config/LOG_LEVEL
  backend/src/lib/main.ts
  backend/src/lib/server-side-events.ts
  backend/src/lib/server.ts
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1162 Add doc link to type column tooltip
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Applications/ApplicationsPage.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1164 2.4 fix console addons display
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1163 2.3 fix console addons display
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1165 refactor empty state message and view docs function
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
  frontend/src/routes/Governance/overview/Overview.test.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1166 Fix capitalization for Proxy wizard
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1108 App Wizard Adoption
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/channel.ts
  frontend/src/routes/Applications/CreateApplication/CreateApplication.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: no

#1167 governance overview
  backend/src/routes/events.ts
  frontend/src/NavigationPath.ts
  frontend/src/components/AcmMasonry.tsx
  frontend/src/components/StatusIcons.tsx
  frontend/src/resources/policy-set.ts
  frontend/src/resources/policy.ts
  frontend/src/routes/Governance/GovernancePage.tsx
  frontend/src/routes/Governance/clusters/GovernanceClustersPage.tsx
  frontend/src/routes/Governance/clusters/useClusterPolicyViolationsColumn.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/overview/ClusterViolationSummary.tsx
  frontend/src/routes/Governance/overview/Overview.test.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/overview/PolicySetViolationSummary.tsx
  frontend/src/routes/Governance/overview/PolicyViolationSummary.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/usePolicySetSummary.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1169 Fix regression
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
Labels: lgtm, approved, dco-signoff: yes

#1173 policy-set editing support
  backend/src/routes/events.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/NavigationPath.ts
  frontend/src/resources/utils/resource-request.ts
  frontend/src/routes/Governance/Governance.tsx
  frontend/src/routes/Governance/clusters/useClusterPolicyViolationsColumn.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  resources/policies/cluster-set.yaml
  resources/policies/policy-set-with-1-placement-rule.yaml
  resources/policies/policy-set-with-1-placement.yaml
  resources/policies/policy-set-with-2-placement-rules.yaml
  resources/policies/policy-set-with-2-placements.yaml
  resources/policies/policy-with-1-placement-rule.yaml
  resources/policies/policy-with-2-placement-rules.yaml
Labels: lgtm, approved, dco-signoff: yes

#1154 Fix cluser create wizard providers
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlData.js
Labels: lgtm, approved, dco-signoff: yes

#1161 Move infra env form buttons to the bottom
  frontend/src/routes/Infrastructure/InfraEnvironments/CreateInfraEnv.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvForm.css
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1171 Fix count discrepancies in policyset details view
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Governance/policy-sets/usePolicySetSummary.tsx
Labels: lgtm, approved, dco-signoff: yes

#1177 Initial Policy details page work
  backend/src/routes/events.ts
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/NavigationPath.ts
  frontend/src/atoms.tsx
  frontend/src/resources/helmrelease.ts
  frontend/src/resources/index.ts
  frontend/src/resources/metadata.ts
  frontend/src/routes/Governance/Governance.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policies/util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1180 Updating RbacDropdown to only show tooltip if also disabled
  frontend/src/components/Rbac.tsx
Labels: lgtm, approved, dco-signoff: yes

#1181 Fix request url length issue for resources that have long names & kinds
  backend/src/app.ts
Labels: lgtm, approved, dco-signoff: yes

#1182 Always sort the PolicySet cards alphabetically
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1183 Initial Policy results page (no links to history or template details …
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/resources/index.ts
  frontend/src/resources/placement-rule.ts
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1188 Use common policy violation column for PolicySet sidebar table
  frontend/src/routes/Governance/clusters/useClusterPolicyViolationsColumn.tsx
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsPage.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1189 update rowActions with resolver and tooltip logic
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1190 Add optional href for status icon counts
  frontend/src/components/StatusIcons.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
Labels: lgtm, approved, dco-signoff: yes

#1187 update policy set wizard
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Applications/CreateApplication/CreateApplication.tsx
  frontend/src/routes/Governance/policies/PolicyWizardPage.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1191 Fix Placement expressions in details view for policies assigned to po…
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1192 Add overview for subscription apps
  frontend/src/components/Topology/Topology.js
  frontend/src/components/Topology/components/ResourceFilterBar.js
  frontend/src/components/Topology/components/ResourceFilterView.js
  frontend/src/components/Topology/components/SearchName.js
  frontend/src/components/Topology/components/Zoom.js
  frontend/src/components/Topology/constants.js
  frontend/src/components/Topology/helpers/filterHelper.js
  frontend/src/components/Topology/helpers/layoutHelper.js
  frontend/src/components/Topology/helpers/linkHelper.js
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/components/Topology/helpers/titleHelper.js
  frontend/src/components/Topology/helpers/zoomHelper.js
  frontend/src/components/Topology/shapes/constants.js
  frontend/src/resources/subscription.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/actions/index.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ArgoAppDetailsContainer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ChannelControl.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ClusterDetailsContainer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsView.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DiagramViewer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LegendView.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/ansible-task.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-argo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/resource-helper.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/search-helper.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/descriptions.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/filtering.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/index.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/layouts.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/status.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/titles.js
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/components/LabelWithPopover.tsx
  frontend/src/routes/Applications/components/TimeWindowLabels.tsx
  frontend/src/routes/Applications/css/ApplicationOverview.css
  frontend/src/routes/Applications/css/TimeWindowLabels.css
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1193 add delete confirm modal for policy set
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1179 19223standalone header
  backend/src/app.ts
  backend/src/routes/configure.ts
  backend/src/routes/consoleLinks.ts
  backend/src/routes/username.ts
  frontend/src/App.tsx
  frontend/src/assets/ACM-icon.svg
  frontend/src/assets/RHACM-Logo.svg
  frontend/src/lib/applinks.ts
  frontend/src/lib/configure.ts
  frontend/src/lib/test-metadata.ts
  frontend/src/lib/username.ts
  frontend/src/resources/multi-cluster-hub.ts
  frontend/webpack.config.ts
Labels: lgtm, approved, dco-signoff: yes

#1196 Update ui-components and change isDisabled prop for DropdownItems in console to isAriaDisabled
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Rbac.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/ClusterSetActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/AddCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DownloadConfigurationDropdown.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1197 Update ManagedClusterAction & ManagedClusterView functions
  frontend/src/resources/managedclusteraction.tsx
  frontend/src/resources/managedclusterview.tsx
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Search/Details/DetailsPage.test.tsx
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
  frontend/src/routes/Home/Search/Details/LogsPage.test.tsx
  frontend/src/routes/Home/Search/Details/LogsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1199 add hover styles to violations cards
  frontend/src/routes/Governance/overview/PolicyViolationSummary.tsx
Labels: lgtm, approved, dco-signoff: yes

#1201 Scrub use of word compliance
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/resources/metadata.ts
  frontend/src/resources/policy.ts
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarFilter.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/Home/Search/searchDefinitions.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#1203 Fix case issue in logs page
  backend/src/app.ts
  frontend/src/resources/managedclusteraction.tsx
  frontend/src/resources/managedclusterview.tsx
  frontend/src/resources/utils/resource-request.ts
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
  frontend/src/routes/Home/Search/Details/LogsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1206 reset props on submit
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1200 Some minor logging tweaks
  backend/package-lock.json
  backend/package.json
  backend/src/lib/logger.ts
  backend/src/lib/server.ts
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1217 [Updated with mce] Add Policy detail template history page
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/routes/Governance/Governance.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistoryPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#1218 Substitute credential name
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#1219 Fix undefined container error for search details page
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1221 Add test for Policy table links
  frontend/src/resources/policy-set.ts
  frontend/src/resources/policy.ts
  frontend/src/routes/Governance/policies/Policies.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1225 Update to version 2.5.0
  COMPONENT_VERSION
  frontend/src/App.tsx
  frontend/src/lib/doc-util.ts
Labels: lgtm, approved, dco-signoff: yes

#1224 Fix issue with getting secrets in search results
  frontend/src/resources/managedclusteraction.tsx
  frontend/src/resources/managedclusterview.tsx
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1226 Use SPA navigation to search
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
Labels: lgtm, approved, dco-signoff: yes

#1176 Bump ai-ui-lib to v2.1.0
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/AIHostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/NetworkForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/DetailsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvForm.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/utils.ts
Labels: lgtm, approved, dco-signoff: yes

#1204 Create Application route update, button changes
  frontend/src/NavigationPath.ts
  frontend/src/resources/channel.ts
  frontend/src/routes/Applications/Applications.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1227 Add Template details page & move YAMLEditor to common component
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/components/YAMLEditor.css
  frontend/src/components/YamlEditor.tsx
  frontend/src/resources/index.ts
  frontend/src/resources/managedclusteraction.tsx
  frontend/src/resources/managedclusterview.tsx
  frontend/src/resources/utils/utils.ts
  frontend/src/routes/Governance/Governance.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistoryPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetailsPage.tsx
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1230 Policy Detail pages testing & yaml editor rework
  frontend/src/components/YAMLEditor.css
  frontend/src/components/YamlEditor.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistory.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistory.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistoryPage.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistoryPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetailsPage.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetailsPage.tsx
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1233 Update sonar coverage dir
  .dockerignore
  frontend/.gitignore
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#1235 set explicit package versions
  backend/package-lock.json
  backend/package.json
  backend/src/lib/logger.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/utils/utils.ts
  package.json
Labels: approved, dco-signoff: yes

#1238 Handle policyset card click
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1234 Fix bugs
  frontend/src/resources/utils/utils.ts
  frontend/src/routes/Applications/CreateApplication/Subscription/SubscriptionApplication.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/CreateApplication/Subscription/style.css
Labels: lgtm, approved, dco-signoff: yes

#1240 delete policy modal
  frontend/public/locales/en/translation.json
  frontend/src/lib/delete-policy.ts
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1239 Address Sonar bugs
  frontend/src/App.tsx
  frontend/src/components/Topology/helpers/layoutHelper.js
  frontend/src/components/Topology/helpers/utilities.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
Labels: lgtm, approved, dco-signoff: yes

#1241 update react form wizard package
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1194 npm update follow-redirects
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#1243 add source column for policy table
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1246 update react form wizard package
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1245 sonar smells
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
Labels: lgtm, approved, dco-signoff: yes

#1250 Add undefined check for window.location.search filter check
  frontend/src/routes/Applications/helpers/resource-helper.test.ts
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1249 add realistic placement examples
  resources/policy-set-with-placement-aws-gcp.yaml
  resources/policy-set-with-placement-rules-aws-gcp.yaml
Labels: lgtm, approved, dco-signoff: yes

#1251 Use patternfly log viewer component in search logs
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Search/Details/LogsPage.test.tsx
  frontend/src/routes/Home/Search/Details/LogsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1252 Argo creation
  frontend/src/resources/channel.ts
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
Labels: lgtm, approved, dco-signoff: yes

#1248 handle watch errors
  backend/package.json
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1258 calculate policy set cluster compliance
  frontend/src/lib/delete-policy.ts
  frontend/src/resources/metadata.ts
  frontend/src/resources/placement-decision.ts
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1257 Add log and YAML tabs to topology sidebar
  frontend/public/locales/en/translation.json
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/Topology/Topology.d.ts
  frontend/src/routes/Applications/ApplicationDetails/AcmDrawer.tsx
  frontend/src/routes/Applications/ApplicationDetails/AcmPage.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsView.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DiagramViewer.css
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DiagramViewer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.css
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1262 update placement apiVersion
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1261 Update react-form-wizard package
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1242 add rbac
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/resources/namespace.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Applications/Applications.tsx
  frontend/src/routes/Applications/CreateApplication/ArgoApplicationSet/ArgoApplicationSet.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/SubscriptionApplication.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlData.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/CreateApplication/Subscription/transformers/transform-data-to-resources.js
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/SubscriptionApplication.test.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
  frontend/src/routes/Applications/helpers/resource-helper.test.ts
Labels: lgtm, approved, dco-signoff: yes
