Repository stolostron/console, pull requests merged in 2022-08, with the labels that each got.

#1934 wipes out any YAML changes install-config in Create Cluster flow#18661
  frontend/src/components/SyncEditor/changes.ts
  frontend/src/components/SyncEditor/process.ts
  frontend/src/components/SyncEditor/reconcile.ts
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/components/TemplateEditor/utils/refresh-source-from-stack.js
  frontend/src/components/TemplateEditor/utils/refresh-source-from-templates.js
  frontend/src/components/TemplateEditor/utils/source-utils.js
  frontend/src/routes/Applications/SubscriptionApplication.tsx
  frontend/src/routes/Applications/style.css
Labels: lgtm, approved, dco-signoff: yes

#1936 Fix dark theme styling for search page breadcrumb
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
  frontend/src/routes/Home/Search/SearchResults/utils.tsx
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/Home/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#1937 Include new pod statuses in overview search queries
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1939 [2.5] Include new pod statuses in overview search queries
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1941 Fix two issues
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1942 editor dark background
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/TemplateEditor/components/YamlEditor.js
  frontend/src/components/TemplateEditor/css/control-panel.css
Labels: lgtm, approved, dco-signoff: yes

#1944 Bulk automation modal tests
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1940 Update complianceType for limit range policy
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1935 add 4.11 and remove 4.7 from discovery ocp versions
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryComponents/test-utils.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#1946 Update react-data-view to fix crash in MCE
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1945 fix mock data domains and ip addresses for infosec
  frontend/src/ui-components/AcmTable/AcmTable.stories.tsx
  frontend/src/ui-components/AcmTable/AcmTable.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1948 back out placement policy change
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/style.css
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
Labels: lgtm, approved, dco-signoff: yes

#1949 Updating implemented linkout icons
  frontend/src/components/AcmDataForm.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPrePostTasks.js
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1953 Fix searchbar styling issues in plugin
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/components/Modals/SaveAndEditSearchModal.tsx
  frontend/src/ui-components/AcmSearchbar/AcmSearchbar.css
  frontend/src/ui-components/AcmSearchbar/AcmSearchbar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1950 Doc string updates
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateSummaryModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1951 Add infrastructure and control plane data to review step
  frontend/src/components/TemplateEditor/controls/ControlPanelFinish.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAI.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHypershift.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHypershift.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.test.js
Labels: lgtm, approved, dco-signoff: yes

#1959 Fix search page bugs
  frontend/src/routes/Home/Search/SearchResults/RelatedResultsTiles.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.test.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.tsx
  frontend/src/routes/Home/Search/components/SearchResults.tsx
  frontend/src/ui-components/AcmSearchbar/AcmSearchbar.tsx
  frontend/src/ui-components/AcmTile/AcmTile.test.tsx
  frontend/src/ui-components/AcmTile/AcmTile.tsx
Labels: lgtm, approved, dco-signoff: yes

#1956 Automation preview/edit opens new tab
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateSummaryModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1958 Fix path
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
Labels: lgtm, approved, dco-signoff: yes

#1963 2.5-fix-branch
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
Labels: lgtm, approved, dco-signoff: yes

#1960 Doc-changes (2.6)
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateSummaryModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1957 Conditionally display template details link
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#1954 update wizard pkg and submit button for importcluster flow
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1967 Fix topology status issue
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.js
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1969 Disable bulk actions for unauthorized users
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1970 Fix Overview page loading state
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  frontend/src/ui-components/AcmCountCard/AcmCountCard.tsx
  frontend/src/ui-components/AcmProvider/AcmProviderCard/AcmProviderCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1973 Cherry pick 2.6 changes
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
Labels: lgtm, approved, dco-signoff: yes

#1972 Fix background color
  frontend/public/locales/en/translation.json
  frontend/src/components/Topology/css/topology-diagram.css
Labels: lgtm, approved, dco-signoff: yes

#1975 Fix multi sub app topo not displaying properly and disable AWS hypershift cluster detach/destroy
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
Labels: lgtm, approved, dco-signoff: yes

#1976 Fix multi sub app topo not displaying properly and disable AWS hypershift cluster detach/destroy for 2.6
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
Labels: lgtm, approved, dco-signoff: yes

#1929 Bug 2112289: Use oc command when importing hypershift cluster
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftImportCommand.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.tsx
Labels: lgtm, approved, dco-signoff: yes

#1964 Import wiz 2.6
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1978 Set subrow key to avoid crash
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#1980 Fix catalog crash when opening tooltip
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
Labels: lgtm, approved, dco-signoff: yes

#1966 Fix retrieving the policy template details in hosted mode
  frontend/src/resources/managed-cluster-add-on.ts
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetailsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1986 [release-2.6] Cherry-pick #1978 (Set subrow key)
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#1979 Add an or operator for isHypershift
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1947 Add action to set installation disk to AI cluster wizard
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1988 Cherry-pick-again
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1982 BZ 2110308: Pass nodepools to hosts step to check the name uniqness
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1981 Align credentials page choices with create cluster
  frontend/src/lib/validation.test.ts
  frontend/src/lib/validation.ts
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Credentials/schema.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAI.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHypershift.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterDestroy.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusField.tsx
  frontend/src/ui-components/AcmIcons/AcmIcons.tsx
  frontend/src/ui-components/AcmIcons/HybridIcon.tsx
  frontend/src/ui-components/AcmIcons/HypershiftIcon.tsx
  frontend/src/ui-components/AcmProvider/index.ts
Labels: lgtm, approved, dco-signoff: yes

#1962 BZ 2113886: Handle OCP console link when running as dynamic plugin
  frontend/src/lib/ocp-utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/AIHypershiftClusterDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1983 BZ 2117163 Prefill form values based on credentials selection
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#1968 Add troubleshooting information to hosts tab in infra env page
  backend/src/routes/events.ts
  frontend/src/atoms.tsx
  frontend/src/resources/index.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1991 Update no infraenv alert texts
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/Warning.tsx
Labels: lgtm, approved, dco-signoff: yes

#1990 change violation filters to cluster level
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1992 Fix sonar scan for searchbar issue
  frontend/src/ui-components/AcmSearchbar/AcmSearchbar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1985 Fix mode for policy automation details
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1974 Fix backend label reconciliation on watches
  backend/src/resources/resource.ts
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1995 Address Sonar bugs
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/components/TemplateEditor/utils/YamlParser.js
Labels: lgtm, approved, dco-signoff: yes

#1994 Use Card/CardBody for dark theme colors
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/css/ApplicationOverview.css
Labels: lgtm, approved, dco-signoff: yes

#1993 add check for ibm provider and that cloud label is set
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1996 Fix the related objects view YAML link in hosted mode
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1998 Update versions for ACM 2.7 / MCE 2.2
  COMPONENT_VERSION
  frontend/plugins/acm/console-plugin.json
  frontend/plugins/mce/console-plugin.json
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1999 String alteration
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#2000 Filter out HostedClusters in useClusters
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#2001 Cherry pick 2.6 Filter out HostedClusters in useClusters
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#2005 String-alteration-2.6
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#2002 Make value no longer required
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
Labels: lgtm, approved, dco-signoff: yes

#2004 Allow empty value for cluster selector label (#1870)
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
Labels: lgtm, approved, dco-signoff: yes

#2006 Add keys for routes
  frontend/src/App.tsx
Labels: lgtm, approved, dco-signoff: yes

#2009 add hint to import cluster flow when aap is not installed
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#2007 Cherry pick 2.6 Fix text and make cluster lists consistent
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
Labels: lgtm, approved, dco-signoff: yes

#2012 Cherry pick - add hint to import cluster flow when aap is not installed
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1997 Import wizard - Automation helper text update
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#2014 Import wizard helper text additions (2.6 branch)
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#2011 Add limit to user saved searches for performance
  frontend/public/locales/en/translation.json
  frontend/src/atoms.tsx
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.test.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.tsx
Labels: lgtm, approved, dco-signoff: yes

#2020 Update react-form-wizard to version 1.8.6
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#2021 [release-2.6] Update react-form-wizard to 1.8.6
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#2013 restore the fix for 24928
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#2025 [release-2.6] restore the fix for 24928
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#2027 Fix secret creation for Automation update
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#2028 [release-2.6] Fix secret creation for Automation update
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#2022 Fix default value for control data
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#2019 Add hint to create cluster automation step when aap is not installed (release-2.6)
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/components/AutomationProviderHint.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#2018 Add hint to create cluster automation step when aap is not installed
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/components/AutomationProviderHint.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#2029 Fix default value for control data (#2022)
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#2031 Record branches for z-stream maintenance
  README.md
Labels: lgtm, approved, dco-signoff: yes

#2030 speed up tests
  frontend/jest.config.ts
Labels: lgtm, approved, dco-signoff: yes

#2023 Remove plural trimming logic
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetailsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#2026 string updates
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#2033 Doc string changes (main branch)
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#2037 Add Content-Security-Policy header
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#2034 [release-2.4] Add Content-Security-Policy header
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#2035 [release-2.5] Add Content-Security-Policy header
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#2017 Bug 2119334: ACM plugin extension for Application list page column
  frontend/src/plugin-extensions/extensions/ApplicationListPageColumn.ts
  frontend/src/plugin-extensions/extensions/index.ts
  frontend/src/plugin-extensions/handler.ts
  frontend/src/plugin-extensions/properties/addListColumnProps.ts
  frontend/src/plugin-extensions/properties/index.ts
  frontend/src/plugin-extensions/types.ts
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#2042 Add Governance OWNERS file
  frontend/src/routes/Governance/OWNERS
Labels: lgtm, approved, dco-signoff: yes

#2044 string updates
  frontend/public/locales/en/translation.json
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#2043 Allow GitHub for branch/path fetching
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#2045 Allow GitHub for branch/path fetching
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#2052 ignore install-yaml secret
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/components/TemplateEditor/css/control-panel.css
Labels: approved, dco-signoff: yes

#2054 restore new subscription app placement ui
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/style.css
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
Labels: lgtm, approved, dco-signoff: yes

#2050 Add support for d3 in jest
  frontend/jest.config.ts
  frontend/src/lib/nock-util.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#2055 link changes
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#2061 Add auto-retry for npm ci of frontend
  Dockerfile.mce.prow
  Dockerfile.prow
  Makefile.prow
Labels: lgtm, approved, dco-signoff: yes

#2058 Fix credentials copy during cluster create
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#2059 Fix credentials copy cluster create 2.6
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#2046 Fix subscription argo app of apps topology 2.7
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.js
Labels: lgtm, approved, dco-signoff: yes

#2063 Remove dead BMA code.
  frontend/public/locales/en/translation.json
  frontend/src/lib/bare-metal-assets.ts
  frontend/src/lib/create-cluster.ts
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/WrappedImportBareMetalAssetsButton.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/endpoints.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#2067 webpack update, readme update
  frontend/PLUGIN.md
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes

#2015 Fix offline cluster topology
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ClusterDetailsContainer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
Labels: lgtm, approved, dco-signoff: yes

#2065 Change title to networking
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHypershift.js
Labels: lgtm, approved, dco-signoff: yes
