Repository stolostron/console, pull requests merged in 2022-04, with the labels that each got.

#1459 update wizards - fixes padding in dynamic plugins
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1468 Update openshift-assisted-ui-lib to v2.3.6-CIM-2.5
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1472 Add unit tests for topology
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ArgoAppDetailsContainer.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ChannelController.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ClusterDetailsContainer.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsView.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LegendView.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/ansible-task.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/resource-helper.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/search-helper.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/application.test.js
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#1473 RBAC check for policy template resources
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1471 Add button for subscriptions
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/AdvancedConfiguration.test.tsx
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/components/ToggleSelector.tsx
Labels: lgtm, approved, dco-signoff: yes

#1478 fix cluster policy sidebar crash
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/overview/ClusterPolicySummarySidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1474 Fix ansible secret
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1481 Synceditor height2
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/SyncEditor/process.ts
  frontend/src/components/Topology/css/topology-details.css
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsView.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/CreateApplication/schema.json
  frontend/src/routes/Credentials/schema.json
  frontend/src/routes/Governance/policies/schema.json
  frontend/src/routes/Governance/policy-sets/schema.json
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/schema.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/schema.json
Labels: lgtm, approved, dco-signoff: yes

#1488 restore tree layout for simple diagrams
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/layouts.js
Labels: lgtm, approved, dco-signoff: yes

#1485 Automation wizard
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicyAutomation.tsx
  frontend/src/routes/Governance/policies/schemaAutomation.json
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
  frontend/src/routes/Infrastructure/Automations/schema.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1479 Update wizard dep to 1.6.45
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1486 Fix path for plugin metadata
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#1487 Fix topology search data not updating
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/relatedResources.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
Labels: lgtm, approved, dco-signoff: yes

#1490 disable add to policy set for view users
  frontend/src/routes/Governance/components/PolicyActionDropdown.tsx
Labels: lgtm, approved, dco-signoff: yes

#1492 Fix searching for sec group policy sidebar
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/overview/SecurityGroupPolicySummarySidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1482 Bug 2071698: Remove AWS from BM-supported platforms
  frontend/src/routes/Infrastructure/InfraEnvironments/infraenv-template.hbs
  frontend/src/routes/Infrastructure/InfraEnvironments/utils.ts
Labels: lgtm, approved, dco-signoff: yes

#1489 Add validation for infra env ntp sources
  frontend/src/routes/Infrastructure/InfraEnvironments/CreateInfraEnv.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvForm.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/infraenv-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#1496 Fix missing title in PolicySet sidebar panel
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1494 Bug 2070922 - [UI] new infra env view -> next steps: text enhancement
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvForm.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1483 Fix 15413
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1497 Remove Technology Preview banner for plugins
  frontend/public/locales/en/translation.json
  frontend/src/components/PluginContextProvider.tsx
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1495 Bug 2059595: In new cluster wizard > Review and save the OpenShift Version is not correct shown
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
Labels: lgtm, approved, dco-signoff: yes, needs-ok-to-test

#1499 perspective switcher styling
  frontend/src/App.tsx
Labels: lgtm, approved, dco-signoff: yes

#1502 disable view details link for view-user in policy results tab
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#1504 Filter out ManagedCluster namespaces in Policy create & edit wizard
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
Labels: lgtm, approved, dco-signoff: yes

#1503 major edits
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/SyncEditor/process.ts
  frontend/src/components/SyncEditor/validation.ts
Labels: lgtm, approved, dco-signoff: yes

#1505 New react-wizard version
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1477 Bug 2064387: Improve the deletion action on infraenvs
  frontend/public/locales/en/translation.json
  frontend/src/components/BulkActionModel.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1498 Update openshift-assisted-ui-lib to v2.3.7-CIM-2.5
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1493 performance
  frontend/src/components/Topology/shapes/DiagramIcons.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DiagramViewer.js
Labels: lgtm, approved, dco-signoff: yes

#1506 Add error msgs for AppSet error states
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ArgoAppDetailsContainer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyArgo.js
Labels: lgtm, approved, dco-signoff: yes

#1508 No app error 2
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1507 Fix policyAutomation run once mode job creation
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policies/EditPolicyAutomation.tsx
Labels: lgtm, approved, dco-signoff: yes

#1510 cookies
  backend/src/lib/cookies.ts
Labels: lgtm, approved, dco-signoff: yes

#1512 Kube admin logout support
  Dockerfile.prow
  backend/src/lib/cookies.ts
  backend/src/routes/oauth.ts
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/resources/utils/resource-request.ts
  scripts/patch-deployment.sh
Labels: lgtm, approved, dco-signoff: yes

#1511 Minor fix for cluster resource status
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1513 treat disabled status similarly to compliant for donut chart, fixes NaN
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1229 Ensure setting of zones occurs for all workers
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
Labels: lgtm, approved, dco-signoff: yes

#1514 Filter undefined for search param
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1515 Fix channel ns
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
Labels: lgtm, approved, dco-signoff: yes

#1517 Use policy-template remediationAction if top level not set
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/policy.ts
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/components/PolicyActionDropdown.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1518 less filtering and more
  frontend/src/components/SyncEditor/process.ts
  frontend/src/components/Topology/Topology.js
  frontend/src/components/Topology/css/topology-diagram.css
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DiagramViewer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/layouts.js
Labels: lgtm, approved, dco-signoff: yes

#1524 add webpack rule for svg url paths
  frontend/src/App.tsx
  frontend/src/typings.d.ts
  frontend/webpack.config.ts
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes

#1526 perspective switcher minheight to match ocp
  frontend/src/App.tsx
Labels: lgtm, approved, dco-signoff: yes

#1525 application filters use constants and ignore version
  frontend/public/locales/en/translation.json
  frontend/src/resources/resource.ts
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1527 update packages
  frontend/package-lock.json
  frontend/package.json
Labels: approved, dco-signoff: yes

#1529 Update wizards
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1531 Update minimist to 1.2.6
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#1532 Fix blank page error in gov overview cluster sidebar
  frontend/src/resources/policy.ts
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/overview/ClusterPolicySummarySidebar.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1533 Fix channel duplicate issue
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1534 Add contexts missing for plugin
  frontend/src/components/PluginContextProvider.tsx
Labels: lgtm, approved, dco-signoff: yes

#1538 Fix various error cases
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
Labels: lgtm, approved, dco-signoff: yes

#1540 Update react-form-wizard version
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1541 Let ManagedCluster cloud label take precedence over cluster claim
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1543 Bug 2074937: Disable create cluster button when there are no ClusterImageSets
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1544 Update assisted-ui-lib to v2.3.8-CIM-2.5
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1545 Update no cluster images tooltip msg
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#1542 Fix rbac issue
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlData.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
Labels: lgtm, approved, dco-signoff: yes

#1523 fix statuses
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.test.js
Labels: lgtm, approved, dco-signoff: yes

#1548 PolicyAutomation rbac check in policy details page
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1549 Wizard version update
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1553 Fix use projects
  frontend/src/lib/rbac-util.ts
  frontend/src/routes/Applications/AdvancedConfiguration.test.tsx
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/components/ToggleSelector.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1550 Temptifly version update
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1554 Update clusterpool template with cloudName field (2.5)
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#1559 fix console plugin nav label for automation page
  frontend/plugins/mce/console-extensions.json
Labels: lgtm, approved, dco-signoff: yes

#1560 Update wizard dep for PolicyAutomation change
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/policies/schemaAutomation.json
Labels: lgtm, approved, dco-signoff: yes

#1552 sync synceditor with form
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/SyncEditor/changes.ts
  frontend/src/components/SyncEditor/decorate.ts
  frontend/src/components/SyncEditor/process.ts
  frontend/src/components/SyncEditor/reconcile.ts
  frontend/src/components/SyncEditor/synchronize.ts
  frontend/src/components/SyncEditor/validation.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Credentials/schema.json
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/schema.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1561 add placement validation
  frontend/src/routes/Governance/policies/schema.json
  frontend/src/routes/Governance/policy-sets/schema.json
Labels: lgtm, approved, dco-signoff: yes

#1562 Fix policyset details displa[Dy for disabled policies
  frontend/src/routes/Governance/common/util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1564 Add two missing translation strings for creation.missing.clusterSelec…
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#1565 update form wizard, increaes url limit for requests, fix table breakpoint
  backend/src/app.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1563 fix layout
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
Labels: lgtm, approved, dco-signoff: yes

#1568 Fix PolicyAutomation RBAC
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1535 Doc string edits
  frontend/public/locales/en/translation.json
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
Labels: lgtm, approved, dco-signoff: yes

#1571 When loading state is false, stop re-attempting fetch
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
Labels: lgtm, approved, dco-signoff: yes

#1574 fix edit policy bug
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1558 [2.4] Fix 15413 (#1483)
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1576 Remove the use of useProjects in ApplicationOverview
  frontend/src/resources/namespace.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.test.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1578 Allow cluster creation with no ClusterImageSets
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1573 update moment, nconf via temptifly
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1577 Fix Argo app table cluster status
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/application.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyArgo.js
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1575 performance fix batch event handling
  frontend/src/atoms.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
Labels: lgtm, approved, dco-signoff: yes

#1579 Fix missing policy in policyset sidebar
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1580 misc fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1582 add substr limit when pol-automation is created, update wizard pkg
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
Labels: lgtm, approved, dco-signoff: yes

#1581 Add the window.getEditorValue method
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/globals.d.ts
Labels: lgtm, approved, dco-signoff: yes

#1584 Add details of resource for conflicts
  frontend/public/locales/en/translation.json
  frontend/src/components/BulkActionModel.tsx
  frontend/src/components/ErrorPage.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/EditSubmarinerConfigModal.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/EditLabels.tsx
Labels: lgtm, approved, dco-signoff: yes

#1583 Fix node status and Argo editor link
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.data.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
Labels: lgtm, approved, dco-signoff: yes

#1585 Fix styling issues
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/index.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/style.css
Labels: lgtm, approved, dco-signoff: yes

#1588 Fix re-query issue and some style in-alignments
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/css/ApplicationOverview.css
  frontend/src/routes/Applications/css/TimeWindowLabels.css
Labels: lgtm, approved, dco-signoff: yes

#1589 disable empty state buttons for view users
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1587 Provide node link only if search available
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
Labels: lgtm, approved, dco-signoff: yes

#1590 Update policy automation wizard
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policies/EditPolicyAutomation.tsx
Labels: lgtm, approved, dco-signoff: yes

#1593 fix loading data flicker
  frontend/src/atoms.tsx
Labels: lgtm, approved, dco-signoff: yes

#1570 Need to enforce https for Ansible credentials
  frontend/public/locales/en/translation.json
  frontend/src/lib/validation.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1586 Bug 2074854: Fix redirect to CIM edit flow
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1591 Fix more plugin translations
  frontend/i18next-parser.config.js
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/index.js
Labels: lgtm, approved, dco-signoff: yes

#1596 Serve TTF fonts
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#1597 fix modal icon and button styling for policy deletion
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1598 update wizards and ui-components
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1599 Fix more missing translations
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/components/ToggleSelector.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
Labels: lgtm, approved, dco-signoff: yes

#1600 Add correct help for base domain for baremetal providers
  frontend/public/locales/en/translation.json
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1602 App topology drilldown
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsTable.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.test.js
Labels: lgtm, approved, dco-signoff: yes

#1603 Include PolicySet statusMessage in card
  frontend/src/resources/policy-set.ts
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1605 update wizard to fix policy placement
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1601 application performance
  frontend/src/atoms.tsx
  frontend/src/routes/Applications/ApplicationsPage.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1594 Bug 2071750: Fix nmstate labeling
  backend/src/routes/events.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atoms.tsx
  frontend/src/resources/index.ts
  frontend/src/resources/nmstateconfig.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/infraenv-template.hbs
  frontend/src/routes/Infrastructure/InfraEnvironments/utils.ts
Labels: lgtm, approved, dco-signoff: yes

#1604 Filter credentials for credentials type
  backend/src/routes/events.ts
  frontend/src/routes/Credentials/CredentialsPage.test.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1608 Set agent status for missing broker case
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
Labels: lgtm, approved, dco-signoff: yes

#1614 Add label annotations
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1617 Fallback to searchClusters when SubscriptionReport is not created
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.js
Labels: lgtm, approved, dco-signoff: yes

#1613 Fix loading of edit policy set resources
  frontend/package-lock.json
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1621 fix policy table crash
  frontend/src/routes/Governance/common/util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1622 Add back message
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes
