Repository stolostron/console, pull requests merged in 2022-03, with the labels that each got.

#1264 Handle url search params
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/urlQuery.test.ts
  frontend/src/lib/urlQuery.tsx
Labels: lgtm, approved, dco-signoff: yes

#1260 After creating infraenv redirecto to infraenv details page
  frontend/src/routes/Infrastructure/InfraEnvironments/CreateInfraEnv.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1266 Fix timezone to UTC for moment in tests
  frontend/src/setupTests.ts
Labels: lgtm, approved, dco-signoff: yes

#1271 Fix null error in Template details page
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1270 Add confirm box in infraenv delete modal
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1273 Policy detail overview page placement info
  backend/src/routes/events.ts
  frontend/src/atoms.tsx
  frontend/src/resources/index.ts
  frontend/src/resources/placement-decision.ts
  frontend/src/resources/placement.ts
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1275 remove policy violations from clusters table
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1268 Add other for git malfunction and sharedResource
  frontend/public/locales/en/translation.json
  frontend/src/resources/utils/resource-request.ts
  frontend/src/routes/Applications/CreateApplication/Subscription/components/SharedResourceWarning.js
  frontend/src/routes/Applications/CreateApplication/Subscription/components/style.css
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlData.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1276 remove incorrect image reference for empty state
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1222 Update packages 2.3
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1280 fix frontend test script
  frontend/package.json
  frontend/src/lib/i18n.ts
  frontend/src/resources/channel.ts
  frontend/src/resources/selector.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Applications/CreateApplication/Subscription/components/SharedResourceWarning.js
  frontend/src/routes/Applications/components/DeleteResourceModal.test.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.test.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/CreateBareMetalAsset.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/ClusterSetActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/CreateInfraEnv.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1281 Delete policyset related resources on delete
  frontend/src/lib/delete-policyset.ts
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1223 Update packages 2.4
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
Labels: lgtm, approved, dco-signoff: yes

#1284 Use Gallery instead of AcmMasonry
  frontend/src/routes/Home/Welcome/Welcome.tsx
Labels: lgtm, approved, dco-signoff: yes

#1282 update policy and policy set wizards
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1285 Misc app UI bugs
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/components/DeleteResourceModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1277 Tweak the infra env empty list design
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1289 Argo and appset topology
  frontend/public/locales/en/translation.json
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/application.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.js
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1292 topology performance
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesSubscription.js
Labels: lgtm, approved, dco-signoff: yes

#1294 Globalnet3
  frontend/public/locales/en/translation.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/SyncEditor/changes.ts
  frontend/src/components/SyncEditor/decorate.ts
  frontend/src/components/SyncEditor/process.ts
  frontend/src/resources/broker.ts
  frontend/src/resources/index.ts
  frontend/src/resources/managed-cluster-set.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/schema.json
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1295 Fix group titles
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#1290 Overview work
  frontend/public/locales/en/translation.json
  frontend/src/resources/utils/resource-request.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/components/SyncResourceModal.tsx
  frontend/src/routes/Applications/css/ApplicationOverview.css
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1267 Make portions of MCE UI conditional on ACM
  frontend/plugins/mce/console-plugin.json
  frontend/src/components/PluginContextProvider.tsx
  frontend/src/lib/PluginContext.tsx
  frontend/src/perspective.tsx
  frontend/src/routes/Applications/ApplicationsPlugin.tsx
  frontend/src/routes/Credentials/CredentialsPlugin.tsx
  frontend/src/routes/Governance/GovernancePlugin.tsx
  frontend/src/routes/Home/Overview/OverviewPlugin.tsx
  frontend/src/routes/Home/Search/SearchPlugin.tsx
  frontend/src/routes/Infrastructure/Automations/AutomationsPlugin.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPlugin.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
  frontend/src/routes/Infrastructure/Clusters/ClustersPlugin.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPlugin.tsx
Labels: lgtm, approved, dco-signoff: yes

#1297 Use pluralize instead of just adding 's'
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#1301 update wizards package
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1300 eslint react hooks
  frontend/package-lock.json
  frontend/package.json
  frontend/src/atoms.tsx
  frontend/src/components/PluginContextProvider.tsx
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/YamlEditor.tsx
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/components/SharedResourceWarning.js
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
  frontend/src/routes/Applications/components/DeleteResourceModal.tsx
  frontend/src/routes/Applications/components/ResourceLabels.tsx
  frontend/src/routes/Applications/components/SyncResourceModal.tsx
  frontend/src/routes/Applications/helpers/resource-helper.test.ts
  frontend/src/routes/Applications/helpers/resource-helper.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
  frontend/src/routes/Governance/components/PolicyActionDropdown.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistory.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarSearch.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
  frontend/src/routes/Home/Search/components/Modals/DeleteResourceModal.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetSubmariner/ClusterSetSubmariner.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/unbindHost.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/AIClusterDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1302 Update policyset apiversion to v1beta1
  backend/src/routes/events.ts
  frontend/src/resources/policy-set.ts
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.test.tsx
  resources/policy-set-with-1-placement-rule.yaml
  resources/policy-set-with-1-placement.yaml
  resources/policy-set-with-2-placement-rules.yaml
  resources/policy-set-with-2-placements.yaml
  resources/policy-set-with-placement-aws-gcp.yaml
  resources/policy-set-with-placement-rules-aws-gcp.yaml
Labels: lgtm, approved, dco-signoff: yes

#1304 fix incorrect button text
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
Labels: lgtm, approved, dco-signoff: yes

#1305 Add expandable row to policy table for standards, categories and cont…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1303 Fix empty state text for Application's Advanced configuration table #20262
  frontend/src/routes/Applications/components/ToggleSelector.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1307 Fix inconsistencies in policy details page
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1309 fix tooltip case when user is view- and edit-only
  frontend/src/routes/Governance/components/PolicyActionDropdown.tsx
Labels: lgtm, approved, dco-signoff: yes

#1310 Allow for null metadata.annotations
  frontend/src/routes/Governance/common/util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1312 root policy filter
  frontend/src/atoms.tsx
  frontend/src/routes/Governance/clusters/GovernanceClustersPage.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsPage.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1313 Update policy set to new resource spec
  frontend/public/locales/en/translation.json
  frontend/src/resources/policy-set.ts
  frontend/src/routes/Governance/clusters/useClusterPolicyViolationsColumn.tsx
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarFilter.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Governance/policy-sets/usePolicySetSummary.tsx
  resources/policy-set-with-1-placement.yaml
  resources/policy-set-with-2-placements.yaml
  resources/policy-set-with-placement-aws-gcp.yaml
  resources/policy-with-1-placement.yaml
  resources/policy-with-2-placements.yaml
Labels: lgtm, approved, dco-signoff: yes

#1315 RHV Creation
  frontend/public/locales/en/translation.json
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#1287 Update AI lib to v2.3.1
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/unbindHost.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.sharedmocks.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/utils.ts
Labels: lgtm, approved, dco-signoff: yes

#1317 Open a drawer to display policies on a specific cluster in policy clu…
  frontend/src/components/StatusIcons.tsx
  frontend/src/routes/Governance/clusters/GovernanceClustersPage.tsx
  frontend/src/routes/Governance/clusters/PolicySummarySidebar.test.tsx
  frontend/src/routes/Governance/clusters/PolicySummarySidebar.tsx
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/Home/Search/searchDefinitions.test.ts
  frontend/src/routes/Home/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#1318 Add policy automation create and edit wizards
  backend/src/routes/events.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/atoms.tsx
  frontend/src/resources/index.ts
  frontend/src/resources/policy-automation.ts
  frontend/src/routes/Governance/Governance.tsx
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policies/EditPolicyAutomation.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1316 rbac tooltip fix
  frontend/src/components/Rbac.tsx
Labels: lgtm, approved, dco-signoff: yes

#1274 Updating ClusterPool scale modal
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/components/ScaleClusterPoolModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1320 Redo welcome page
  frontend/src/components/AcmDynamicGrid.tsx
  frontend/src/routes/Home/Welcome/Welcome.tsx
Labels: lgtm, approved, dco-signoff: yes

#1326 Support ansible pre and post hook
  frontend/public/locales/en/translation.json
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/ansible-task.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/application.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
Labels: lgtm, approved, dco-signoff: yes

#1324 Removed bad logic from OCP version check
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#1325 Remove Tech Preview banner for cluster sets
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1322 Remove double translation
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
Labels: lgtm, approved, dco-signoff: yes

#1323 Cluster pool status
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/resources/cluster-deployment.ts
  frontend/src/resources/utils/get-cluster.test.ts
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/ClusterStatuses.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusField.tsx
Labels: lgtm, approved, dco-signoff: yes

#1321 Overview Dropdown
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
  frontend/src/routes/Applications/components/DeleteResourceModal.tsx
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1330 policy-drawer-styles
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterPolicySidebar.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterPolicySidebarIcons.tsx
Labels: lgtm, approved, dco-signoff: yes

#1327 Cluster set cluster pool fixes
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/components/Rbac.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetClusterPools/ClusterSetClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1334 edit argo application set support
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/components/DeleteResourceModal.tsx
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1336 Update react-form-wizards dependency
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/policy-automation.ts
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policies/EditPolicyAutomation.tsx
Labels: lgtm, approved, dco-signoff: yes

#1331 Do not use KlusterletAddonConfig in MCE
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Applications/components/DeleteResourceModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/ai-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/cim-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1319 Cluster pool updates
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/components/ClusterClaimModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1333 Adjust pool availability
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
Labels: lgtm, approved, dco-signoff: yes

#1339 Add tech preview banner for dynamic plugins
  frontend/plugins/acm/console-plugin.json
  frontend/public/locales/en/translation.json
  frontend/src/components/PluginContextProvider.tsx
  frontend/src/lib/doc-util.ts
  frontend/src/routes/Home/Welcome/WelcomePlugin.tsx
Labels: lgtm, approved, dco-signoff: yes

#1344 fix policy edit crash
  frontend/src/atoms.tsx
Labels: lgtm, approved, dco-signoff: yes

#1338 Add unit tests for topology
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/TestingData.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-argo.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.data.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/constants.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/constants.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/descriptions.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/filtering.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/status.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/titles.test.js
Labels: lgtm, approved, dco-signoff: yes

#1341 Submariner doc link root updated
  frontend/src/lib/doc-util.ts
Labels: lgtm, approved, dco-signoff: yes

#1345 Update react-form-wizards
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1342 Add policies policyset
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1347 Fix show secrets issue
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlData.js
  frontend/src/routes/Applications/CreateApplication/Subscription/templates/templateGit.hbs
  frontend/src/routes/Applications/CreateApplication/Subscription/templates/templateHelm.hbs
  frontend/src/routes/Applications/CreateApplication/Subscription/templates/templateObjectStore.hbs
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1350 Policy automation sidebar
  backend/src/routes/events.ts
  frontend/public/locales/en/translation.json
  frontend/src/resources/ansible-job.ts
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policies/EditPolicyAutomation.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistory.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1308 Bug 2060453 : cluster in creating state provides incorrect link to installation logs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterDestroy.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusField.tsx
Labels: lgtm, approved, dco-signoff: yes, needs-ok-to-test

#1349 topology drilldown
  frontend/src/components/Topology/Topology.js
  frontend/src/components/Topology/css/topology-node.css
  frontend/src/components/Topology/helpers/nodeHelper.js
  frontend/src/components/Topology/shapes/DiagramIcons.tsx
  frontend/src/components/Topology/shapes/DiagramShapes.tsx
  frontend/src/components/Topology/shapes/constants.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsTable.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsView.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/TestingData.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.data.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/relatedResources.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/index.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/layouts.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/status.js
Labels: lgtm, approved, dco-signoff: yes

#1353 Display alert if ansible operator is not installed
  backend/src/routes/events.ts
  frontend/public/locales/en/translation.json
  frontend/src/atoms.tsx
  frontend/src/resources/index.ts
  frontend/src/resources/subscription-operator.ts
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1355 reorder policy annotation groups
  frontend/src/routes/Governance/overview/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1348 RHV provider label detection logic added
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1357 Get temptifly fix to avoid redirect in plugin
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1354 update argo application set wizard
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1360 Display disabled policies in the policy set sidebar
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1363 Validation, extra fields for RHV
  frontend/public/locales/en/translation.json
  frontend/src/resources/provider-connection.ts
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#1361 Update AI lib to v2.3.2
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
Labels: lgtm, approved, dco-signoff: yes

#1364 Fix path for argo appsets
  frontend/src/NavigationPath.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/transformers/transform-resources-to-controls.js
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1366 Fix plural translation support
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/details.js
  frontend/src/routes/Applications/components/DeleteResourceModal.test.tsx
  frontend/src/routes/Applications/components/ResourceLabels.test.tsx
  frontend/src/routes/Applications/components/SyncResourceModal.test.tsx
  frontend/src/routes/Applications/helpers/resource-helper.test.ts
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1365 Update policy wizard
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1368 Use hook to get the policies included in a PolicySet
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1351 String fix for AWS hosted zones
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#1362 Fix bare metal install on OCP 4.10
  frontend/src/lib/bare-metal-assets.ts
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#1372 Fix search resource
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/resource-helper.js
  frontend/src/routes/Applications/helpers/resource-helper.test.ts
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1379 Remove governance clusters tab and move cluster table to overview
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/components/AcmMasonry.tsx
  frontend/src/routes/Governance/GovernancePage.tsx
  frontend/src/routes/Governance/clusters/GovernanceClustersPage.tsx
  frontend/src/routes/Governance/clusters/useClusterPolicyViolationsColumn.tsx
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/overview/ClusterPolicySummarySidebar.test.tsx
  frontend/src/routes/Governance/overview/ClusterPolicySummarySidebar.tsx
  frontend/src/routes/Governance/overview/ClusterViolationSummary.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/overview/SecurityGroupPolicySummarySidebar.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1377 Application set and policy fixes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1378 application set delete support
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1380 Feng remoteargo
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ArgoAppDetailsContainer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/application.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1381 Make sure Running status only applies to ClusterPool clusters
  frontend/src/resources/cluster-deployment.ts
  frontend/src/resources/utils/get-cluster.test.ts
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1385 change ext managed resource alert to warning
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1383 Message fixes
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ScaleClusterAlert.tsx
Labels: lgtm, approved, dco-signoff: yes

#1387 fix for pset search bar to handle similarly named psets
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1386 Governance overview card order and match patternfly guidelines
  frontend/src/routes/Governance/overview/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1388 label addition (install-config, klusterAddonConfig)
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/endpoints.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#1376 Empty state refactor
  frontend/public/locales/en/translation.json
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
  frontend/src/routes/Governance/overview/Overview.test.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.test.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/AddCluster.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1382 fix yaml editor crash
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1394 Governance overview card legend items should be links
  frontend/package-lock.json
  frontend/package.json
  frontend/src/lib/urlQuery.tsx
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/overview/PolicySetViolationSummary.tsx
  frontend/src/routes/Governance/overview/PolicyViolationSummary.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarFilter.tsx
Labels: lgtm, approved, dco-signoff: yes

#1396 fix view doc link for recycled button
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1397 Fix resource not found error on policy template details page
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#1398 Add legendView back
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.css
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/ApplicationTopology.tsx
Labels: lgtm, approved, dco-signoff: yes

#1389 Fixing conditional rendering of clusterpool subrows
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
Labels: lgtm, approved, dco-signoff: yes

#1390 Fix app table crashing with RBAC user
  frontend/src/resources/project.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.test.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/application.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/helpers/resource-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1399 Preset the table searchbar in policy details results page
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#1384 fix edit app subscription
  .vscode/launch.json
  frontend/src/components/SyncEditor/SyncEditor.css
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/SyncEditor/process.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsView.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1408 Fix placement typo
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1402 Add unit test coverage for create subscription
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.test.tsx
  frontend/src/routes/Applications/SubscriptionApplication.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1405 Update RHV defaults
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#1406 add filter fields back to policy table
  frontend/src/routes/Applications/helpers/resource-helper.ts
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1412 Subscription private channel
  frontend/src/resources/channel.ts
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/CreateApplication/Subscription/templates/templateGit.hbs
Labels: lgtm, approved, dco-signoff: yes

#1411 add rbac to disable create policy and policy set, and config automati…
  frontend/public/locales/en/translation.json
  frontend/src/components/ErrorPage.tsx
  frontend/src/resources/policy-automation.ts
  frontend/src/resources/policy-set.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1414 Fix create app button disabled for RBAC users
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1401 Globalnet string adjustments
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1418 fix sort for policy history
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistory.tsx
Labels: lgtm, approved, dco-signoff: yes

#1416 Cluster tooltips
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/overview/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1417 fix broken automation links
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1409 Validation fix (support for ecdsa-sha2-nistp521 in console 2.4)
  frontend/src/lib/validation.ts
Labels: lgtm, approved, dco-signoff: yes

#1415 Fix refresh blank issue
  frontend/src/resources/application.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1420 add sorting to policy detail results table
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#1421 Filter policy history correctly
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistory.tsx
Labels: lgtm, approved, dco-signoff: yes

#1419 Avoid calling search when not available
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#1413 BZ2066324 Show Hosts discovery hint link above infraenv hosts list
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
Labels: lgtm, approved

#1422 update react forms wizards
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1407 Bug 2066310: UI remove technology preview badgets from cim
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlData.js
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1423 BZ 2060230: Fix BMH name displayed in the Delete host modal
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
Labels: lgtm, approved, dco-signoff: yes

#1428 Update for Hive: Added OVIRT to provider detection logic.
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1426 Allow conflict for previous KlusterletAddonConfig
  frontend/src/lib/import-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1427 Fix RHV network placeholders
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
Labels: lgtm, approved, dco-signoff: yes

#1429 Fix string for associated placement resources
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#1432 Update temptifly for treeselect fix
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1430 Strings for AWS private
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
Labels: lgtm, approved, dco-signoff: yes

#1391 Bug 2064387: UI when trying to delete an infraenv during installation there is no alert saying we can't
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1424 BZ 2065071: Fix missing clusterDeployment for Scale Up
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
Labels: lgtm, approved, dco-signoff: yes

#1435 Update openshift-assisted-ui-lib to v2.3.4-CIM-2.5
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1436 Update openshift-assisted-ui-lib to v2.3.5-CIM-2.5
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/unbindHost.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/AIClusterDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/utils.ts
Labels: lgtm, approved, dco-signoff: yes

#1439 create/edit policy navigation
  frontend/src/routes/Governance/components/PolicyActionDropdown.tsx
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
Labels: lgtm, approved, dco-signoff: yes

#1438 Enable SyncEditor in production
  frontend/src/components/AcmDataForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1441 App cluster resources status use ui-components
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/css/ApplicationOverview.css
Labels: lgtm, approved, dco-signoff: yes

#1433 Added condition for authentication failure
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1440 update react-form-wizard
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1442 Fix logs tab for resources with pods
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsView.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/YAMLContainer.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers-utils.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.data.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologySubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.test.js
Labels: lgtm, approved, dco-signoff: yes

#1431 dynamic plugins scrolling issue
  frontend/src/components/PluginContextProvider.tsx
Labels: lgtm, approved, dco-signoff: yes

#1444 Aws Gov regions hidden behind config gate
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
Labels: lgtm, approved, dco-signoff: yes

#1445 Fix control logic for secret fetching (Subscription App)
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
Labels: lgtm, approved, dco-signoff: yes

#1450 Subscription node
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/options/filtering.js
Labels: lgtm, approved, dco-signoff: yes

#1451 Cluster pool test updates
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/components/ClusterClaimModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1452 remove dynamic plugin tech preview alert padding
  frontend/src/components/PluginContextProvider.tsx
  frontend/src/components/TechPreviewAlert.tsx
Labels: lgtm, approved, dco-signoff: yes

#1453 Allow http scheme for httpsProxy
  frontend/public/locales/en/translation.json
  frontend/src/lib/validation.ts
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1455 Display branding for Alibaba infrastructure
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1403 Prevents running count form being scaled greater than size
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/components/ScaleClusterPoolModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1456 Show unknown cluster status in governance pages
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/overview/ClusterViolationSummary.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1446 Fix-route
  backend/src/routes/serve.ts
  frontend/src/lib/search.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/utils.js
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Applications/CreateApplication/actions/index.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
  frontend/src/routes/Applications/helpers/resource-helper.test.ts
  frontend/src/routes/Applications/helpers/resource-helper.ts
  frontend/src/routes/Governance/policies/EditPolicy.tsx
Labels: lgtm, approved, dco-signoff: yes

#1458 fix enforce/inform modal for undefined remediation
  frontend/src/routes/Governance/components/PolicyActionDropdown.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1460 rhv tooltip fix
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
Labels: lgtm, approved, dco-signoff: yes

#1448 Fix data from useRecoilValue on infraenv detail page
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes
