Repository stolostron/console, pull requests merged in 2022-01, with the labels that each got.

#1050 MGMT-8160 Add Host unbind action
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.sharedmocks.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/AIHostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/CIMHostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/unbindHost.css
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/unbindHost.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/ai-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/cim-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/AIClusterDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
Labels: lgtm, approved, dco-signoff: yes

#1064 Fix console URL rendering
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/AIClusterDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1052 Add backup labels, fix install config annotation
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
Labels: approved, dco-signoff: yes

#1078 Bugzilla 2032957
  backend/src/routes/ansibletower.ts
  frontend/src/resources/ansible-job.ts
  frontend/src/resources/utils/resource-request.ts
  frontend/webpack.config.ts
Labels: lgtm, approved

#1060 Update backend watch to run a list, reconcile and then watch
  backend/.gitignore
  backend/config/LOG_LEVEL
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/lib/body-parser.ts
  backend/src/lib/logger.ts
  backend/src/resources/resource.ts
  backend/src/routes/ansibletower.ts
  backend/src/routes/events.ts
  backend/tsconfig.json
Labels: lgtm, approved, dco-signoff: yes

#1077 Update apollo/client dep
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Home/Search/SearchPage.test.tsx
Labels: lgtm, approved

#1075 Use attribute-value search in PolicySet page
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarSearch.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved

#1081 Prevent unbinding masters and workers only to installed/error clusters
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/unbindHost.tsx
Labels: lgtm, approved, dco-signoff: yes

#1080 Aws gov handlebar edit
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#1083 Add toolbar filter to policysets page
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarFilter.tsx
Labels: lgtm, approved, dco-signoff: yes

#1072 [2.4 backport] Fix nodes count calculation in AcmCountCardSection
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#1071 Fix nodes count calculation in AcmCountCardSection
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#890 Remove wireguard from the list of cabledrivers
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/resources/submariner-config.ts
Labels: lgtm, approved, dco-signoff: yes

#1084 Fix duplicate PF styles
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarSearch.tsx
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes

#1082 Adjust warning host count calculation
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1085 update popover copy and ui-components version
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Governance/GovernancePage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1086 modify popover properties
  frontend/src/routes/Governance/GovernancePage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1099 update policy sets tab label
  frontend/src/routes/Governance/GovernancePage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1100 Add Policyset unit tests
  frontend/src/resources/index.ts
  frontend/src/routes/Governance/policy-sets/PolicySets.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarSearch.tsx
Labels: lgtm, approved, dco-signoff: yes

#1094 [release-2.2] Switch to @stolostron/ui-components
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AppContext.tsx
  frontend/src/components/BulkActionModel.tsx
  frontend/src/components/ClusterCommon.tsx
  frontend/src/components/ConfirmModal.tsx
  frontend/src/components/ErrorPage.tsx
  frontend/src/lib/get-cluster.ts
  frontend/src/routes/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/BareMetalAssets/CreateBareMetalAsset.tsx
  frontend/src/routes/ClusterManagement/ClusterManagement.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/ClusterManagement/Clusters/ClusterDetails/ClusterSettings/ClusterSettings.tsx
  frontend/src/routes/ClusterManagement/Clusters/Clusters.tsx
  frontend/src/routes/ClusterManagement/Clusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/BatchUpgradeModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ClusterDestroy.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/DownloadConfigurationDropdown.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/EditLabelsModal.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/HiveNotification.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/ImportCommand.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/LoginCredentials.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusField.tsx
  frontend/src/routes/ClusterManagement/Clusters/components/StatusSummaryCount.tsx
  frontend/src/routes/ClusterManagement/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/ProviderConnections/AddConnection/AddConnection.tsx
  frontend/src/routes/ProviderConnections/ProviderConnections/ProviderConnections.tsx
Labels: lgtm, approved, dco-signoff: yes

#1093 [main] Update quay.io references
  scripts/patch-deployment.sh
Labels: lgtm, approved, dco-signoff: yes

#1101 Use proxy alias
  frontend/PLUGIN.md
  frontend/package.json
  frontend/src/components/PluginData.tsx
  frontend/src/lib/usePluginProxy.tsx
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes

#1092 Implement-config
  README.md
  backend/src/routes/events.ts
  features/automation.yaml
  features/cluster-sets.yaml
  features/single-node-openshift.yaml
  frontend/src/FeatureGates.ts
  frontend/src/atoms.tsx
  frontend/src/lib/test-metadata.ts
  frontend/src/resources/feature-gate.ts
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1102 2.4-fix-cred
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataBMC.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
Labels: lgtm, approved, dco-signoff: yes

#1104 policy risk cards
  frontend/src/routes/Governance/components/PolicyRiskLabels.tsx
Labels: lgtm, approved, dco-signoff: yes

#1105 Enhance Policyset details view
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#1107 support react form wizard
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.ts
Labels: lgtm, approved, dco-signoff: yes

#1110 PolicySet details test
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1112 Update governance overview
  frontend/src/components/AcmMasonry.css
  frontend/src/components/AcmMasonry.tsx
  frontend/src/components/StatusIcons.tsx
  frontend/src/components/StatusLabeledIcons.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/PolicyRiskLabels.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/overview/PolicyGrouping.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/useGovernanceData.tsx
  frontend/src/routes/Home/Welcome/Welcome.tsx
Labels: approved, dco-signoff: yes

#1114 fix clipping of labels
  frontend/src/routes/Home/Search/components/Modals/SearchInfoModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1091 Es module support
  .github/workflows/backend-upgrade.yml
  Dockerfile.prow
  backend/package-lock.json
  backend/package.json
  backend/src/lib/logger.ts
  backend/src/routes/events.ts
  backend/test/mock-request.ts
  backend/tsconfig.json
Labels: lgtm, approved, dco-signoff: yes

#1115 Remove application table timer
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetAccessManagement/ClusterSetAccessManagement.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#1117 goverance overview text updates
  frontend/src/components/StatusIcons.tsx
  frontend/src/components/StatusLabeledIcons.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/components/PolicyViolations.tsx
Labels: lgtm, approved, dco-signoff: yes

#1118 Copyright fix
  frontend/src/components/Topology/Topology.d.ts
  frontend/src/components/Topology/helpers/utilities.js
  frontend/src/components/Topology/shapes/DiagramIcons.tsx
  frontend/src/components/Topology/shapes/DiagramShapes.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topology.js
  package.json
  scripts/copyright-check.ts
  scripts/copyright-fix.ts
Labels: lgtm, approved, dco-signoff: yes

#1120 grc text and color tweaks
  frontend/src/components/StatusIcons.tsx
  frontend/src/components/StatusLabeledIcons.tsx
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
Labels: lgtm, approved, dco-signoff: yes

#1122 grc-overview-tweaks-2
  backend/src/lib/logger.ts
  frontend/src/routes/Governance/components/ClusterPolicyViolations.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1126 Update plugin__acm-plugin.json to include "Add credential"
  frontend/public/locales/en/plugin__acm-plugin.json
Labels: lgtm, approved, dco-signoff: yes

#1121 Add provider connection changed to add credential
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1127 Changing "common:learn.more" to "Learn more" on import cluster page
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1109 Fix appearance of the Missing InnfraEnv warning
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1095 Do not show Unbind action for BMHs or AI flow
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/unbindHost.tsx
Labels: lgtm, approved, dco-signoff: yes

#1124 add emptystates for each grc tab
  frontend/src/lib/doc-util.ts
  frontend/src/routes/Governance/GovernancePage.tsx
  frontend/src/routes/Governance/components/GovernanceEmptyState.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.test.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1116 Adding AWS Gov template changes to 2.5 (already merged in 2.4.z)
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#1111 Update proxy path
  frontend/PLUGIN.md
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes

#1129 Update builder image
  Dockerfile.prow
  backend/package-lock.json
  backend/package.json
  package.json
  scripts/copyright-check.ts
Labels: lgtm, approved, dco-signoff: yes

#1128 Non existing secret catch
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: no

#1130 Update AI lib to 2.0.9
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.sharedmocks.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/AIHostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/CIMHostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/HostsForm.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/NetworkForm.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/NetworkForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/DetailsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvForm.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/infraenv-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#1136 Fix position of the AI Create Cluster Card
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlData.js
Labels: lgtm, approved, dco-signoff: yes

#1134 Restore cluster status popover
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusField.tsx
Labels: lgtm, approved, dco-signoff: yes

#1133 Fix cluster status popover 2.4
  frontend/public/locales/en/cluster.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusField.tsx
Labels: lgtm, approved, dco-signoff: yes

#1131 Cluster set fix for cluster claims and cluster pools
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
Labels: lgtm, approved, dco-signoff: yes

#1143 2.3.x fix stale event cache
  backend/package-lock.json
  backend/package.json
  backend/src/lib/cors.ts
  backend/src/lib/respond.ts
  backend/src/lib/token.ts
  backend/src/resources/resource.ts
  backend/src/routes/events.ts
  backend/src/routes/oauth.ts
  backend/src/routes/serve.ts
Labels: lgtm, approved, dco-signoff: yes

#1144 Credential catch strings
  frontend/public/locales/en/plugin__acm-plugin.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
Labels: lgtm, approved, dco-signoff: yes
