Repository stolostron/console, pull requests merged in 2022-07, with the labels that each got.

#1799 Fix route URL for local-cluster 2.6
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
Labels: lgtm, approved, dco-signoff: yes

#1809 Fix typo
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
Labels: lgtm, approved, dco-signoff: yes

#1811 MGMT-8156: Merge translation files from assisted-ui-lib into one file
  frontend/src/typings.d.ts
  frontend/webpack.config.ts
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1814 Disable dark theme detection in standalone production
  frontend/src/theme.tsx
Labels: lgtm, approved, dco-signoff: yes

#1815 Update ui-components to 1.77.0
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1817 fix
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#1818 Use console backend to display user saved searches
  backend/src/routes/events.ts
  frontend/public/locales/en/translation.json
  frontend/src/atoms.tsx
  frontend/src/lib/nock-util.ts
  frontend/src/resources/index.ts
  frontend/src/resources/userpreference.tsx
  frontend/src/routes/Home/Search/SearchPage.test.tsx
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/components/Modals/DeleteSearchModal.test.tsx
  frontend/src/routes/Home/Search/components/Modals/DeleteSearchModal.tsx
  frontend/src/routes/Home/Search/components/Modals/SaveAndEditSearchModal.tsx
  frontend/src/routes/Home/Search/components/Modals/ShareSearchModal.test.tsx
  frontend/src/routes/Home/Search/components/Modals/ShareSearchModal.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.test.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.tsx
  frontend/src/routes/Home/Search/search-sdk/saveSearchQueries.graphql
  frontend/src/routes/Home/Search/search-sdk/search-sdk.ts
  frontend/src/routes/Home/Search/search-sdk/searchQueries.graphql
  frontend/src/routes/Home/Search/urlQuery.test.ts
  frontend/src/routes/Home/Search/urlQuery.ts
Labels: lgtm, approved, dco-signoff: yes

#1820 Restore label behaviour
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1800 Cluster labels section does not show up#22433
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/components/TemplateEditor/controls/ControlPanel.js
  frontend/src/components/TemplateEditor/controls/ControlPanelComboBox.js
  frontend/src/components/TemplateEditor/controls/ControlPanelFormGroup.js
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelCheckbox.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelComboBox.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelLabels.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelMultiSelect.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelNumber.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelSingleSelect.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelTextArea.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelTextInput.test.js.snap
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelTreeSelect.test.js.snap
  frontend/src/components/TemplateEditor/css/control-panel.css
  frontend/src/components/TemplateEditor/utils/initialize-control-data.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/style.css
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlData.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPrePostTasks.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/CreateApplication/Subscription/transformers/transform-resources-to-controls.js
Labels: lgtm, approved, dco-signoff: yes

#1821 Fix provider logic in Overview page
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1822 [2.5] Fix provider logic in Overview page
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1810 Fix-typo-2.5
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
Labels: lgtm, approved, dco-signoff: yes

#1826 Fix search issues
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1827 Creation and deletes existing cluster#23877 2.4
  frontend/public/locales/en/create.json
  frontend/src/lib/create-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
Labels: lgtm, approved, dco-signoff: yes

#1828 Creation and deletes existing cluster#23877 2.5
  frontend/public/locales/en/translation.json
  frontend/src/lib/create-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
Labels: lgtm, approved, dco-signoff: yes

#1824 Creation and deletes existing cluster#23877
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateEditor/controls/ControlPanelCards.js
  frontend/src/components/TemplateEditor/css/control-panel-cards.css
  frontend/src/components/TemplateEditor/css/control-panel.css
  frontend/src/lib/create-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
Labels: lgtm, approved, dco-signoff: yes

#1807 Fix route for local-cluster for 2.5.2
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
Labels: lgtm, approved, dco-signoff: yes

#1825 Update Policy schema with namespace LabelSelector
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/policy.ts
  frontend/src/resources/selector.ts
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
  setup.sh
Labels: lgtm, approved, dco-signoff: yes

#1829 Prevent-adding-to-global-cluster-set#23956
  frontend/src/resources/managed-cluster-set.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useCanJoinClusterSets.tsx
Labels: lgtm, approved, dco-signoff: yes

#1831 ACM-1499: Remove BMA - List page, Create cluster, and Create credentials
  frontend/plugins/mce/console-extensions.json
  frontend/plugins/mce/console-plugin.json
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.ts
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssets.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPage.test.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPage.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/BareMetalAssetsPlugin.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/CreateBareMetalAsset.test.tsx
  frontend/src/routes/Infrastructure/BareMetalAssets/CreateBareMetalAsset.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataBMC.js
Labels: lgtm, approved, dco-signoff: yes

#1716 Enable backend coverage
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/test/routes/configure.spec.ts
  backend/test/routes/consoleLinks.spec.ts
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#1841 Add test for username route
  backend/test/routes/consoleLinks.spec.ts
  backend/test/routes/username.spec.ts
Labels: lgtm, approved, dco-signoff: yes

#1842 Fix access to undefined in getHiveConfig()
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#1843 Fix access to undefined when creating InfraEnv (TemplateEditor)
  frontend/src/components/TemplateEditor/TemplateEditor.js
Labels: lgtm, approved, dco-signoff: yes

#1839 Refactor the way of getting managed cluster
  frontend/src/resources/managed-cluster.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlData.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataGit.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataHelm.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataObjectStore.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataOther.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
  frontend/src/routes/Applications/SubscriptionApplication.test.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#1845 Prevent upgrading hypershift clusters
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/BatchChannelSelectModal.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/BatchUpgradeModal.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterDestroy.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DownloadConfigurationDropdown.old.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/LoginCredentials.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ProgressStepBar.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1830 Alterations to global cluster set
  frontend/public/locales/en/translation.json
  frontend/src/lib/test-metadata.ts
  frontend/src/resources/managed-cluster-set.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/ManagedClusterSetBindingModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1805 Rename infra environments to host inventory
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/HostInventoryBanner.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1850 update packages minor
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  package-lock.json
  package.json
Labels: lgtm, approved, dco-signoff: yes

#1798 Catalog flow for create infrastructure (hypershift designs)
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.ts
  frontend/src/routes/Infrastructure/Clusters/Clusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/setupTests.ts
Labels: lgtm, approved, dco-signoff: yes

#1851 Fix log viewer crash for pod deploy failures 2.5
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.tsx
Labels: lgtm, approved, dco-signoff: yes

#1852 Update packages minor 2
  frontend/jest.config.ts
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1853 Fix log viewer crash for 2.6
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/LogsContainer.tsx
Labels: lgtm, approved, dco-signoff: yes

#1858 add app tests debug sonar properties for stories
  frontend/jest.config.ts
  frontend/src/App.test.tsx
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#1854 BZ2079247: Do not bulk delete infra envs with hosts
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1863 Fix paths for prod/dev for translation file merging
  frontend/webpack.config.ts
Labels: lgtm, approved, dco-signoff: yes

#1862 Run format on save in vscode
  frontend/.vscode/settings.json
Labels: lgtm, approved, dco-signoff: yes

#1868 Update AI lib to v2.6.0-cim
  backend/src/routes/events.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/AIHypershiftClusterDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#1855 Handle unauthorized requests uniformly
  frontend/src/atoms.tsx
  frontend/src/resources/utils/resource-request.ts
Labels: lgtm, approved, dco-signoff: yes

#1872 [release-2.5] Do not cache product version
  backend/src/routes/mchVersion.ts
Labels: lgtm, approved, dco-signoff: yes

#1865 Only run search query when user presses run button
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.test.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/__snapshots__/urlQuery.test.ts.snap
  frontend/src/routes/Home/Search/components/SavedSearchQueries.tsx
  frontend/src/routes/Home/Search/urlQuery.ts
  frontend/src/ui-components/AcmSearchbar/AcmSearchbar.css
  frontend/src/ui-components/AcmSearchbar/AcmSearchbar.test.tsx
  frontend/src/ui-components/AcmSearchbar/AcmSearchbar.tsx
Labels: lgtm, approved, dco-signoff: yes

#1857 Move credential selection to cluster details
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAI.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHypershift.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
Labels: lgtm, approved, dco-signoff: yes

#1873 [release-2.5] Fix path for favicon
  frontend/public/index.html
Labels: lgtm, approved, dco-signoff: yes

#1871 Do not cache product version
  backend/src/routes/mchVersion.ts
Labels: lgtm, approved, dco-signoff: yes

#1875 Fix #23944 - UI crash in cluster discovery
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#1874 Fix path for favicon
  frontend/public/index.html
Labels: lgtm, approved, dco-signoff: yes

#1876 Sync release 2.5 to backplane 2.0
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/lib/create-cluster.ts
  frontend/src/resources/multi-cluster-engine.ts
  frontend/src/routes/Applications/CreateApplication/Subscription/transformers/transform-resources-to-controls.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/CreateClusterPool.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/hive-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/AIClusterDetails.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
  frontend/webpack.config.ts
Labels: lgtm, approved, dco-signoff: yes

#1870 Allow empty value for cluster selector label
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
Labels: lgtm, approved, dco-signoff: yes

#1877 Cherrypick-2.5
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
Labels: lgtm, approved, dco-signoff: yes

#1879 [release-2.5] Use regex to check version
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#1832 ACM plugin custom extension for row action
  frontend/src/components/PluginContextProvider.tsx
  frontend/src/lib/PluginContext.tsx
  frontend/src/plugin-extensions/extensions/ApplicationAction.ts
  frontend/src/plugin-extensions/extensions/index.ts
  frontend/src/plugin-extensions/handler.ts
  frontend/src/plugin-extensions/properties/addActionProps.ts
  frontend/src/plugin-extensions/properties/index.ts
  frontend/src/plugin-extensions/types.ts
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1866 Disable hypershift catalog item if the feature is not enabled
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.tsx
Labels: lgtm, approved, dco-signoff: yes

#1869 Add cancel button for catalog view
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.tsx
Labels: lgtm, approved, dco-signoff: yes

#1882 Bug 2092555: [UI] update wording for alert when no infraenvs are available
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#1883 Reenable AI tests
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1880 [backplane-2.0] Use regex to check version
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#1884 Set default active for credential
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#1887 [release-2.5] Fix log container name
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.tsx
Labels: lgtm, approved, dco-signoff: yes

#1886 [backplane-2.0] Fix log container name
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.tsx
Labels: lgtm, approved, dco-signoff: yes

#1885 Use correct container name for Hive uninstall jobs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.tsx
Labels: lgtm, approved, dco-signoff: yes

#1864 Add warning on policies that will auto-prune
  frontend/public/locales/en/translation.json
  frontend/src/resources/policy.ts
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1889 Update versions for ACM 2.6 / MCE 2.1
  COMPONENT_VERSION
  frontend/plugins/acm/console-plugin.json
  frontend/plugins/mce/console-plugin.json
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#1888 Manage resource assignments
  frontend/src/lib/doc-util.tsx
  frontend/src/lib/patch-cluster.ts
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetManageResources/ClusterSetManageResources.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/GlobalClusterSetPopover.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/BatchChannelSelectModal.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/BatchUpgradeModal.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterDestroy.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DownloadConfigurationDropdown.old.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/LoginCredentials.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ProgressStepBar.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1890 Fix issue unable to delete placementrule with same name in different namespaces 2.6
  frontend/src/routes/Applications/helpers/resource-helper.tsx
Labels: lgtm, approved, dco-signoff: yes

#1892 Reduce search query limit
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/relatedResources.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyOCPFluxApp.js
  frontend/src/routes/Applications/CreateApplication/Subscription/components/SharedResourceWarning.js
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
  frontend/src/routes/Home/Search/SearchPage.test.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.test.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/__snapshots__/search-helper.test.tsx.snap
  frontend/src/routes/Home/Search/components/Modals/DeleteResourceModal.test.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.test.tsx
  frontend/src/routes/Home/Search/components/SearchResults.tsx
  frontend/src/routes/Home/Search/search-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#1895 update patternfly
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/TemplateEditor/components/__snapshots__/EditorBar.test.js.snap
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
  frontend/src/ui-components/AcmTable/AcmTable.test.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
  frontend/src/ui-components/AcmTile/AcmTile.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1899 Fix #23944 - UI crash in cluster discovery (#1875)
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#1897 isValid() function no longer provided for v7 of ip-address
  frontend/src/components/TemplateEditor/utils/validation-types.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlData.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/WrappedImportBareMetalAssetsButton.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/Logos.js
Labels: lgtm, approved, dco-signoff: yes

#1893 Add explanatory text for pending import
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.tsx
Labels: lgtm, approved, dco-signoff: yes

#1898 fix dependency loop causing crash
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#1906 Change MCE plugin infra env nav link to Host inventory
  frontend/plugins/mce/console-extensions.json
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#1902 Add tooltips to control plane page and fix empty create cluster blank…
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateDiscoverHost.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/AddCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1867 Add info about manual import of hypershift cluster
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.tsx
Labels: lgtm, approved, dco-signoff: yes

#1907 Hide helm apps from OCP discovered resources
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1908 Override temptifly back button for new catalog
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/components/TemplateEditor/controls/ControlPanel.js
  frontend/src/components/TemplateEditor/controls/ControlPanelWizard.js
  frontend/src/components/TemplateEditor/index.d.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClustersPage.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClustersPage.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1896 Fix bug on consecutive resource update calls in search details view
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1903 Suppress dark mode when not fully supported
  frontend/src/App.tsx
  frontend/src/theme.tsx
Labels: lgtm, approved, dco-signoff: yes

#1905 Integrate hypershift API publishing strategy fields
  frontend/package-lock.json
  frontend/package.json
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/NetworkForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/hypershift-template.hbs
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/InfraEnvironmentDetailsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1911 Add copy login button for hypershift import
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/HypershiftKubeAPI.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftImportCommand.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.tsx
Labels: lgtm, approved, dco-signoff: yes

#1901 [2.5] Fix bug on consecutive resource update calls in search details …
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1912 update wizard and data-view packages
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
Labels: lgtm, approved, dco-signoff: yes

#1914 Rename Bare Metal infra to Host Inventory
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.tsx
Labels: lgtm, approved, dco-signoff: yes

#1913 Update assisted-ui-lib to v2.5.1-CIM-2.5
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1916 Update PatternFly packages to OCP 4.11 versions
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#1909 Add control plane column for hypershift
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1910 Curator summary widget + link out to template
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateSummaryModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#1917 resource plural support fix
  frontend/src/atoms.tsx
  frontend/src/resources/custom-resource-definition.ts
  frontend/src/resources/resource.ts
Labels: lgtm, approved, dco-signoff: yes

#1918 update to PatternFly 4.221.11 for side drawer crash fix
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1900 fix editing of resources
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#1919 Fix placement deletion issue in 2.5
  frontend/src/routes/Applications/helpers/resource-helper.tsx
Labels: lgtm, approved, dco-signoff: yes

#1904 cluster bulk-automation modal
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#1924 [backplane-2.0] npm audit fix
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1925 [release-2.5] npm audit fix
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1923 [release-2.4] npm audit fix
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#1921 Fix overview card cluster issues count
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1920 [2.5] resource plural fix
  backend/src/routes/events.ts
  frontend/src/atoms.tsx
  frontend/src/resources/custom-resource-definition.ts
  frontend/src/resources/index.ts
  frontend/src/resources/resource.ts
Labels: lgtm, approved, dco-signoff: yes

#1922 [release-2.3] npm audit fix
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, dco-signoff: yes

#1926 [2.5] Fix overview card cluster issues count
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#1891 BZ2053000 Include custom styles in Clusters plugin entry component
  frontend/src/routes/Infrastructure/Clusters/ClustersPlugin.css
  frontend/src/routes/Infrastructure/Clusters/ClustersPlugin.tsx
Labels: lgtm, approved, dco-signoff: yes

#1927 Multiple text fixes for catalog
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateInfrastructure.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#1928 Rbac added to edit button
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetOverview/ClusterSetOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#1930 Include custom styles in Clusters plugin entry component (#1891)
  frontend/src/routes/Infrastructure/Clusters/ClustersPlugin.css
  frontend/src/routes/Infrastructure/Clusters/ClustersPlugin.tsx
Labels: lgtm, approved, dco-signoff: yes

#1932 Add checks for optional fields
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#1931 Update Automation strings
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#1933 fix labels change for secret patch
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/UpdateAutomationModal.tsx
Labels: lgtm, approved, dco-signoff: yes
