Repository stolostron/console, pull requests merged in 2023-02, with the labels that each got.

#2526 Skip search query when OCP apps are filtered out
  frontend/src/lib/search.ts
  frontend/src/routes/Applications/Application.sharedmocks.tsx
  frontend/src/routes/Applications/ApplicationsPage.tsx
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#2527 Use accordion to present search results
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Search/SearchResults/RelatedResults.test.tsx
  frontend/src/routes/Home/Search/SearchResults/RelatedResults.tsx
  frontend/src/routes/Home/Search/SearchResults/RelatedResultsTables.tsx
  frontend/src/routes/Home/Search/SearchResults/RelatedResultsTiles.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.test.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/SearchResults/utils.tsx
Labels: lgtm, approved, dco-signoff: yes

#2529 Mark more policies as externally managed
  frontend/src/routes/Governance/common/util.test.tsx
  frontend/src/routes/Governance/common/util.tsx
Labels: lgtm, approved, dco-signoff: yes

#2531 ACM-2918 sync monaco editor version to ocp at 0.20
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/YamlEditor.tsx
Labels: lgtm, approved, dco-signoff: yes

#2530 ACM-2661 Shows upgrade available under distribution version
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#2532 MGMT-13551 Move reconcilePause control to automationControlData
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAI.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAWS.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAZR.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataCIM.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataGCP.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataHypershift.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataOST.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataRHV.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataVMW.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#2534 Change Onboarding modal footer colour to gray and support dark mode
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/OnboardingModal.css
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/OnboardingModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#2523 Applied fix for https://issues.redhat.com/browse/ACM-3010 Chinese translation
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#2536 ACM-2411
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftClusterInstallProgress.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#2535 Allow for search results refresh
  frontend/src/routes/Home/Search/SearchPage.test.tsx
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.test.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/components/Searchbar.test.tsx
  frontend/src/routes/Home/Search/components/Searchbar.tsx
Labels: lgtm, approved, dco-signoff: yes

#2538 ACM-3214
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#2539 ACM-2664
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#2537 trans fixes, acmdataform need eyes
  frontend/public/locales/en/translation.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/TemplateSummaryModal.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/overview/PolicySetViolationSummary.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
  frontend/src/ui-components/AcmTextInput/AcmTextInput.tsx
Labels: lgtm, approved, dco-signoff: yes

#2541 ACM-2863 Fix create application button in dark mode
  frontend/src/routes/Applications/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#2543 ACM-3019
  frontend/src/routes/Applications/components/DeleteResourceModal.tsx
  frontend/src/routes/Applications/css/DeleteResourceModal.css
Labels: lgtm, approved, dco-signoff: yes

#2545 Add missing wizard tests (es2020)
  frontend/jest.config.ts
  frontend/src/wizards/Argo/ArgoWizard.test.tsx
  frontend/src/wizards/Argo/ArgoWizard.tsx
  frontend/src/wizards/PolicyAutomation/PolicyAutomationWizard.test.tsx
  frontend/src/wizards/PolicyAutomation/PolicyAutomationWizard.tsx
  frontend/tsconfig.dev.json
Labels: lgtm, approved, dco-signoff: yes

#2542 trans fixes in control panel and aria-labels
  frontend/public/locales/en/translation.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/TemplateEditor/controls/ControlPanelFinish.js
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HypershiftAWSCLI.tsx
Labels: lgtm, approved, dco-signoff: yes

#2533 [2.7] MGMT-13551 Move reconcilePause control to automationControlData
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAI.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAWS.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAZR.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataCIM.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataGCP.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataHypershift.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataOST.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataRHV.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataVMW.test.js.snap
Labels: approved, dco-signoff: yes

#2547 Fix onboarding modal ACM doc link 2.7.1
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/OnboardingModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#2551 Color class correction
  frontend/src/routes/Governance/overview/PolicyViolationSummary.tsx
Labels: lgtm, approved, dco-signoff: yes

#2553 Fix onboarding modal ACM doc link 2.8
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/OnboardingModal.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/OnboardingModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#2556 ACM-3344
  frontend/src/routes/Applications/css/DeleteResourceModal.css
Labels: lgtm, approved, dco-signoff: yes

#2557 Fix search result label styling for PolicyReports
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/Home/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#2548 Fix search issue in cluster list and application
  frontend/src/routes/Home/Search/components/Searchbar.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#2558 ACM-3243 Remove add on consideration
  frontend/src/resources/utils/get-cluster.test.ts
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/useAllClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#2559 ACM-3264:Add alert in topo to show search disabled
  frontend/public/locales/en/translation.json
  frontend/src/lib/search.ts
  frontend/src/routes/Applications/Application.sharedmocks.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/topology/Topology.test.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/topology/Topology.tsx
Labels: lgtm, approved, dco-signoff: yes

#2554 color class change
  frontend/src/routes/Governance/overview/PolicyViolationSummary.tsx
Labels: lgtm, approved, dco-signoff: yes

#2562 Fix case where users use same name different namespace for resources 2.8
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsTable.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
Labels: lgtm, approved, dco-signoff: yes

#2563 [2.7] Fix search result label styling for PolicyReports
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.ts.snap
  frontend/src/routes/Home/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#2560 ACM-3426
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/OnboardingModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#2561 ACM-2112 Fix filter value clash
  frontend/jest.config.ts
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/ui-components/AcmTable/AcmTable.test.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#2567 Fix case where users use same name different namespace for resources 2.7
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsTable.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
Labels: lgtm, approved, dco-signoff: yes

#2568 cluster table add-ons column
  frontend/public/locales/en/translation.json
  frontend/src/resources/utils/get-addons.ts
  frontend/src/resources/utils/get-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/useAllClusters.tsx
  frontend/src/ui-components/AcmInlineStatus/AcmInlineStatusGroup.tsx
Labels: lgtm, approved, dco-signoff: yes

#2565 ACM-2237 for 2.7
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataGCP.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataOST.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataRHV.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAWS.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAZR.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataGCP.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataOST.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataRHV.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataVMW.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#2569 ACM-2883
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ClusterDetailsContainer.js
Labels: lgtm, approved, dco-signoff: yes

#2574 ACM-2918 sync monaco editor version to op 2.7
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/YamlEditor.tsx
Labels: lgtm, approved, dco-signoff: yes

#2573 Policy Set view - make keyboard accessible and reduce duplication
  frontend/src/routes/Governance/policy-sets/components/CardViewToolbarFilter.tsx
Labels: lgtm, approved, dco-signoff: yes

#2572 ACM-2918 fix sync editor
  frontend/__mocks__/react-monaco-editor.tsx
  frontend/src/components/SyncEditor/SyncEditor.tsx
Labels: lgtm, approved, dco-signoff: yes

#2578 ACM-3454 ACM-3455 Translate Add annotations on policies
  frontend/src/wizards/Placement/PlacementSection.tsx
  frontend/src/wizards/Policy/PolicyWizard.tsx
Labels: lgtm, approved, dco-signoff: yes

#2579 Fix infinite spinner on logs page
  frontend/src/routes/Home/Search/Details/LogsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#2552 ACM-2112 Add node and addon filtering to clusters list
  frontend/public/locales/en/translation.json
  frontend/src/resources/utils/get-addons.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterSettings/ClusterSettings.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/ui-components/AcmInlineStatus/AcmInlineStatus.tsx
Labels: lgtm, approved, dco-signoff: yes

#2580 [2.7] Fix infinite spinner on logs page
  frontend/src/routes/Home/Search/Details/LogsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#2570 ACM-3244 Missing breadcrumbs
  frontend/i18next-parser.config.js
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Applications/SubscriptionApplication.test.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
  frontend/src/routes/Governance/policies/CreatePolicy.test.tsx
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.test.tsx
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicyAutomation.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
  frontend/src/wizards/Argo/ArgoWizard.tsx
  frontend/src/wizards/Policy/PolicyWizard.tsx
  frontend/src/wizards/PolicyAutomation/PolicyAutomationWizard.tsx
  frontend/src/wizards/PolicySet/PolicySetWizard.tsx
  frontend/src/wizards/WizardPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#2577 ACM-3034 - architecture field now singleselect, with new architecture types
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAWS.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAZR.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataGCP.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataOST.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataRHV.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataVMW.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#2549 ACM 2113 -- Overview page cluster add on statuses
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useClusterAddons.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
  frontend/src/ui-components/AcmCharts/AcmDonutChart/AcmDonutChart.tsx
Labels: lgtm, approved, dco-signoff: yes

#2576 trans fixes for 3459, 3462, 3463, 3458,
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Home/Search/Details/DetailsOverviewPage.tsx
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
  frontend/src/routes/Home/Search/components/Searchbar.tsx
  frontend/src/wizards/Argo/ArgoWizard.test.tsx
  frontend/src/wizards/Argo/ArgoWizard.tsx
  frontend/src/wizards/PolicyAutomation/PolicyAutomationWizard.test.tsx
  frontend/src/wizards/PolicyAutomation/PolicyAutomationWizard.tsx
Labels: approved, do-not-merge/hold, dco-signoff: yes

#2555 [2.6] ACM-3668 Move installAttemptsLimit control to automationControlData
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#2575 Fix case where users use same name different namespace for resources 2.6
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/DetailsTable.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeRelated.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
Labels: lgtm, approved, dco-signoff: yes

#2583 Enable a11y linting
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/StatusLabeledIcons.tsx
  frontend/src/components/TemplateEditor/components/EditorHeader.js
  frontend/src/components/TemplateEditor/controls/ControlPanelComboBox.js
  frontend/src/components/TemplateEditor/controls/ControlPanelTreeSelect.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
  frontend/src/routes/Home/Search/components/Searchbar.tsx
  frontend/src/routes/Home/Welcome/Welcome.tsx
  frontend/src/ui-components/AcmCountCard/AcmCountCardSection.tsx
  frontend/src/ui-components/AcmDescriptionList/AcmDescriptionList.stories.tsx
  frontend/src/ui-components/AcmDescriptionList/AcmDescriptionList.test.tsx
  frontend/src/ui-components/AcmDrawer/AcmDrawer.tsx
  frontend/src/ui-components/AcmInlineStatus/AcmInlineStatus.stories.tsx
  frontend/src/ui-components/AcmInlineStatus/AcmInlineStatus.test.tsx
  frontend/src/ui-components/AcmLabelsInput/AcmLabelsInput.tsx
  frontend/src/ui-components/AcmLaunchLink/AcmLaunchLink.test.tsx
  frontend/src/ui-components/AcmPage/AcmPage.stories.tsx
  frontend/src/ui-components/AcmPage/AcmPage.tsx
  frontend/src/ui-components/AcmPageProcess/AcmPageProcess.tsx
Labels: lgtm, approved, dco-signoff: yes

#2582 ACM-3640: fix channel rbac issues
  frontend/public/locales/en/translation.json
  frontend/src/resources/channel.ts
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataGit.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataHelm.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataObjectStore.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/SubscriptionApplication.test.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#2585 Remove pre-commit hook
  .husky/pre-commit
  backend/package.json
  frontend/package.json
  lint-staged.config.js
  package.json
Labels: lgtm, approved, dco-signoff: yes

#2546 ACM-3195
  frontend/src/components/Topology/css/topology-details.css
Labels: lgtm, approved, dco-signoff: yes

#2587 Update README.md file
  README.md
Labels: lgtm, approved, dco-signoff: yes

#2588 update react-form-wizard version. update wizardstring object
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/lib/wizardStrings.ts
Labels: lgtm, approved, dco-signoff: yes

#2592 Pull translation files from https://github.com/rh-tchuang/acm-console…
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
Labels: lgtm, approved, dco-signoff: yes

#2584 ACM-3640: fix channel rbac issues
  frontend/public/locales/en/translation.json
  frontend/src/resources/channel.ts
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataGit.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataHelm.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataObjectStore.js
  frontend/src/routes/Applications/CreateApplication/Subscription/controlData/utils.js
  frontend/src/routes/Applications/SubscriptionApplication.test.tsx
  frontend/src/routes/Applications/SubscriptionApplication.tsx
Labels: lgtm, approved, dco-signoff: yes

#2593 Make sure singular form is singular
  frontend/public/locales/en/translation.json
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#2595 ACM-3478 Wizard namespace list is unsorted
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#2596 translation function applied
  frontend/src/components/AcmDataForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#2594 ACM-3663: Fix breadcrumbs
  frontend/public/locales/en/translation.json
  frontend/src/routes/Credentials/CreateCredentialsCatalog.tsx
  frontend/src/routes/Credentials/CreateCredentialsType/CreateCredentialsAWS.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#2597 ACM-3493 editing the name of a policy placement
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
  frontend/src/wizards/WizardPage.css
  frontend/src/wizards/WizardPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#2601 ACM-3493-disable-all-of-placement-rule
  frontend/src/routes/Governance/policies/EditPolicy.tsx
  frontend/src/routes/Governance/policy-sets/EditPolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#2600 cleanup from missed trans strings
  frontend/public/locales/en/translation.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/TemplateEditor/components/EditorHeader.js
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/overview/PolicySetViolationSummary.tsx
  frontend/src/routes/Governance/overview/PolicyViolationSummary.tsx
Labels: approved, dco-signoff: yes

#2598 ACM-3760 - Worker zone updater fix
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
Labels: lgtm, approved, dco-signoff: yes

#2606 UI fix of NavItem highlighting
  frontend/src/App.tsx
Labels: lgtm, approved, dco-signoff: yes

#2604 ACM-3860
  setup.sh
Labels: lgtm, approved, dco-signoff: yes

#2608 Remove extra div
  frontend/src/wizards/WizardPage.css
  frontend/src/wizards/WizardPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#2607 ACM-3122 Icon updates
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/TemplateEditor/components/EditorBar.js
  frontend/src/components/TemplateEditor/components/__snapshots__/EditorBar.test.js.snap
  frontend/src/components/TemplateEditor/controls/ControlPanel.js
  frontend/src/components/TemplateEditor/controls/ControlPanelAccordion.js
  frontend/src/components/TemplateEditor/controls/ControlPanelPrompt.js
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelPrompt.test.js.snap
  frontend/src/components/TemplateEditor/css/control-panel.css
  frontend/src/components/TemplateEditor/icons/Icons.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/style.css
  frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/index.js
  frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/style.css
  frontend/src/routes/Applications/css/ApplicationOverview.css
  frontend/src/routes/Applications/style.css
Labels: lgtm, approved, dco-signoff: yes

#2612 ACM-3851 ACM-3850 : Addon detection fix
  frontend/src/resources/utils/get-addons.ts
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#2611 ACM-3940 Fix Ansible icon
  frontend/src/ui-components/AcmIcons/AnsibleIcon.tsx
  frontend/src/ui-components/AcmIcons/ansible-icon.css
  frontend/src/ui-components/AcmIcons/createAcmIcon.tsx
Labels: lgtm, approved, dco-signoff: yes
