Repository stolostron/console, pull requests merged in 2024-02, with the labels that each got.

#3249 Use loading state to skip saved search query
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.test.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.tsx
Labels: lgtm, approved, dco-signoff: yes

#3209 ACM-9163 Update to nodejs 20
  .nvmrc
  .tool-versions
  Dockerfile.mce.prow
  Dockerfile.prow
  README.md
  package.json
Labels: lgtm, approved, dco-signoff: yes

#3247 Bump AI lib to 2.9.15
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/NetworkForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/types.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#3253 Bump AI UI Lib to 2.10.0
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/resources/node-pool.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/DetailsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HypershiftAgentContext.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/NetworkForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/types.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/hypershift-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolForm.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#3246 Bump AI lib to 2.8.7
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#3254 Change OCP authentication from service account to token
  start-ocp-console.sh
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#3261 Rhtap deps
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: approved, dco-signoff: yes

#3255 ACM-6587 Include saved search card in fleet view page
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Overview/OverviewPageBeta.test.tsx
  frontend/src/routes/Home/Overview/OverviewPageBeta.tsx
  frontend/src/routes/Home/Overview/SavedSearchesCard.test.tsx
  frontend/src/routes/Home/Overview/SavedSearchesCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#3264 Revert "Rhtap deps"
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: dco-signoff: no

#3265 Rhtap/references/backplane 2.4
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: approved, dco-signoff: yes

#3267 Rhtap/references/backplane 2.5
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: approved, dco-signoff: yes

#3259 ACM-9792 Implement feature to customize Argo and OCP app search…
  backend/config/APP_ARGO_SEARCH_RESULT_LIMIT
  backend/config/APP_OCP_SEARCH_RESULT_LIMIT
  frontend/src/atoms.ts
  frontend/src/components/GetDiscoveredOCPApps.tsx
  frontend/src/lib/search.ts
  frontend/src/routes/Applications/Application.sharedmocks.tsx
Labels: lgtm, approved, dco-signoff: yes

#3274 ACM-9268 KubeVirt hosted cluster creation wizard
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/components/TemplateEditor/controls/ControlPanel.js
  frontend/src/components/TemplateEditor/controls/ControlPanelBoolean.js
  frontend/src/components/TemplateEditor/controls/ControlPanelBoolean.test.js
  frontend/src/components/TemplateEditor/controls/__snapshots__/ControlPanelBoolean.test.js.snap
  frontend/src/resources/storage-class.ts
  frontend/src/routes/Credentials/CreateCredentials.test.tsx
  frontend/src/routes/Credentials/CreateCredentialsCatalog.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
  frontend/src/routes/Credentials/schema.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataKubeVirt.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataKubeVirt.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataKubeVirt.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/kubevirt-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/CreateKubeVirtControlPlane.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/CreateKubeVirtControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/GetHostedCard.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/GetHostedCard.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/__snapshots__/GetHostedCard.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#3260 update err output when failed get logs
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Search/Details/LogsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3279 ACM-9859 Fix typos for Argo create wizard
  frontend/public/locales/en/translation.json
  frontend/src/components/GitOpsOperatorAlert.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgoPullModel.test.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgoPullModel.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/wizards/Argo/ArgoWizard.tsx
Labels: lgtm, approved, dco-signoff: yes

#3278 Allow minReplicas to be 0 for autoscaling
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterDetails.sharedmocks.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/components/ScaleMachinePoolModal.tsx
  frontend/src/ui-components/AcmNumberInput/AcmNumberInput.tsx
Labels: lgtm, approved, dco-signoff: yes

#3277 Only set new credential once
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#3280 ACM-9781 Avoid unnecessary network request while userpreference loads
  frontend/src/routes/Home/Search/SearchPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3281 Remove DELETED event after broadcast to current clients
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#3284 ACM-9887 Remove DELETED event after broadcast to current clients
  backend/src/routes/events.ts
Labels: lgtm, approved, dco-signoff: yes

#3276 Fix filtering of actions related to auto-scaling machine pools
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterMachinePools/ClusterMachinePools.tsx
Labels: lgtm, approved, dco-signoff: yes

#3287 Fix saved search CRUD bug
  frontend/src/routes/Home/Overview/SavedSearchesCard.test.tsx
  frontend/src/routes/Home/Overview/SavedSearchesCard.tsx
  frontend/src/routes/Home/Search/SearchPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3288 Add support for IBMPower Clusters
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#3290 ACM-9915: show compute and root storage
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#3289 ACM-9650 Fix edit/delete on hub in self-management disabled mode
  frontend/src/routes/Home/Search/Details/YAMLPage.tsx
  frontend/src/routes/Home/Search/components/Modals/DeleteResourceModal.test.tsx
  frontend/src/routes/Home/Search/components/Modals/DeleteResourceModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#3294 ACM-9907 Remove KubeVirt cli based catalog card
  frontend/public/locales/en/translation.json
  frontend/src/NavigationPath.ts
  frontend/src/routes/Infrastructure/Clusters/Clusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HypershiftKubeVirtCLI.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HypershiftKubeVirtCLI.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/CreateKubeVirtControlPlane.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/CreateKubeVirtControlPlane.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/GetHostedCard.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/GetHostedCard.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/__snapshots__/GetHostedCard.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#3291 ACM-9933 Extract details from OperatorPolicy
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#3295 updated anchors in links
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HypershiftAWSCLI.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/common/DocPage.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/__snapshots__/GetHostedCard.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#3299 ACM-9969 Fix globalhub & global search enabled check
  frontend/src/routes/Home/Search/SearchResults/RelatedResults.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
Labels: lgtm, approved, dco-signoff: yes

#3296 ACM-8935 Fix HostedCluster upgrade not displaying in dropdown
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/utils/cluster-actions.ts
Labels: lgtm, approved, dco-signoff: yes

#3301 ACM-9976 chore(i18n): update translations
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
Labels: lgtm, approved, dco-signoff: yes

#3302 ACM-9977 chore(i18n): update translations
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
Labels: lgtm, approved, dco-signoff: yes

#3305 ACM-9914: Fix add nodepool tooltip text to use hcp CLI
  frontend/public/locales/en/translation.json
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsProgress.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#3304 Fix TS eslint problem
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3306 ACM-9908 Kubevirt core & memory should have a min value of 1
  frontend/src/components/TemplateEditor/controls/ControlPanelNumber.js
  frontend/src/components/TemplateEditor/controls/ControlPanelNumber.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataKubeVirt.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataKubeVirt.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#3307 Acm 9619 - Edit labels fix
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/EditLabels.tsx
Labels: lgtm, approved, dco-signoff: yes

#3310 ACM-9967 fix cursor moving bug in search yaml editor
  frontend/src/components/YamlEditor.tsx
Labels: lgtm, approved, dco-signoff: yes

#3311 ACM-6587 Display search unavailable error if search is not configured
  frontend/src/lib/nock-util.ts
  frontend/src/routes/Home/Overview/SavedSearchesCard.test.tsx
  frontend/src/routes/Home/Overview/SavedSearchesCard.tsx
Labels: lgtm, approved, dco-signoff: yes

#3313 ACM-9906 Default namespace to clusters for KubeVirt
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/kubevirt-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#3320 ACM-10049 Drop 4.12 and add 4.16 for discovery
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#3309 Bump AI Lib to 2.10.1-cim
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3308 Bump AI Lib to 2.8.8-cim
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3322 ACM-10148 Fix KubeVirt ui creation fails if clusters ns doesn't exist
  frontend/src/lib/create-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/kubevirt-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#3324 CVE fix for release-2.9
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#3327 CVE fix for release-2.7
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#3325 CVE fix for release-2.8
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes
