Repository stolostron/console, pull requests merged in 2024-12, with the labels that each got.

#4116 ACM-16018 Refactor multi-namespace self access checks
  frontend/src/components/LoadData.tsx
  frontend/src/lib/rbac-util.test.ts
  frontend/src/lib/rbac-util.ts
  frontend/src/resources/self-subject-access-review.ts
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/components/ToggleSelector.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsProgress.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#4114 ACM-16020 Refactor multi-namespace self access checks [release-2.11]
  frontend/src/components/LoadData.tsx
  frontend/src/lib/rbac-util.test.ts
  frontend/src/lib/rbac-util.ts
  frontend/src/resources/self-subject-access-review.ts
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/components/ToggleSelector.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsProgress.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#4113 ACM-16021 Refactor multi-namespace self access checks [release-2.10]
  frontend/src/components/LoadData.tsx
  frontend/src/lib/rbac-util.test.ts
  frontend/src/lib/rbac-util.ts
  frontend/src/resources/self-subject-access-review.ts
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/components/ToggleSelector.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policy-sets/PolicySets.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsProgress.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/NodePoolsTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#4052 IngressVIPs for VMW cluster creation
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateEditor/TemplateEditor.js
  frontend/src/components/TemplateEditor/controls/ControlPanel.js
  frontend/src/components/TemplateEditor/controls/ControlPanelFinish.js
  frontend/src/components/TemplateEditor/controls/ControlPanelFormGroup.tsx
  frontend/src/components/TemplateEditor/controls/ControlPanelMultiTextInput.test.tsx
  frontend/src/components/TemplateEditor/controls/ControlPanelMultiTextInput.tsx
  frontend/src/components/TemplateEditor/utils/validate-controls.js
  frontend/src/components/TemplateEditor/utils/validate-controls.test.js
  frontend/src/resources/install-config.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.test.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataVMW.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataVMW.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/install-config.hbs
Labels: lgtm, approved, dco-signoff: yes

#4126 Add filter option as No status for VAPB in discovered
  frontend/src/routes/Governance/discovered/DiscoveredPolicies.test.tsx
  frontend/src/routes/Governance/discovered/DiscoveredPolicies.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4143 Adjust test timeout
  frontend/src/routes/Credentials/CredentialsForm.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/setupTests.ts
Labels: lgtm, approved, dco-signoff: yes

#4140 Fix critical console bugs related to policies with exceptional templates
  frontend/src/resources/policy.ts
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4110 ACM-13003-Fast-cluster-page-load
  .vscode/launch.json
  .vscode/tasks.json
  backend/src/lib/gigantic.ts
  backend/src/lib/server-side-events.ts
  backend/src/routes/aggregators/applications.ts
  backend/src/routes/events.ts
  frontend/package.json
  frontend/src/atoms.ts
  frontend/src/components/ErrorPage.tsx
  frontend/src/components/LoadData.tsx
  frontend/src/components/LoadPluginData.tsx
  frontend/src/components/PluginDataContextProvider.test.tsx
  frontend/src/lib/PluginDataContext.tsx
  frontend/src/routes/Governance/overview/Overview.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/ui-components/AcmEmptyState/AcmEmptyState.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, do-not-merge/hold, dco-signoff: yes

#4141 ACM-15920 - Min value validator for kubevirt Core and Memory field.
  frontend/public/locales/en/translation.json
  frontend/src/components/TemplateEditor/utils/validation-types.test.ts
  frontend/src/components/TemplateEditor/utils/validation-types.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataKubeVirt.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataKubeVirt.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#4148 SyncEditor - Do not use effect to respond to changes
  frontend/src/components/SyncEditor/SyncEditor.tsx
Labels: lgtm, approved, dco-signoff: yes

#4123 ACM-15840 Validate hosted cluster namespace for HCP on KubeVirt wizard
  frontend/public/locales/en/translation.json
  frontend/src/lib/temptifly-utils.ts
  frontend/src/resources/managed-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataKubeVirt.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataKubeVirt.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#4150 Package updates
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#4151 ACM-16224 ACM-16230 Upgrade nanoid to 3.3.8
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#4154 ACM-16423: Use cluster claims for hosted clusters
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#4076 ACM-14462-Application-page-with-lots-of-clusters:
  frontend/src/ui-components/AcmTable/AcmTable.stories.tsx
  frontend/src/ui-components/AcmTable/AcmTable.test.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#4161 ACM-15271-Prevent unintended react form wizard submission
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#4145 [ACM-16080] Dynamic VM actions in search results and details page
  frontend/src/routes/Search/Details/DetailsPage.test.tsx
  frontend/src/routes/Search/Details/DetailsPage.tsx
  frontend/src/routes/Search/SearchResults/RelatedResults.tsx
  frontend/src/routes/Search/SearchResults/SearchResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#4160 Bump AI Lib to 2.14.0-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/DetailsForm.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/DetailsForm.test.tsx.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/HostForm.test.tsx.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/NetworkForm.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#4147 [ACM-15258] Update VM page error message
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#4129 ACM-15850-Polling-from-console-pods-adding-too-much-load-on-search
  backend/config/APP_ARGO_SEARCH_RESULT_LIMIT
  backend/config/APP_OCP_SEARCH_RESULT_LIMIT
  backend/config/APP_SEARCH_INTERVAL
  backend/config/APP_SEARCH_LIMIT
  backend/src/lib/clusters.ts
  backend/src/lib/config.ts
  backend/src/lib/search.ts
  backend/src/routes/aggregator.ts
  backend/src/routes/aggregators/applications.ts
  backend/src/routes/aggregators/applicationsArgo.ts
  backend/src/routes/aggregators/applicationsOCP.ts
  backend/src/routes/aggregators/statuses.ts
  backend/src/routes/aggregators/utils.ts
  backend/test/routes/aggregator.test.ts
Labels: lgtm, approved, dco-signoff: yes

#4159 [Release-2.11]Fix critical console bugs related to policies with exceptional templates
  frontend/src/resources/policy.ts
  frontend/src/routes/Governance/common/util.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
Labels: lgtm, approved, dco-signoff: yes

#4164 ACM-16417 Fix redirect on click + spacing
  frontend/src/routes/Applications/components/LabelWithPopover.tsx
  frontend/src/routes/Applications/css/ResourceLabels.css
Labels: lgtm, approved, dco-signoff: yes

#4170 Make monaco globally accessible for testing
  frontend/webpack.config.ts
  frontend/webpack.plugin.ts
Labels: lgtm, approved, dco-signoff: yes

#4168 Update OWNERS file
  OWNERS
Labels: lgtm, approved, dco-signoff: yes

#4169 Fix message typo
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftUpgradeModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#4167 ACM-16411 Fix policy set detail sidebar
  frontend/src/routes/Governance/policy-sets/components/PolicySetCard.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
  frontend/src/ui-components/AcmDrawer/AcmDrawer.tsx
Labels: lgtm, approved, dco-signoff: yes

#4162 Add generated objects in the Kyverno policy template details page
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/Governance.tsx
  frontend/src/routes/Governance/components/TemplateDetailTitle.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/KyvernoRelatedResources.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/KyvernoRelatedResources.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/KyvernoTable.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetailHooks.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetails.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetailsColumns.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetailsPage.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetailsPage.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateYaml.tsx
Labels: lgtm, approved, dco-signoff: yes
