Repository stolostron/console, pull requests merged in 2024-05, with the labels that each got.

#3465 [ACM-10917] Add search definition for VirtualMachines
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.tsx.snap
  frontend/src/routes/Home/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#3418 Add support for IBMZ in SubmarinerAddon
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#3467 ACM-11007 Fix crash when no PlacementRules are in templateObject
  frontend/src/routes/Applications/CreateApplication/Subscription/transformers/transform-resources-to-controls.js
Labels: lgtm, approved, dco-signoff: yes

#3466 Update suggested query templates to include virtual machine search
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Search/components/SuggestedQueryTemplates.ts
Labels: lgtm, approved, dco-signoff: yes

#3471 update paramaters for migration 0.3->0.4
  .tekton/console-mce-mce-25-pull-request.yaml
  .tekton/console-mce-mce-25-push.yaml
Labels: dco-signoff: yes

#3472 update paramaters for migration 0.3->0.4
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: dco-signoff: yes

#3475 add containerfile for acm update dockerfile ref
  .tekton/console-acm-210-pull-request.yaml
  Containerfile.acm.konflux
Labels: dco-signoff: yes

#3476 Kon acm onboard
  Containerfile.acm.konflux
Labels: approved, dco-signoff: no

#3477 Fix i18next issues in governance page
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/PolicyTableCell.tsx
Labels: lgtm, approved, dco-signoff: yes

#3479 ACM-11564 Fix appsub duplicate cluster selector error
  frontend/src/routes/Applications/CreateApplication/Subscription/common/ClusterSelector/index.tsx
Labels: lgtm, approved, dco-signoff: yes

#3481 Fix topology link for global search apps
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.tsx.snap
  frontend/src/routes/Home/Search/searchDefinitions.test.tsx
  frontend/src/routes/Home/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#3485 migration dep-bas-img-check
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: approved, dco-signoff: yes

#3484 Explain that IamPolicy is no longer supported on the details page
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
Labels: lgtm, approved, dco-signoff: yes

#3482 Remove unnecessary global search checks
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterNodes/ClusterNodes.tsx
Labels: lgtm, approved, dco-signoff: yes

#3483 Remove validation on operator policy sub name
  frontend/src/wizards/Governance/Policy/PolicyWizard.tsx
Labels: lgtm, approved, dco-signoff: yes

#3488 Switch to task-buildah-6gb for pull requests
  .tekton/console-acm-210-pull-request.yaml
  .tekton/console-mce-mce-25-pull-request.yaml
Labels: lgtm, approved, dco-signoff: yes

#3489 Add action dropdown to search details page header
  frontend/src/routes/Home/Search/Details/DeleteResourceModal.test.tsx
  frontend/src/routes/Home/Search/Details/DeleteResourceModal.tsx
  frontend/src/routes/Home/Search/Details/DetailsPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3494 [ACM-11686] Add managedHub column to clusters table in global search results
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Search/__snapshots__/searchDefinitions.test.tsx.snap
  frontend/src/routes/Home/Search/searchDefinitions.test.tsx
  frontend/src/routes/Home/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#3495 Match image versions to current downstream [release-2.10]
  .dockerignore
  .tekton/console-mce-mce-25-pull-request.yaml
  .tekton/console-mce-mce-25-push.yaml
  Containerfile.acm.konflux
  Containerfile.mce.konflux
Labels: lgtm, approved, dco-signoff: yes

#3498 Maintenance updates
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3501 Fix issue with partial matching in searchbar due to upper case
  frontend/src/routes/Home/Search/components/Searchbar.tsx
Labels: lgtm, approved, dco-signoff: yes

#3497 Add Konflux containerfiles
  .dockerignore
  .tekton/console-mce-mce-25-pull-request.yaml
  .tekton/console-mce-mce-25-push.yaml
  Containerfile.acm.konflux
  Containerfile.mce.konflux
Labels: lgtm, approved, dco-signoff: yes

#3503 ACM-11634 Update braces [release-2.10]
  backend/package-lock.json
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#3504 ACM-11634 Update braces [release-2.9]
  backend/package-lock.json
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#3505 Add try/catch around search suggested search parsing
  frontend/src/routes/Home/Search/SearchPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3502 ACM-11634 Update braces
  backend/package-lock.json
  frontend/package-lock.json
Labels: lgtm, approved, dco-signoff: yes

#3506 chore(i18n): update translations
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
Labels: lgtm, approved, dco-signoff: yes

#3508 Create service account secret if not found
  setup.sh
  start-ocp-console.sh
Labels: lgtm, approved, dco-signoff: yes

#3511 Fleet view search link
  frontend/src/routes/Home/Overview/Overview.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  frontend/src/routes/Home/Search/components/ReuseableSearchbar.test.tsx
  frontend/src/routes/Home/Search/components/ReuseableSearchbar.tsx
  frontend/src/routes/Home/Search/components/__snapshots__/HeaderWithNotification.test.tsx.snap
  frontend/src/routes/Home/Search/components/__snapshots__/ReuseableSearchbar.test.tsx.snap
  frontend/src/ui-components/AcmPage/AcmPage.test.tsx
  frontend/src/ui-components/AcmPage/AcmPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3513 Add namspace field when it is not presented
  frontend/src/components/SyncEditor/SyncEditor.test.tsx
  frontend/src/components/SyncEditor/SyncEditor.tsx
  frontend/src/components/SyncEditor/process.ts
  frontend/src/components/SyncEditor/validation.ts
  frontend/src/routes/Governance/policies/CreatePolicy.tsx
  frontend/src/routes/Governance/policies/CreatePolicyAutomation.tsx
  frontend/src/routes/Governance/policy-sets/CreatePolicySet.tsx
Labels: lgtm, approved, dco-signoff: yes

#3514 [ACM-9303] Do not block search results on federated error
  frontend/src/components/LoadData.tsx
  frontend/src/routes/Home/Search/SearchPage.test.tsx
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/SearchResults/RelatedResults.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/components/HeaderWithNotification.tsx
  frontend/src/routes/Home/Search/components/__snapshots__/HeaderWithNotification.test.tsx.snap
  frontend/src/routes/Home/Search/search-helper.ts
Labels: lgtm, approved, dco-signoff: yes

#3520 [ACM-9303] Add alert on global search federated error
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Search/Search.tsx
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.tsx
  frontend/src/routes/Home/Search/components/SearchAlertGroup.test.tsx
  frontend/src/routes/Home/Search/components/SearchAlertGroup.tsx
  frontend/src/routes/Home/Search/search-helper.tsx
Labels: lgtm, approved, dco-signoff: yes

#3507 ACM-9431 - Auto import discovered ROSA clusters
  frontend/public/locales/en/translation.json
  frontend/src/resources/discovered-cluster.ts
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/schema.json
  frontend/src/selectors.ts
  frontend/src/wizards/common/AcmFormInputAdapter.tsx
Labels: lgtm, approved, dco-signoff: yes

#3516 Auto Import poilcy info alert
  frontend/public/locales/en/translation.json
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#3515 Display the diff of a ConfigurationPolicy in the console
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/components/CodeBlock.tsx
  frontend/src/routes/Governance/components/DiffModal.test.tsx
  frontend/src/routes/Governance/components/DiffModal.tsx
  frontend/src/routes/Governance/components/TemplateDetailTitle.test.tsx
  frontend/src/routes/Governance/components/TemplateDetailTitle.tsx
  frontend/src/routes/Governance/components/ViewDiffApiCall.test.tsx
  frontend/src/routes/Governance/components/ViewDiffApiCall.tsx
  frontend/src/routes/Governance/components/github.min.css
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.test.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetailsPage.tsx
  frontend/src/ui-components/AcmDescriptionList/AcmDescriptionList.tsx
  frontend/src/ui-components/AcmExpandable/AcmExpandableCard/AcmExpandableCard.tsx
  frontend/src/ui-components/AcmPage/AcmPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3521 ACM-11046 Indicate when application list is truncated
  frontend/package-lock.json
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/atoms.ts
  frontend/src/components/GetDiscoveredOCPApps.tsx
  frontend/src/components/PluginDataContextProvider.tsx
  frontend/src/hooks/application-queries.ts
  frontend/src/hooks/shared-react-query.ts
  frontend/src/lib/PluginDataContext.tsx
  frontend/src/lib/search.ts
  frontend/src/routes/Applications/Application.sharedmocks.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.test.tsx
  frontend/src/routes/Applications/ApplicationsPage.tsx
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  frontend/src/routes/Home/Overview/OverviewPageBeta.test.tsx
  frontend/src/routes/Home/Overview/OverviewPageBeta.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
  frontend/src/ui-components/AcmTable/AcmManageColumn.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#3524 Use Spanish (World) es_001 for Spanish
  frontend/i18n-scripts/memsource-upload.sh
Labels: lgtm, approved, dco-signoff: yes
