Repository stolostron/console, pull requests merged in 2024-07, with the labels that each got.

#3614 Fix bug Cannot filter policies by policy set
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#3620 chore(i18n): update translations
  frontend/public/locales/es/translation.json
  frontend/public/locales/fr/translation.json
Labels: lgtm, approved, dco-signoff: yes

#3621 chore(i18n): update translations (#3620)
  frontend/public/locales/es/translation.json
  frontend/public/locales/fr/translation.json
Labels: lgtm, approved, dco-signoff: yes

#3624 Remove kyverno policies from console
  frontend/src/wizards/Governance/Policy/stable/CM-Configuration-Management/README.md
  frontend/src/wizards/Governance/Policy/stable/CM-Configuration-Management/policy-kyverno-add-network-policy.yaml
  frontend/src/wizards/Governance/Policy/stable/CM-Configuration-Management/policy-kyverno-add-quota.yaml
  frontend/src/wizards/Governance/Policy/stable/CM-Configuration-Management/policy-kyverno-sync-secrets.yaml
  frontend/src/wizards/Governance/Policy/stable/README.md
Labels: lgtm, approved, dco-signoff: yes

#3625 ACM-9517 Fix AppSub Ansible jobs not displaying
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/applicationSubscription.js
Labels: lgtm, approved, dco-signoff: yes

#3642 ACM-10165 Fix KubeVirt bulk destroy
  frontend/src/lib/delete-cluster.test.ts
  frontend/src/lib/delete-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#3644 Update search SDK and apollo version
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Applications/ApplicationDetails/ApplicationDetails.test.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/relatedResources.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesAppSet.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesArgo.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesArgo.test.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/resourceStatusesSubscription.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyAppSet.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/topologyOCPFluxApp.js
  frontend/src/routes/Applications/CreateApplication/Subscription/components/SharedResourceWarning.js
  frontend/src/routes/Home/Search/search-sdk/search-sdk.ts
  frontend/src/routes/Home/Search/search-sdk/search-sdk.yml
  frontend/src/routes/Home/Search/search-sdk/searchQueries.graphql
  sonar-project.properties
Labels: lgtm, approved, dco-signoff: yes

#3653 ACM-12264 Add required --base-domain option to AWS HostedCluster command
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HypershiftAWSCLI.tsx
Labels: lgtm, approved, dco-signoff: yes

#3651 Remove Compliance wording messages from GRC UI pages
  frontend/public/locales/en/translation.json
  frontend/src/routes/Governance/policies/Policies.test.tsx
  frontend/src/routes/Governance/policies/Policies.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetails.tsx
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/ui-components/AcmCharts/AcmDonutChart/AcmDonutChart.stories.tsx
  frontend/src/ui-components/AcmCharts/AcmDonutChart/AcmDonutChart.test.tsx
  frontend/src/wizards/Governance/Policy/PolicyWizard.tsx
Labels: lgtm, approved, dco-signoff: yes

#3643 AcmTable csv export button addition
  frontend/src/routes/Home/Overview/SavedSearchesCard.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DownloadConfigurationDropdown.test.tsx
  frontend/src/ui-components/AcmTable/AcmManageColumn.tsx
  frontend/src/ui-components/AcmTable/AcmTable.test.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#3668 ACM-12772 Fix form match expressions required fields
  frontend/package-lock.json
  frontend/package.json
  frontend/src/wizards/Placement/MatchExpression.tsx
Labels: lgtm, approved, dco-signoff: yes

#3673 Standardize Cluster violations string
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.test.tsx
  frontend/src/routes/Governance/policy-sets/components/PolicySetDetailSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#3691 Fix for info alert documentation link
  frontend/public/locales/en/translation.json
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
Labels: lgtm, approved, dco-signoff: yes

#3686 Bump AI Lib to 2.11.3-cim
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3694 [ACM-12882] Overview page crash on app count
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#3696 migration task-buildah 0.1->0.2
  .tekton/console-acm-210-pull-request.yaml
  .tekton/console-acm-210-push.yaml
  .tekton/console-mce-mce-25-pull-request.yaml
  .tekton/console-mce-mce-25-push.yaml
Labels: approved, dco-signoff: yes

#3697 migration task-buildah 0.1->0.2
  .tekton/console-acm-211-pull-request.yaml
  .tekton/console-acm-211-push.yaml
  .tekton/console-mce-mce-26-pull-request.yaml
  .tekton/console-mce-mce-26-push.yaml
Labels: dco-signoff: yes

#3698 migration task-buildah 0.1->0.2
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: approved, dco-signoff: yes

#3695 [ACM-12704] Fleet view i18n misses
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Overview/OverviewPageBeta.tsx
Labels: lgtm, approved, dco-signoff: yes

#3701 [ACM-12704] 2.11 Fleet view i18n misses
  frontend/public/locales/en/translation.json
  frontend/src/routes/Home/Overview/OverviewPageBeta.tsx
Labels: lgtm, approved, dco-signoff: yes

#3705 ACM-12945 Use single-page mode and new domain for doc links
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/__snapshots__/GetHostedCard.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#3664 EDM-203: Add Overview tab extension
  frontend/src/plugin-extensions/extensions/OverviewTab.ts
  frontend/src/plugin-extensions/extensions/index.ts
  frontend/src/plugin-extensions/handler.ts
  frontend/src/plugin-extensions/properties/index.ts
  frontend/src/plugin-extensions/properties/overviewTabProps.ts
  frontend/src/plugin-extensions/types.ts
  frontend/src/routes/Home/Overview/ClustersTab.tsx
  frontend/src/routes/Home/Overview/Overview.sharedmocks.tsx
  frontend/src/routes/Home/Overview/Overview.test.tsx
  frontend/src/routes/Home/Overview/Overview.tsx
  frontend/src/routes/Home/Overview/OverviewClusterLabelSelector.tsx
  frontend/src/routes/Home/Overview/OverviewPage.test.tsx
  frontend/src/routes/Home/Overview/OverviewPage.tsx
  frontend/src/routes/Home/Overview/OverviewPageBeta.tsx
Labels: lgtm, approved, dco-signoff: yes

#3693 ACM-12797 - LaunchLogs uses default path for installer pod logs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HiveNotification.tsx
Labels: lgtm, approved, dco-signoff: yes

#3681 ACM-12098: Helper function for export of SubRows and returning CSV safe strings
  frontend/src/resources/utils/utils.ts
  frontend/src/ui-components/AcmTable/AcmTable.test.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#3710 ACM-12960-Unable-to-use-AWS-instance
  frontend/src/routes/Home/Overview/SavedSearchesCard.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/CreateClusterPool/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAWS.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAZR.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAWS.test.js.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataAZR.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#3709 Remove unused dependencies
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3711 ACM-13005 Turn off search queries on cluster details page
  frontend/src/hooks/application-queries.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#3671 ACM-12099: CSV export clusters
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterPools/ClusterPools.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/ClusterStatuses.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/components/useClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.test.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ManagedClusters.tsx
Labels: lgtm, approved, dco-signoff: yes
