Repository stolostron/console, pull requests merged in 2024-01, with the labels that each got.

#3205 Fix ordering of icons in GRC Clusters section
  frontend/src/routes/Governance/overview/Overview.tsx
Labels: lgtm, approved, dco-signoff: yes

#3215 ACM-9015 Fix Application count mismatch in Overview Beta
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Home/Overview/OverviewPageBeta.tsx
  frontend/src/routes/Home/Overview/__snapshots__/overviewDataFunctions.test.tsx.snap
  frontend/src/routes/Home/Overview/overviewDataFunctions.test.tsx
  frontend/src/routes/Home/Overview/overviewDataFunctions.tsx
Labels: lgtm, approved, dco-signoff: yes

#3193 ACM-5054 Add support for baremetal clusters
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetDetails.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSetDetails/ClusterSetInstallSubmariner/InstallSubmarinerForm.tsx
Labels: lgtm, approved, dco-signoff: yes

#3216 Bump AI lib to 2.9.14
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HostsForm.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/HypershiftAgentContext.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/hypershift-template.hbs
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#3213 Bump AI lib to 2.8.6
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#3219 [ACM-8903] Added ROSA-HCP type for discovered clusters
  frontend/public/locales/en/translation.json
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#3163 MGMT-15954 CIM: Add desiredCuration=install only after cluster is ready
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.test.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataAI.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataCIM.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/cim-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/nutanix-ai-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/nutanix-cim-template.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/cluster-curator.hbs
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
Labels: lgtm, approved, dco-signoff: yes

#3226 [ACM-8909] Updated discovered cloud provider mapping for redhat virtualization
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
Labels: lgtm, approved, dco-signoff: yes

#3229 [release-2.8] ACM-9495 translation scripts
  .gitignore
  frontend/i18n-scripts/languages.sh
  frontend/i18n-scripts/memsource-download.sh
  frontend/i18n-scripts/memsource-upload.sh
  frontend/i18next-parser.config.js
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/lib/wizardStrings.ts
Labels: lgtm, approved, dco-signoff: yes

#3228 [release-2.7] ACM-9491 update translations
  .gitignore
  frontend/i18n-scripts/languages.sh
  frontend/i18n-scripts/memsource-download.sh
  frontend/i18n-scripts/memsource-upload.sh
  frontend/i18next-parser.config.js
  frontend/package.json
  frontend/public/locales/en/translation.json
Labels: lgtm, approved, dco-signoff: yes

#3160 MGMT-16178: Update link for nutanix post-install docs
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#3161 MGMT-16188 Do not autoselect credentials for nutanix
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHelpers.js
Labels: lgtm, approved, dco-signoff: yes

#3223 ACM-9466 Optimize app count for cluster details page
  frontend/src/components/GetDiscoveredOCPApps.tsx
  frontend/src/lib/search.ts
  frontend/src/routes/Applications/Application.sharedmocks.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/StatusSummaryCount.tsx
Labels: lgtm, approved, dco-signoff: yes

#3231 follow-redirects pkg cve - reinstall packages with follow-redirects as dep
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3236 ACM-9536 Wrap search queries functions in useCallback
  frontend/src/components/GetDiscoveredOCPApps.tsx
Labels: lgtm, approved

#3235 ACM-9491 chore(i18n): update translations
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
Labels: lgtm, approved

#3240 revert rulecomponents pkg to 3.2.6
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3242 reinstall packages with follow-redirects as dep
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#3243 ACM-9664 cluster deployment ref fix (release 2.9.z)
  frontend/src/resources/cluster-deployment.ts
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#3245 remove params per migration from 0.1 to 0.2
  .tekton/console-mce-pull-request.yaml
  .tekton/console-mce-push.yaml
Labels: approved, dco-signoff: yes

#3248 ACM-9724 Fix flicker on saved search card load
  frontend/src/routes/Home/Search/SearchPage.tsx
  frontend/src/routes/Home/Search/components/SavedSearchQueries.tsx
  frontend/src/ui-components/AcmExpandable/AcmExpandableWrapper/AcmExpandableWrapper.stories.tsx
  frontend/src/ui-components/AcmExpandable/AcmExpandableWrapper/AcmExpandableWrapper.test.tsx
  frontend/src/ui-components/AcmExpandable/AcmExpandableWrapper/AcmExpandableWrapper.tsx
Labels: lgtm, approved, dco-signoff: yes
