Repository stolostron/console, pull requests merged in 2025-07, with the labels that each got.

#4713 Update Assisted Installer UI Lib to 2.15.2-cim
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#4669 ACM-21598 Missing translations on virtual machines pages
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/modals/VMActionModal.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/modals/snapshotModalBody.tsx
Labels: lgtm, approved, dco-signoff: yes

#4711 ACM-21596-Issues-with-Discovery-Cypress-automation
  frontend/src/components/AcmSelectBase.tsx
Labels: lgtm, approved, dco-signoff: yes

#4677 ACM-21116 Live Migration - UI Implementation - feature flag for live migration
  backend/config/VM_MIGRATION
  frontend/src/atoms.ts
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/utils.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/utils.tsx
  frontend/src/routes/Search/SearchResults/RelatedResults.tsx
  frontend/src/routes/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Search/SearchResults/utils.test.tsx
  frontend/src/routes/Search/SearchResults/utils.tsx
Labels: lgtm, approved, dco-signoff: yes

#4695 ACM-20341: fix null response in watch hooks
  frontend/package-lock.json
  frontend/packages/multicluster-sdk/package.json
  frontend/packages/multicluster-sdk/src/api/search/useMulticlusterSearchWatch.ts
  frontend/packages/multicluster-sdk/src/api/use-fleet-k8s-watch-resource/use-fleet-k8s-watch-resource.ts
Labels: approved, dco-signoff: yes, ok-to-test

#4720 ACM-20341: fix bug on useFleetPrometheus and add tests
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/index.test.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/index.ts
Labels: dco-signoff: yes, ok-to-test

#4731 ACM-21337 Multi clusterSDK Fleet Resource link
  frontend/packages/multicluster-sdk/src/api/FleetResourceLink.test.tsx
  frontend/packages/multicluster-sdk/src/api/FleetResourceLink.tsx
  frontend/plugins/mce/console-extensions.ts
  frontend/plugins/mce/console-plugin-metadata.ts
  frontend/src/routes/Infrastructure/VirtualMachines/VMRedirect.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VMRedirect.tsx
Labels: lgtm, approved, dco-signoff: yes

#4724 Update OWNERS
  frontend/src/routes/Governance/OWNERS
  frontend/src/wizards/Governance/OWNERS
Labels: lgtm, approved, dco-signoff: yes

#4655 ACM-21224: Multicluster SDK - merge managedClusterProxy into main codebase
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/lib/server.ts
  backend/src/lib/token.ts
  backend/src/routes/managedClusterProxy.ts
  backend/test/routes/managedClusterProxy.test.ts
  frontend/webpack.config.ts
  setup.sh
Labels: lgtm, approved, dco-signoff: yes

#4743 ACM-22314 prevent field renaming when creating/editing ClusterPermission
  frontend/src/routes/AccessControlManagement/AccessControlManagementForm.tsx
  frontend/src/routes/AccessControlManagement/RoleBindingSection.tsx
Labels: lgtm, approved, dco-signoff: yes

#4721 ACM-21808: Multicluster SDK - implement useHubClusterName hook
  frontend/packages/multicluster-sdk/README.md
  frontend/packages/multicluster-sdk/src/api/useHubClusterName.test.ts
  frontend/packages/multicluster-sdk/src/api/useHubClusterName.ts
  frontend/packages/multicluster-sdk/src/internal/cachedHubClusterName.ts
Labels: lgtm, approved, dco-signoff: yes

#4774 ACM-21807/ACM-20341: UseFleetSearchPoll
  frontend/package-lock.json
  frontend/packages/multicluster-sdk/package.json
  frontend/packages/multicluster-sdk/src/api/index.ts
  frontend/packages/multicluster-sdk/src/api/search/types.ts
  frontend/packages/multicluster-sdk/src/api/search/useFleetSearchPoll.ts
Labels: lgtm, approved, dco-signoff: yes

#4775 Fix toggle flicker for search related resource section
  frontend/src/routes/Search/SearchResults/SearchResults.tsx
Labels: lgtm, approved, dco-signoff: yes

#4795 ACM-22091: Fix test configuration for multicluster SDK
  frontend/packages/multicluster-sdk/__mocks__/dummy.ts
  frontend/packages/multicluster-sdk/__mocks__/file.mock.js
  frontend/packages/multicluster-sdk/jest.config.ts
  frontend/packages/multicluster-sdk/src/setupTests.ts
Labels: lgtm, approved, dco-signoff: yes

#4735 ACM-14666: HCP kubevirt 4.15.0-x86_64 updates toa multi architecture instead of x86_64
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.tsx
Labels: lgtm, approved, dco-signoff: yes

#4800 ACM-22575: ACM pages are not linked to perspective
  frontend/plugins/acm/console-extensions.ts
  frontend/plugins/mce/console-extensions.ts
Labels: lgtm, approved, dco-signoff: yes

#4761 Red Hat Konflux update console-acm-215
  .tekton/console-acm-215-pull-request.yaml
  .tekton/console-acm-215-push.yaml
  Makefile.prow
  frontend/package-lock.json
  frontend/packages/multicluster-sdk/package.json
  frontend/packages/react-form-wizard/package.json
Labels: approved, dco-signoff: yes

#4796 Fixing frontend install warnings.
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#4773 update assisted version 2.11.7-cim
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#4811 ACM-20341: update virtualmachine link
  frontend/packages/multicluster-sdk/src/api/FleetResourceLink.test.tsx
  frontend/packages/multicluster-sdk/src/api/FleetResourceLink.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4813 ACM-22670: Slide-out annotation panel's "no violation" check-marks should be green for compliant policies.
  frontend/src/routes/Governance/overview/SecurityGroupPolicySummarySidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#4821 ACM-22611 RBAC UI Implementation - Routes and Menu entries
  frontend/plugins/acm/console-extensions.ts
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/NavigationPath.tsx
  frontend/src/routes/Identities/Groups/GroupDetail.tsx
  frontend/src/routes/Identities/Groups/GroupRoleAssignments.tsx
  frontend/src/routes/Identities/Groups/GroupUsers.tsx
  frontend/src/routes/Identities/Groups/GroupYaml.tsx
  frontend/src/routes/Identities/Groups/Groups.test.tsx
  frontend/src/routes/Identities/Groups/Groups.tsx
  frontend/src/routes/Identities/IdentitiesManagement.test.tsx
  frontend/src/routes/Identities/IdentitiesManagement.tsx
  frontend/src/routes/Identities/IdentitiesPage.test.tsx
  frontend/src/routes/Identities/IdentitiesPage.tsx
  frontend/src/routes/Identities/ServiceAccounts/ServiceAccountDetail.tsx
  frontend/src/routes/Identities/ServiceAccounts/ServiceAccountGroups.tsx
  frontend/src/routes/Identities/ServiceAccounts/ServiceAccountRoleAssignments.tsx
  frontend/src/routes/Identities/ServiceAccounts/ServiceAccountYaml.tsx
  frontend/src/routes/Identities/ServiceAccounts/ServiceAccounts.test.tsx
  frontend/src/routes/Identities/ServiceAccounts/ServiceAccounts.tsx
  frontend/src/routes/Identities/Users/UserDetail.tsx
  frontend/src/routes/Identities/Users/UserGroups.tsx
  frontend/src/routes/Identities/Users/UserRoleAssignments.tsx
  frontend/src/routes/Identities/Users/UserYaml.tsx
  frontend/src/routes/Identities/Users/Users.test.tsx
  frontend/src/routes/Identities/Users/Users.tsx
  frontend/src/routes/Roles/RoleAssignments.test.tsx
  frontend/src/routes/Roles/RoleAssignments.tsx
  frontend/src/routes/Roles/RoleDetail.test.tsx
  frontend/src/routes/Roles/RoleDetail.tsx
  frontend/src/routes/Roles/RolePermissions.test.tsx
  frontend/src/routes/Roles/RolePermissions.tsx
  frontend/src/routes/Roles/RoleYaml.test.tsx
  frontend/src/routes/Roles/RoleYaml.tsx
  frontend/src/routes/Roles/Roles.test.tsx
  frontend/src/routes/Roles/Roles.tsx
  frontend/src/routes/Roles/RolesManagement.test.tsx
  frontend/src/routes/Roles/RolesManagement.tsx
Labels: lgtm, approved, dco-signoff: yes

#4817 Update Assisted Installer UI Lib to 2.14.9-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/DetailsForm.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#4818 Update Assisted Installer UI Lib to 2.15.3-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/DetailsForm.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#4831 Update Assisted Installer UI Lib to 2.15.3-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/DetailsForm.test.tsx.snap
Labels: lgtm, approved, dco-signoff: yes

#4833 Acm 22088 multicluster sdk configure automatic npm publishing2
  .github/workflows/publish-multicluster-sdk.yml
Labels: lgtm, approved, dco-signoff: yes

#4786 ACM-21807: SDK directory reorg, documentation
  frontend/packages/multicluster-sdk/README.md
  frontend/packages/multicluster-sdk/src/api/index.ts
  frontend/packages/multicluster-sdk/src/api/search/types.ts
  frontend/packages/multicluster-sdk/src/api/search/useFleetSearchPoll.ts
  frontend/packages/multicluster-sdk/src/api/useFleetSearchPoll.test.ts
  frontend/packages/multicluster-sdk/src/api/useFleetSearchPoll.ts
  frontend/packages/multicluster-sdk/src/internal/search/search-client.ts
  frontend/packages/multicluster-sdk/src/internal/search/search-sdk.test.ts
  frontend/packages/multicluster-sdk/src/internal/search/search-sdk.ts
  frontend/packages/multicluster-sdk/src/internal/search/search-sdk.yml
  frontend/packages/multicluster-sdk/src/internal/search/searchQueries.graphql
  frontend/packages/multicluster-sdk/src/internal/search/searchUtils.test.ts
  frontend/packages/multicluster-sdk/src/internal/search/searchUtils.ts
  frontend/packages/multicluster-sdk/src/types/fleet.ts
  frontend/packages/multicluster-sdk/src/types/index.ts
  frontend/packages/multicluster-sdk/src/types/search.ts
Labels: lgtm, approved, dco-signoff: yes

#4834 Acm 22088 multicluster sdk configure automatic npm publishing2
  .github/workflows/publish-multicluster-sdk.yml
Labels: approved, dco-signoff: yes
