Repository stolostron/console, pull requests merged in 2025-03, with the labels that each got.

#4310 ACM-18147: RHOV spoke of 4.18 displays Upgrading even after deploy completed.
  frontend/src/resources/utils/get-cluster.ts
Labels: lgtm, approved, dco-signoff: yes

#4300 Fix VAP policies getting shown in parameter resources table
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetailHooks.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetailsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#4314 ACM-18449 show more vm properties in vm table
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/routes/Search/__snapshots__/searchDefinitions.test.tsx.snap
  frontend/src/routes/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#4270 Standardize timestamp formatting using AcmTimestamp component across console UI
  frontend/package-lock.json
  frontend/package.json
  frontend/src/hooks/useProjects.tsx
  frontend/src/hooks/useTimezone.ts
  frontend/src/lib/AcmTimestamp.test.tsx
  frontend/src/lib/AcmTimestamp.tsx
  frontend/src/resources/utils/utils.ts
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
  frontend/src/routes/Applications/Application.sharedmocks.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.test.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/components/ClusterDetailsContainer.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/helpers/diagram-helpers.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.test.js
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgo.tsx
  frontend/src/routes/Applications/CreateApplication/CreateApplicationArgoPullModel.tsx
  frontend/src/routes/Applications/CreateApplication/EditArgoApplicationSet.tsx
  frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/index.js
  frontend/src/routes/Applications/Overview.test.tsx
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/routes/Applications/SubscriptionApplication.test.tsx
  frontend/src/routes/Applications/helpers/resource-helper.test.ts
  frontend/src/routes/Applications/helpers/resource-helper.tsx
  frontend/src/routes/Credentials/CredentialsPage.tsx
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.test.tsx
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
  frontend/src/routes/Governance/policies/PolicyTableCell.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsHistory.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsOverview.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyDetailsResults.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveredClusters.tsx
  frontend/src/routes/Search/__snapshots__/searchDefinitions.test.tsx.snap
  frontend/src/routes/Search/searchDefinitions.test.tsx
  frontend/src/routes/Search/searchDefinitions.tsx
  frontend/src/setupTests.ts
  frontend/src/ui-components/AcmRefreshTime/AcmRefreshTime.test.tsx
  frontend/src/ui-components/AcmRefreshTime/AcmRefreshTime.tsx
Labels: lgtm, approved, dco-signoff: yes

#4317 Clean up "Last sync requested" formatting
  frontend/src/routes/Applications/ApplicationDetails/ApplicationOverview/ApplicationOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#4318 ACM-18603 Fix false local-cluster offline warning in topology
  frontend/src/routes/Applications/ApplicationDetails/ApplicationTopology/model/computeStatuses.js
Labels: lgtm, approved, dco-signoff: yes

#4322 ACM-18631 Remove namespace from channel tooltip
  frontend/public/locales/en/translation.json
  frontend/src/routes/Applications/AdvancedConfiguration.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4321 ACM-18453-ClusterSets-not-included-in-First-Events-Packet
  backend/src/lib/server-side-events.ts
  frontend/src/components/LoadPluginData.tsx
Labels: lgtm, approved, dco-signoff: yes

#4323 ACM-17281 non admin users may see incorrect list of applications for 2.12
  backend/src/routes/aggregators/applications.ts
  backend/src/routes/events.ts
  backend/test/routes/aggregator.test.ts
Labels: lgtm, approved, dco-signoff: yes

#4325 ACM-18530: Unauthorized Message Appears when going through Credential Creation
  frontend/src/hooks/useProjects.tsx
  frontend/src/routes/Credentials/CredentialsForm.tsx
Labels: lgtm, approved

#4328 ACM-18820 Use spec.name instead of metadata.name for operator check
  backend/src/routes/operatorCheck.ts
  backend/test/routes/operatorCheck.test.ts
  frontend/src/components/ACMNotReadyWarning.test.tsx
  frontend/src/components/AutomationProviderHint.test.tsx
  frontend/src/resources/subscription-operator.ts
  frontend/src/routes/Applications/Application.sharedmocks.tsx
  frontend/src/routes/Governance/governance.sharedMocks.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.test.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/selectors.ts
Labels: lgtm, approved, dco-signoff: yes

#4335 ACM-18862 Use spec.name instead of metadata.name for operator check [release-2.12]
  backend/src/routes/operatorCheck.ts
  backend/test/routes/operatorCheck.test.ts
  frontend/src/components/ACMNotReadyWarning.test.tsx
  frontend/src/components/AutomationProviderHint.test.tsx
  frontend/src/resources/subscription-operator.ts
  frontend/src/routes/Applications/Application.sharedmocks.tsx
  frontend/src/routes/Governance/governance.sharedMocks.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomations.test.tsx
  frontend/src/routes/Infrastructure/Automations/AnsibleAutomationsForm.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  frontend/src/selectors.ts
Labels: lgtm, approved, dco-signoff: yes

#4308 [ACM-17420] Add ACM Searchbar to VM page for filtering
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/routes/Search/SearchPage.test.tsx
  frontend/src/routes/Search/SearchPage.tsx
  frontend/src/routes/Search/__snapshots__/searchDefinitions.test.tsx.snap
  frontend/src/routes/Search/components/Searchbar.test.tsx
  frontend/src/routes/Search/components/Searchbar.tsx
  frontend/src/routes/Search/search-sdk/search-sdk.ts
  frontend/src/routes/Search/search-sdk/searchQueries.graphql
  frontend/src/routes/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#4293 Bump AI Lib to 2.14.3-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.test.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAgentModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
Labels: lgtm, approved, dco-signoff: yes

#4345 Ansible job status Started, Finished columns - Fixes column definition to format data
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.test.tsx
  frontend/src/routes/Governance/components/AutomationDetailsSidebar.tsx
Labels: lgtm, approved, dco-signoff: yes

#4279 ACM-17500: Download Kubeconfig button from MCE should point to hc.status.customkubeconfig if that status is reported.
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftKubeconfigDownload.tsx
Labels: dco-signoff: yes

#4347 Update base image for Konflux builds
  Containerfile.acm.konflux
  Containerfile.mce.konflux
Labels: lgtm, approved, dco-signoff: yes

#4351 ACM-18935: Updating description for Red Hat OpenShift Virtualization
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/CreateClusterCatalog.tsx
Labels: lgtm, approved, dco-signoff: yes

#4353 Bump AI Lib to 2.14.3-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.test.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAgentModal.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/ScaleUpDialog.tsx
  frontend/src/routes/Infrastructure/InfraEnvironments/Details/HostsTab.tsx
Labels: lgtm, approved, dco-signoff: yes

#4350 Fix OpenShift Cluster Manager link
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.tsx
Labels: lgtm, approved, dco-signoff: yes

#4355 MGMT-20051: Number of control plane nodes is not edittable in MCE console
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/cim-template.hbs
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4359 [ACM-17421] Add modal for VM actions
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/VirtualMachines/VMActionModal.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VMActionModal.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/utils.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/utils.tsx
  frontend/src/routes/Search/Details/DetailsPage.tsx
  frontend/src/routes/Search/SearchResults/RelatedResults.test.tsx
  frontend/src/routes/Search/SearchResults/RelatedResults.tsx
  frontend/src/routes/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Search/SearchResults/__snapshots__/utils.test.tsx.snap
  frontend/src/routes/Search/SearchResults/utils.test.tsx
  frontend/src/routes/Search/SearchResults/utils.tsx
Labels: lgtm, approved, dco-signoff: yes

#4358 ACM-18525 Create Credential Modal PF5 update
  frontend/src/components/CreateCredentialModal.test.tsx
  frontend/src/components/CreateCredentialModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#4363 Labels column for VirtualMachine view
  frontend/src/routes/Search/__snapshots__/searchDefinitions.test.tsx.snap
  frontend/src/routes/Search/searchDefinitions.tsx
Labels: lgtm, approved, dco-signoff: yes

#4368 ACM-18956 Remove klusterlet CRD v1beta1 in import secret
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftImportCommand.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.tsx
Labels: lgtm, approved, dco-signoff: yes

#4357 ACM-18611: Update release image Pop up box text truncation issue
  frontend/src/components/BulkActionModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#4364 Bump AI Lib to 2.14.3-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/DetailsForm.test.tsx.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/utils.test.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/utils.test.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftKubeconfigDownload.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4371 Bump AI Lib to 2.14.3-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/DetailsForm.test.tsx.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/utils.test.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#4378 use crds.yaml in import command
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ImportCommand.tsx
Labels: lgtm, approved, dco-signoff: yes
