Repository stolostron/console, pull requests merged in 2025-06, with the labels that each got.

#4544 ACM-20991, ACM-20992: Fix key in PF5 Tbody in AcmTable component.
  frontend/src/routes/Applications/Overview.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#4555 Update Assisted Installer UI Lib to 2.14.6-cim
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#4370 MGMT-19356: NMStateConfig not picked up for hosts during cluster creation with 4.17
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/templates/assisted-installer/ai-template.hbs
Labels: lgtm, approved, dco-signoff: yes

#4562 Add loading component to delete resource modal while requesting user …
  frontend/src/routes/Search/components/Modals/DeleteResourceModal.tsx
Labels: lgtm, approved, dco-signoff: yes

#4557 ACM-20380: Multicluster SDK - Complete prettier and linting configuration
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/packages/eslint-config/index.js
  frontend/packages/eslint-config/package.json
  frontend/packages/multicluster-sdk/.eslintrc.js
  frontend/packages/multicluster-sdk/package.json
  frontend/packages/multicluster-sdk/src/api/FleetSupport.tsx
  frontend/packages/multicluster-sdk/src/api/useFleetK8sWatchResource.ts
  frontend/packages/prettier-config/package.json
Labels: lgtm, approved, dco-signoff: yes

#4567 Use locally cached token for development only as last resort
  backend/src/lib/token.ts
Labels: lgtm, approved, dco-signoff: yes

#4526 ACM-20689-Compress-ACM-Backend-Caches
  backend/src/lib/compression.ts
  backend/src/lib/gigantic.ts
  backend/src/lib/pagination.ts
  backend/src/lib/server-side-events.ts
  backend/src/routes/aggregators/applications.ts
  backend/src/routes/aggregators/applicationsArgo.ts
  backend/src/routes/aggregators/statuses.ts
  backend/src/routes/aggregators/uidata.ts
  backend/src/routes/aggregators/utils.ts
  backend/src/routes/events.ts
  backend/test/routes/aggregator.test.ts
Labels: lgtm, approved, dco-signoff: yes

#4519 MGMT-20654: Hypershift flow stuck on Node pool page
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/ControlDataHypershift.js
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/controlData/__snapshots__/ControlDataHypershift.test.js.snap
Labels: lgtm, approved, dco-signoff: yes

#4569 ACM-20814-Applicationset-detail-and-topology-pages-show-incorrect-cluster-resources
  backend/src/routes/aggregators/applicationsArgo.ts
Labels: lgtm, approved, dco-signoff: yes

#4570 [ACM-21109] VM page search filters should update the browser search p…
  frontend/public/locales/en/translation.json
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#4546 [ACM-21115] Live Migration - UI Implementation - create more generic feature flag hook
  README.md
  frontend/plugins/acm/console-extensions.ts
  frontend/plugins/acm/console-plugin-metadata.ts
  frontend/src/utils/flags/consts.ts
  frontend/src/utils/flags/index.ts
  frontend/src/utils/flags/useEnableAccessControlManagementMenuFlag.ts
  frontend/src/utils/flags/useFeatureFlags.test.ts
  frontend/src/utils/flags/useFeatureFlags.ts
Labels: lgtm, approved, dco-signoff: yes

#4573 ACM-21125: Incorrect locators(data-labels) in GRC policies table when one of the column is not enabled
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/ui-components/AcmTable/AcmTable.tsx
Labels: lgtm, approved, dco-signoff: yes

#4586 [2.13] Revert search availability hook
  frontend/src/atoms.ts
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
Labels: lgtm, approved, dco-signoff: yes

#4590 ACM-21352 Incorrect format of the time window in the YAML
  frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/index.js
Labels: lgtm, approved, dco-signoff: yes

#4589 ACM-21291 Filter ConfigPolicies from related resources
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetails.tsx
  frontend/src/routes/Governance/policies/policy-details/PolicyTemplateDetail/PolicyTemplateDetailsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#4600 ACM-21051-Error-handing-issue-for-policy-template-in-policy
  frontend/package-lock.json
  frontend/package.json
Labels: lgtm, approved, dco-signoff: yes

#4579 ACM-21273 Aligns restraint button advance search
  frontend/src/ui-components/AcmSearchInput/AcmSearchInput.tsx
Labels: lgtm, approved, dco-signoff: yes

#4595 Update Assisted Installer UI Lib to 2.11.6-cim
  frontend/package-lock.json
  frontend/package.json
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/CreateCluster.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/__snapshots__/DetailsForm.test.tsx.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/hypershift/utils.test.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/ClusterActionDropdown.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/DistributionField.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/cim/EditAICluster.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#4603 ACM-21019: Turn on checks for PRs against release-2.14
  .tekton/console-acm-214-pull-request.yaml
  .tekton/console-mce-mce-29-pull-request.yaml
Labels: lgtm, approved, dco-signoff: yes

#4578 ACM-21258-Edit-namespaces-bindings-not-aligned
  frontend/public/locales/en/translation.json
  frontend/src/components/AcmSelectBase.tsx
Labels: lgtm, approved, dco-signoff: yes

#4605 ACM-21019: Update versions for ACM 2.15
  .tekton/console-acm-214-pull-request.yaml
  .tekton/console-acm-214-push.yaml
  .tekton/console-mce-mce-29-pull-request.yaml
  .tekton/console-mce-mce-29-push.yaml
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/plugins/acm/console-plugin-metadata.ts
  frontend/plugins/mce/console-plugin-metadata.ts
  frontend/src/lib/doc-util.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryComponents/test-utils.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.test.tsx
  frontend/src/routes/Infrastructure/Clusters/DiscoveredClusters/DiscoveryConfig/DiscoveryConfig.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateClusterCatalog/common/__snapshots__/GetHostedCard.test.tsx.snap
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ImportCluster/ImportCluster.test.tsx
  renovate.json
  start-ocp-console.sh
Labels: lgtm, approved, dco-signoff: yes

#4619 ACM-20719: Update SDK readme with new hook description
  frontend/packages/multicluster-sdk/README.md
Labels: lgtm, approved, dco-signoff: yes

#4615 MGMT-20843: Hosted cluster deployment - "ValidReleaseImage 1327" etc
  backend/src/lib/compression.ts
Labels: lgtm, approved, dco-signoff: yes

#4620 [ACM-21300] user/group manual entry
  frontend/public/locales/en/translation.json
  frontend/src/components/AcmDataForm.tsx
  frontend/src/components/AcmSelectBase.tsx
  frontend/src/ui-components/AcmSelect/AcmSelect.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#4604 VM action auth fallback in non-fine grained RBAC context
  backend/src/app.ts
  backend/src/routes/events.ts
  backend/src/routes/virtualMachineProxy.ts
  backend/test/routes/virtualMachineProxy.test.ts
  frontend/public/locales/en/translation.json
  frontend/src/atoms.ts
  frontend/src/components/LoadData.tsx
  frontend/src/components/PluginDataContextProvider.test.tsx
  frontend/src/resources/multi-cluster-hub.ts
  frontend/src/routes/Infrastructure/VirtualMachines/VirtualMachinesPage.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/modals/VMActionModal.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/modals/VMActionModal.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/modals/snapshotModalBody.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/modals/snapshotModalBody.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/utils.test.tsx
  frontend/src/routes/Infrastructure/VirtualMachines/utils.tsx
  frontend/src/routes/Search/Details/DetailsPage.test.tsx
  frontend/src/routes/Search/Details/DetailsPage.tsx
  frontend/src/routes/Search/Details/SnapshotsTab.tsx
  frontend/src/routes/Search/SearchResults/RelatedResults.tsx
  frontend/src/routes/Search/SearchResults/SearchResults.tsx
  frontend/src/routes/Search/SearchResults/utils.test.tsx
  frontend/src/routes/Search/SearchResults/utils.tsx
Labels: lgtm, approved, dco-signoff: yes

#4633 Update overall OWNERS and access management owners
  OWNERS
  frontend/src/routes/AccessControlManagement/OWNERS
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4630 chore(i18n): update translations
  frontend/public/locales/es/translation.json
  frontend/public/locales/fr/translation.json
  frontend/public/locales/ja/translation.json
  frontend/public/locales/ko/translation.json
  frontend/public/locales/zh/translation.json
Labels: lgtm, approved, dco-signoff: yes

#4636 [ACM-21610] Refine user-facing text and terminology for ACM RBAC MVP
  frontend/plugins/acm/console-extensions.ts
  frontend/public/locales/en/translation.json
  frontend/src/App.tsx
  frontend/src/components/AcmFormData.ts
  frontend/src/routes/AccessControlManagement/AccessControlManagementForm.tsx
  frontend/src/routes/AccessControlManagement/AccessControlManagementPage.tsx
  frontend/src/routes/AccessControlManagement/AccessControlManagementTable.tsx
  frontend/src/routes/AccessControlManagement/AccessControlManagementTableHelper.tsx
  frontend/src/routes/AccessControlManagement/CreateAccessControlManagementPage.tsx
  frontend/src/routes/AccessControlManagement/RoleBindingSection.tsx
Labels: lgtm, approved, dco-signoff: yes

#4645 Standalone multicluster SDK
  frontend/package-lock.json
  frontend/packages/multicluster-sdk/package.json
  frontend/packages/multicluster-sdk/src/api/FleetResourceLink.tsx
  frontend/packages/multicluster-sdk/src/api/apiRequests.ts
  frontend/packages/multicluster-sdk/src/api/constants.ts
  frontend/packages/multicluster-sdk/src/api/index.ts
  frontend/packages/multicluster-sdk/src/api/search/search-client.ts
  frontend/packages/multicluster-sdk/src/api/search/search-sdk.ts
  frontend/packages/multicluster-sdk/src/api/search/search-sdk.yml
  frontend/packages/multicluster-sdk/src/api/search/searchQueries.graphql
  frontend/packages/multicluster-sdk/src/api/search/searchUtils.ts
  frontend/packages/multicluster-sdk/src/api/search/types.ts
  frontend/packages/multicluster-sdk/src/api/search/useMulticlusterSearchWatch.ts
  frontend/packages/multicluster-sdk/src/api/use-fleet-k8s-watch-resource/use-fleet-k8s-watch-resource.ts
  frontend/packages/multicluster-sdk/src/api/use-fleet-k8s-watch-resource/utils.ts
  frontend/packages/multicluster-sdk/src/api/useBackendURL.ts
  frontend/packages/multicluster-sdk/src/api/useFleetK8sAPIPath.ts
  frontend/packages/multicluster-sdk/src/api/useFleetK8sWatchResource.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/constants.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/index.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/usePoll.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/useSafeFetch.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/useURLPoll.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/utils.ts
  frontend/packages/multicluster-sdk/src/api/useHubClusterName.ts
  frontend/packages/multicluster-sdk/src/api/utils/api-resource-list.ts
  frontend/packages/multicluster-sdk/src/api/utils/requirements.ts
  frontend/packages/multicluster-sdk/src/api/utils/searchPaths.ts
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/EventComponent.tsx
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/EventStream.tsx
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/EventStreamList.tsx
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/TogglePlay.tsx
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/WithScrollContainer.tsx
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/constants.ts
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/utils.ts
  frontend/packages/multicluster-sdk/src/components/index.ts
  frontend/packages/multicluster-sdk/src/extensions/index.ts
  frontend/packages/multicluster-sdk/src/extensions/resource.ts
  frontend/packages/multicluster-sdk/src/globals.d.ts
  frontend/packages/multicluster-sdk/src/index.ts
  frontend/packages/multicluster-sdk/src/types/fleet.ts
Labels: approved, dco-signoff: yes

#4663 Updates anchors for proxy-vmware and deprecations-acm
  frontend/src/lib/doc-util.tsx
Labels: lgtm, approved, dco-signoff: yes

#4661 Resolve TLS handshake error on VM GET requests
  backend/src/routes/virtualMachineProxy.ts
Labels: lgtm, approved, dco-signoff: yes

#4635 ACM-21488-The-clusters-field-is-None-for-appset-in-app-table
  backend/src/routes/aggregators/applicationsArgo.ts
Labels: lgtm, approved, dco-signoff: yes

#4662 Fix backend url from async to non-async
  frontend/package-lock.json
  frontend/packages/multicluster-sdk/package.json
  frontend/packages/multicluster-sdk/src/api/apiRequests.ts
  frontend/packages/multicluster-sdk/src/api/constants.ts
  frontend/packages/multicluster-sdk/src/api/search/search-client.ts
  frontend/packages/multicluster-sdk/src/api/search/useMulticlusterSearchWatch.ts
  frontend/packages/multicluster-sdk/src/api/useBackendURL.ts
  frontend/packages/multicluster-sdk/src/api/useFleetClusterNames.ts
  frontend/packages/multicluster-sdk/src/api/useFleetK8sAPIPath.ts
  frontend/packages/multicluster-sdk/src/api/useFleetK8sWatchResource.ts
  frontend/packages/multicluster-sdk/src/api/useFleetPrometheusPoll/index.ts
  frontend/packages/multicluster-sdk/src/api/useHubClusterName.ts
  frontend/packages/multicluster-sdk/src/api/utils/api-resource-list.ts
  frontend/packages/multicluster-sdk/src/components/FleetResourceEventStream/EventStream.tsx
  frontend/packages/multicluster-sdk/src/types/fleet.ts
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4647 add odf to start-ocp-console
  start-ocp-console.sh
Labels: lgtm, approved, dco-signoff: yes

#4598 ACM-21312 Script to update ACM and MCE console images for testing PR builds
  update-console-images.sh
Labels: lgtm, approved, dco-signoff: yes

#4671 Fix fleetresourcelink
  frontend/packages/multicluster-sdk/src/api/FleetResourceLink.tsx
Labels: lgtm, approved, dco-signoff: yes, ok-to-test

#4676 ACM-21838-Fix-ACM-Test-problems
  frontend/src/lib/test-util.ts
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/ClusterDetails/ClusterOverview/ClusterOverview.test.tsx
  frontend/src/routes/Infrastructure/Clusters/ManagedClusters/components/HypershiftImportCommand.tsx
  frontend/src/routes/Search/Details/DetailsPage.test.tsx
Labels: lgtm, approved, dco-signoff: yes

#4693 [ACM-21798] Edit VM action should use fine-grained rbac if enabled
  backend/src/routes/virtualMachineProxy.ts
  frontend/src/routes/Search/Details/YAMLPage.tsx
Labels: lgtm, approved, dco-signoff: yes
